### ISSUE TITLE
[CommonHTML] Inconsistent horizontal spacing when loading a new font

### ISSUE THREAD

**Issue by jsmaniac** [mathjax/MathJax#1837] opened 2017-09-14 10:52 UTC
In the example below, the spacing between the `::` and the `=` is not the same on the first and fifth equations (it's more visible on the fifth). These equations load a new font, which might be the cause for the larger space. The equations 1–4 are strictly identical, and so are the equations 5–8. I wasn't able to build a smaller example, the problem disappears when removing one of the `:` or when removing the `\raise`.

![The space between the :: and the = is a bit wider on the first line, and much wider on the fifth line](http://jahvascriptmaniac.free.fr/2017/spacing.png)

```
<!DOCTYPE html>
<html>
  <head>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions:["tex2jax.js"],
        tex2jax:{displayMath:[["\\[", "\\]"]]},
        jax: ["input/TeX", "output/CommonHTML"]
      });
    </script>
    <script type="text/javascript" src="MathJax/MathJax.js?config=default"></script>
  </head>
  <body>
    <!-- Loads bf font: -->
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathbf{\unicode{x03BB}}\]
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathbf{\unicode{x03BB}}\]
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathbf{\unicode{x03BB}}\]
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathbf{\unicode{x03BB}}\]
    <!-- Loads sf font: -->
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathsf{\unicode{x03BB}}\]
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathsf{\unicode{x03BB}}\]
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathsf{\unicode{x03BB}}\]
    \[a \raise0.4mu{::}\hspace{-8mu}=\mathsf{\unicode{x03BB}}\]
  </body>
</html>
```

**Comment by pkra** [comment] 2017-09-14 13:50
Thanks for the report. We can reproduce the issue and will look into it.

**Comment by dpvc** [comment] 2017-09-16 18:50
OK, here's what's happening:  when the content of the `\mathsf` command is being typeset, MathJax has to load the data for the sans-serif font, which means MathJax has to pause in order to wait for that to load.  Once that loads, it restarts the typesetting operation and lays out the expression again.  But it turns out that the information about the width of the earlier `::` characters doesn't get cleared, and when they are played out again, their width is added to the element *again*.  Usually, this width isn't used, but the `\raise{}` introduces an `<mpadded>` element, and in that case, the width *is* used, and since it is wrong, the output end up twice as wide as it should.

The solution is to clear the bounding box information so that any earlier bounding box data (left over from an earlier attempt to typeset the expression) is discarded.

Here is a patch that you can include in your pages for now, until the bug is fixed in MathJax itself.  Add the following script

```
MathJax.Hub.Register.StartupHook("CommonHTML Jax Ready", function () {
  var MML = MathJax.ElementJax.mml;
  var TOCHTML = MML.chars.prototype.toCommonHTML;
  MML.chars.Augment({
    toCommonHTML: function (node,options) {
      this.CHTML = null;
      TOCHTML.call(this,node,options);
    }
  });
});
</script>
```
just **before** you load `MathJax.js` itself, or include the content of the script in your configuration file, if you are using a local configuration.

**Comment by pkra** [comment] 2017-09-17 14:10
=> renamed title.

**Comment by jsmaniac** [comment] 2017-09-18 10:02
Thanks for the quick patch! And sorry for the title, I must've been distracted as I actually checked that the bug occurs with CommonHTML (and not with HTML-CSS).

**Closed** 2018-01-22 16:40 UTC
Labels: Accepted, Merged, Test Needed
