### ISSUE TITLE
CommonHTML scale-all-math has no effect

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1324] opened 2015-12-03 08:54 UTC
HTML-CSS and SVG scale fine but on the CommonHTML it has no effect. 

I thought I had run into this and understood the reason when I was recording the a11y screencasts. Will look again later.

**Comment by dpvc** [comment] 2015-12-03 12:37
It's the MathJax menu item for setting the scale that is at fault, not CommonHTML itself (if you reload the page after setting the scale, you will see the new scale in effect).  The problem is that the menu item has logic for each individual output jax, and wasn't updated to include CommonHTML.

**Comment by dpvc** [comment] 2015-12-03 13:14
The `issue1324` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment] 2015-12-04 19:42
=> Merged.

**Closed** 2015-12-04 19:42 UTC
Labels: Accepted, Merged, Test Needed
