### ISSUE TITLE
Make frown/smile stretch via an alias for top/bottom parenthesis [was: Add permanent workaround for mover with frown / arc]

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#928] opened 2014-10-02 16:13 UTC
None of the supported fonts can do a stretchy arc (using `&#x2322;`) but we can do stretchy parenthesis.

Something like 

    <script type="text/x-mathjax-config"> 
        MathJax.Hub.Register.StartupHook("MathML Jax Ready",function () { 
          MathJax.InputJax.MathML.prefilterHooks.Add(function (data) { 
            data.math = data.math.replace(/⌢/g, '&#x23dc;'); 
          }); 
        }); 
    </script> 

is a decent hack (better on some fonts like STIX). 

This feature request is to add this internally.

**Comment by devon** [comment] 2015-02-27 02:32
The \arc is quite useful in geometry class. It will be great if MathJax support this.

**Comment by dpvc** [comment] 2015-04-14 18:40
This is a duplicate of #567

**Comment by dpvc** [comment] 2015-04-14 20:39
I've added `\overparen` and `\underparen` to make stretchy over- and under-parentheses.  I didn't make it `\overarc` since it really isn't the correct character for that.  Users can define `\overarc` as `\overparen` if they want to.

**Comment by pkra** [comment] 2015-04-15 08:05
> This is a duplicate of #567

Sure, there's some overlap but my OP was about adding a hack for frown (to output processing, independent of input); it actually came up regarding MathML (via Jean).

>  I didn't make it \overarc since it really isn't the correct character for that. 

I don't have a problem with deciding against it; it would've been nice to discuss it though.

> I've added \overparen and \underparen to make stretchy over- and under-parentheses. 

Sounds fine but seems unrelated to the issue.

**Comment by dpvc** [comment] 2015-04-15 13:11
> Sure, there's some overlap but my OP was about adding a hack for frown (to output processing, independent of input); it actually came up regarding MathML (via Jean).

Sorry, I didn't understand originally the distinction you were making between this and 567.

In terms of frown, this is not marked as a character that is stretchy by default in the MathML operator table, so

``` html
<math>
  <mover>
    <mtext>underneath</mtext>
    <mo>&#x2322;</mo>
  </mover>
</math>
```

should not stretch (if we use the operator table from appendix C of the spec, even though it is non-normative).

Since the stretchy character tables for the font data were generated based on the operator table from Appendix C, the frown doesn't have any stretchy data.  So 

``` html
<math>
  <mover>
    <mtext>underneath</mtext>
    <mo stretchy="true">&#x2322;</mo>
  </mover>
</math>
```

would also not stretch.  Of course, the spec allows for that, as it does indicate that not all characters will be able to stretch.

If we want to add data to make frown (and presumably smile) to stretch, that can be done (and relatively easily, as it could just be an alias for U+23DC (top parenthesis).  There is no need for a pre-filter that might alter the character in situations where it is not necessary to do so.

> I don't have a problem with deciding against it; it would've been nice to discuss it though.

That is why I mentioned what macros I had used and why I hadn't done a different one.  This is not yet merged into develop, and is marked as "Ready for Review", so it seems to be that this is the opportunity for discussion, and this *is* the discussion of it.  If an alternative (or additional) macro should be used, this is when that could be suggested.  Also, Fred's issue 567 suggested several possibilities, but no discussions ensued, so I made a choice that corresponded to the characters involved, and have proposed this fix for (what I thought) the issue was.  If it is not the right fix, that can certainly be discussed here.

This is a two line change.  Suggesting the solution essentially *is* providing the update.  This is a proposal; it can be accepted, or rejected, or modified.  I do not see why it is a problem to make the proposal along with the tinny bit of code that implements it.

**Comment by dpvc** [comment] 2015-04-15 14:09
OK, I see one of the problems:  I forgot to push the commit, so the code wasn't available here.  It is the `issue928` branch of my fork of MathJax.

**Comment by pkra** [comment] 2015-04-15 14:15
> In terms of frown, this is not marked as a character that is stretchy by default in the MathML operator table

Ah! I didn't realize this when I looked up the old threads before I did the OP. => Labeling this `MML spec limitation` for tracking.

> If we want to add data to make frown (and presumably smile) to stretch, that can be done (and relatively easily, as it could just be an alias for U+23DC (top parenthesis). 
> There is no need for a pre-filter that might alter the character in situations where it is not necessary to do so.

That's what I was after with this issue -- but I didn't do a good job at describing it.

>  This is not yet merged into develop, and is marked as "Ready for Review", so it seems to be that this is the opportunity for discussion

I misunderstood `Ready for Review` + `QA Unit Test Wanted` to mean code has been merged. On second thought, I should have noticed that no commit message mentions this issue / shows up on this thread and should have asked for clarification; sorry about that.

So to (hopefully) respond better this time

* I think over/underparen are good additions 
  * perhaps they deserve their own issue (or #567). 
* I'm in favor of making frown/smile stretchable via an alias
  * but since it's non-standard I can reach out the WG first. 

I've taken the liberty to rename the issue. Again, sorry about being confused and causing more confusion.

**Comment by pkra** [comment] 2015-04-15 14:16
FYI I didn't see the newer comment while writing my last one.

**Comment by dpvc** [comment] 2015-04-15 14:24
> I misunderstood `Ready for Review` + `QA Unit Test Wanted` to mean code has been merged.

Ah, I see.  `Merged` is for merged into the develop branch.  `Ready for Review` is for proposed code changes, and ideally would call for a review and OK from other developers.  Since we don't really have any others, I've been leaving them up for comment for a few days and then merging.  If we ever get a larger core of developers, we can make a more formal review process.

Technically, `QA- Unit Test Wanted` shouldn't be applied until `Merged`, I guess, but I've been adding them at the same time so that I can work on test cases if needed and don't forget to later.  I can wait until `Merged` if that helps any.

**Comment by dpvc** [comment] 2015-04-15 14:25
OK, I can change the branch to `issue567` and make a new one for the added stretchy character.

**Comment by dpvc** [comment] 2015-04-15 15:19
OK, I've added the data for stretchy U+2322 (FROWN), U+2323 (SMILE), and also U+2312 (ARC) to be aliases for the top and bottom parentheses.  This is in the `issue928` branch of my fork of MathJax.

**Comment by dpvc** [comment] 2015-04-21 20:53
==> Merged

**Closed** 2015-04-21 20:53 UTC
Labels: Feature Request, Merged, MML spec limitation, Test Needed

**Comment by dpvc** [comment] 2015-08-17 17:11
=> in testsuite

MathMLToDisplay/Topics/StretchyChars/horizontal.html?op=2312
MathMLToDisplay/Topics/StretchyChars/horizontal.html?op=2322
MathMLToDisplay/Topics/StretchyChars/horizontal.html?op=2323
