### ISSUE TITLE
Broken accents on iOS

### ISSUE THREAD

**Issue by goerz** [mathjax/MathJax#2091] opened 2018-12-04 04:27 UTC
I am currently still seeing #1737 on iOS Safari, e.g. https://newtonprop.readthedocs.io/en/latest/newton.html where the hats over operators are shifted to the right (Ĥ in the first equation).

**Comment by pkra** [comment] 2018-12-04 08:09
Duplicate of #1737 (regression in Safari) which was worked around in 2.7.2 -- 2.7.5 is the current version.  The linked site is still using MathJax 2.7.1.

**Closed as completed** 2018-12-04 22:25 UTC
Labels: Duplicate
