### ISSUE TITLE
Any plans to support STIX-web with CommonHTML?

### ISSUE THREAD

**Issue by chris-malloy-mri** [mathjax/MathJax#1808] opened 2017-07-13 18:17 UTC
It seems currently we only have the option of using the Tex font.

**Comment by pkra** [comment] 2017-07-13 20:05
Duplicate of https://github.com/mathjax/MathJax/issues/1351.

This will be in the v3 release.

**Comment by chris-malloy-mri** [comment] 2017-07-13 20:10
Thank you. I assume v3 has no scheduled release date yet?

**Comment by pkra** [comment] 2017-07-14 07:19
There isn't.

You can follow the discussions of the TC at https://groups.google.com/forum/#!forum/mathjax-dev and the development at https://github.com/mathjax/mathjax-v3. We aim for a first set of components by the end of the summer.

**Closed** 2017-08-31 08:04 UTC
Labels: Duplicate
