### ISSUE TITLE
[TeX input] mhchem and mathrm conflicting

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1427] opened 2016-03-30 14:07 UTC
Reported on http://stackoverflow.com/questions/36307606/how-to-use-mathjax-mhchem-extension-with-mathjax-cdn. 

Something like `\ce{^{14}_6 \mathrm{C}}` throws an error (mathrm missing arguments). `\rm` is a workaround where possible.

I'm not sure in how far this is expected behavior given the mhchem parers; fwiw, it works in LaTeX with mhchem set to version 1 and version 4. But I don't know the original mhchem well enough.

**Comment by mikkorantalainen** [comment] 2016-03-30 16:20
This may be a regression. If I remember correctly this kind of usage used to work with MathJax 2.3.x.

**Comment by mikkorantalainen** [comment] 2016-03-30 16:21
This also works with latest MathJax: `\ce{^{14}_6 $(\mathrm{C})$}`

**Comment by pkra** [comment] 2016-03-30 20:42
> This may be a regression. 

Yikes, you're correct. `$\require{mhchem} \ce{^{14}_6 \mathrm{C}}$` works  [here](http://cdn.mathjax.org/mathjax/2.5-latest/test/sample-dynamic-2.html).

**Comment by dpvc** [comment] 2016-03-31 12:36
In version 2.6 we modified the mhchem extension to use mmultiscripts for prescripts rather than using super and subscripts on an empty element.  The logic for this doesn't handle this situation properly.  I've looked at it and there is not an easy fix, and since the mhchem extension is being totally rewritten to be more consistent with the LaTeX version, I'm not sure its worth the time to fix the current version.

Note also that the `\mathrm` is redundant, as `\ce{^{14}_6 C}` already typesets `C` using `\mathrm`.

**Comment by mikkorantalainen** [comment] 2016-03-31 13:17
I'm fine with MathJax + mhchem extension not supporting `\ce{^{14}_6 \mathrm{C}}` but this backwards incompatible change needs to be documented somewhere.

**Comment by pkra** [comment] 2016-03-31 13:23
> this backwards incompatible change needs to be documented somewhere.

It's a bug so I think this is the right place to document it. (@dpvc only described that the fix will have to wait until the other work on the mhchem extension is completed.)

**Comment by dpvc** [comment] 2016-06-14 21:33
The new version of mhchem handles the situation properly, so I'm going to close this issue.

**Closed by dpvc** 2016-06-14 21:33 UTC
Labels: Accepted

**Comment by pkra** [comment] 2016-06-15 07:32
Two question: 

Should we drop this from the milestone?
Should we mark mhchem issues as `upstream` going forward?

**Comment by dpvc** [comment] 2016-06-15 12:53
> Should we drop this from the milestone?

I don't think so.  We are going to make the current `mhchem` point to the new one, so I think leaving this one in the milestone is fine, since the new version fixes it.

> Should we mark mhchem issues as `upstream` going forward?

That sounds good.
