### ISSUE TITLE
MathJax is broken on MathJax's site after changing the rendering mode 

### ISSUE THREAD

**Issue by guilhermesimoes** [mathjax/MathJax#1058] opened 2015-02-12 15:58 UTC
Steps to Reproduce:

1. Go to http://www.mathjax.org/

2. Click on the "View samples" button below "High-quality typography".

3. Select the `MathML` rendering mode. Click Ok.

4. A mjx.menu cookie is set. Now, even if you change the rendering mode back to `HTML-CSS` and refresh the page, the page will be broken because of the cookie.

**Comment by pkra** [comment] 2015-02-13 09:39
Thanks. This is a duplicate of https://github.com/mathjax/MathJax-website/issues/19 (and others)

**Closed by pkra** 2015-02-13 09:39 UTC
