### ISSUE TITLE
Action extension and AMS alignment structures

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2111] opened 2019-01-16 11:39 UTC
I have found unexpected problems when mixing the action extension with AMS alignment structures. Example page at
https://cdi2tp.math.tecnico.ulisboa.pt/test
Example code
\begin{align*}\int_a^b f & \int_a^b f  \\ & \leq \mathtip{\leq}{\sup(f+g)\leq \sup f + \sup g}\end{align*}

**Comment by dpvc** [comment] 2019-01-16 12:20
It is actually the accessibility extension that is causing the problem.  It looks like the semantic enrichment is damaging the tooltip construction (the pieces are rearranged, destroying the nesting structure).  We'll have to look into it further.

**Comment by zorkow** [comment] 2019-01-16 13:57
The problem is indeed due to incorrect treatment of an already existing `maction` element in the semantic enrichment in SRE. I'll file an upstream issue. 
For now the best course of action is to disable a11y extension.

**Comment by dpvc** [comment] 2022-03-11 17:01
This seems to have been resolved in an update to SRE.  I am no longer able to reproduce it.

**Closed by dpvc** 2022-03-11 17:01 UTC
Labels: Accepted, Upstream, SRE
