### ISSUE TITLE
MathJax 3 dies while trying to escape its commands.

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2364] opened 2020-03-07 10:13 UTC
In MathJax 2 I was able to write a line of HTML like
`<p>Write \$\int f(x)\, dx\$ instead of \int f(x)\, dx</p>`
escaping MathJax commands.

I have found that such a line kills MathJax 3.0.1, appearing in the web console:
`TypeError: t.setAttribute is not a functiontex-mml-chtml.js:1:262087`

Example pages (identical except for MathJax versions) are:
[https://math.tecnico.ulisboa.pt/test.php](https://math.tecnico.ulisboa.pt/test.php) (MathJax 3)
[https://math.tecnico.ulisboa.pt/test2.php](https://math.tecnico.ulisboa.pt/test2.php) (MathJax 2)

**Comment by dpvc** [comment] 2020-03-09 13:46
This is a duplicate of #2327, which will be fixed in the next release.  That linked issue contains a work-around that you can use in the meantime.

**Closed** 2020-05-12 15:16 UTC
Labels: Duplicate, v3
