### ISSUE TITLE
Missing space both sides of the '+' when using '_'

### ISSUE THREAD

**Issue by views63** [mathjax/MathJax#2216] opened 2019-10-13 02:06 UTC
Issue Summary

Steps to Reproduce

Go to the [MathJax demo](https://www.mathjax.org/#demo) site
Paste the following equation in:

`$\mathbf {x}_0+C t$`

Click the "Render HTML" button.

![图片](https://user-images.githubusercontent.com/175116/66709934-c3f9f780-eda0-11e9-997d-dadb5f690576.png)

Technical details
    Client OS: Windows 10 64 bit
    Browsers: Firefox (69.03 (64-bit))

**Comment by dpvc** [comment] 2019-10-13 19:10
This is a duplicate of #2187 and is fixed by the same pull request listed for that issue.

**Closed** 2019-10-19 19:55 UTC
Labels: Duplicate
