### ISSUE TITLE
"\hat" slightly offset

### ISSUE THREAD

**Issue by rvuduc** [mathjax/MathJax#1766] opened 2017-06-07 21:23 UTC
I'm observing that `\hat{.}` places the "hat" in a slightly wrong position. Is it something in my browser environment or a (known) issue with Mathjax? The problem does not occur with other accents, such as `\widehat{.}` or `\dot{.}`. See the attached screenshot.

![mathjax-hat-problem](https://user-images.githubusercontent.com/5316640/26902088-007a6e00-4ba6-11e7-9201-ba4c24fd5036.png)

(This capture comes from a macOS Sierra box in Safari, ~~though I've also observed the issue in Chrome and Firefox on the same system~~. _Correction:_ I do not observe the problem in Chrome or Firefox on the same box, so I guess it's a Safari issue. Any advice on how to workaround it is appreciated nonetheless!)

**Comment by pkra** [comment] 2017-06-07 21:38
Thanks for the report.

Duplicate of #1737 / #1709.

This is a browser bug.

**Closed** 2017-08-31 08:04 UTC
Labels: Duplicate

**Comment by alecjacobson** [comment] 2018-10-02 00:14
Obviously not an ideal solution, but for others landing here I used this as a hot fix 

     $\renewcommand{\hat}[1]{\widehat{#1}}$

**Comment by pkra** [comment] 2018-10-02 06:58
@alecjacobson a workaround was implemented for Safari. If you're still seeing this, please file a new bug with details.
