### ISSUE TITLE
Geometry of mathematics and physics with Mathjax, in addition to formulas.

### ISSUE THREAD

**Issue by dirkncl** [mathjax/MathJax#2015] opened 2018-07-01 10:23 UTC
I like Mathjax because it does not use external libraries such as Jquery, Angular, React, require and define and more.
But although the content is still fat, but almost complete, perhaps in the following release mathjax may include Tikz / pgf or as a substitute for Tikz / pgf, thus complete mathjax can read tex / latex documents in general include mathematical and physics geometry drawings.

**Comment by dpvc** [comment] 2018-07-02 22:14
This is a duplicate of #41.  See also #1126.

**Comment by dirkncl** [comment] 2018-07-03 06:14
Ok !, I have read it, but there is no solution.
Our hope is: only with mathjax (pure HTML5 / Javascript) and without outside libraries like D3, ThreeJS, Desmos Calculator, algebra and others, we can read "document Tex / Latex".
Maybe Team Mathjax is saturated? ... because only with the addition of a few canvas and svg programs I think a great mathjax team can make it.
Or is it "document Tex / Latex" a lot of variety so it's rather difficult to compile everything in one program? ...
My proposal is Mathjax reserves the right to create "Tex / Latex" documents of Mathjax and may someday become a standard "mathjax" document Tex / Latex "for browser (pure htm5 / javascript).
But if Team Mathjax is already Saturated, I think Mathjax is currently very good, let alone being developed Mathjax3 is simple and slim, although the placement sintaxnya must be in <script> tags unlike normal mathjax.

**Comment by dpvc** [comment] 2018-07-05 23:59
My reference was only to the fact that this has been requested before, and that the discussion indicated that it is a substantial endeavor (not just "a few canvas and svg programs").  We have limited resources, and are not able to add every feature that we might like to.  In particular, graphics processing is outside the scope of MathJax's mission, which is to typeset mathematical notation in the browser, so although we understand the desire for Tikz, it is unlikely to be implemented in MathJax any time soon unless a community member is able to do so and contributes it to the project.  This has happened with the mhchem extension, for example.

MathJax is not intended to be a complete TeX processor, and so will not ever process complete TeX or LaTeX documents on its own.

**Closed** 2020-05-12 16:08 UTC
Labels: Duplicate, Feature Request
