### ISSUE TITLE
Bug: parse error with _

### ISSUE THREAD

**Issue by yonh** [mathjax/MathJax#2087] opened 2018-11-28 11:29 UTC
I am try to parse this formula
```
$$
0.1_{(2)} = 0.1_{(10)}
$$
```
But it doesn't work,But when I use this formula, it works.
```
$$
0.1_{(2)} = 0.1\_{(10)}
$$
```

I think the question is abount `{}`

```

0.1_{(2)} = 0.1_2   # right
0.1_{(2)} = 0.1_23 # right

0.1_{(2)} = 0.1_{2}3 # wrong

```

**Comment by pkra** [comment] 2018-11-28 12:47
Please check the issue tracker before posting -- duplicate of https://github.com/mathjax/MathJax/issues/2081

**Closed by pkra** 2018-11-28 12:47 UTC
Labels: Duplicate
