### ISSUE TITLE
\\ cannot produce breakline

### ISSUE THREAD

**Issue by zq1997** [mathjax/MathJax#2382] opened 2020-03-25 12:52 UTC
### Issue Summary

`\\` cannot produce breakline in chtml.

### Steps to Reproduce:

Just try this html 
```html
<html>

<head>
    <script defer src="https://cdn.jsdelivr.net/npm/mathjax/es5/tex-chtml-full.js"></script>
</head>

<body>
    <script type="math/tex; mode=display">
        \alpha = \beta + \beta\\
        \alpha = 2\beta
    </script>

    <script>
        window.MathJax = {
            options: {
                renderActions: {
                    addMenu: [0, '', ''],
                    findScript: [10, doc => {
                        document.querySelectorAll('script[type^="math/tex"]').forEach(node => {
                            const display = !!node.type.match(/; *mode=display/);
                            const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
                            const text = document.createTextNode('');
                            node.parentNode.replaceChild(text, node);
                            math.start = { node: text, delim: '', n: 0 };
                            math.end = { node: text, delim: '', n: 0 };
                            doc.math.push(math);
                        });
                    }, '', false]
                }
            }
        };
    </script>
</body>

</html>
```

It gives me such result, no breakline produced
![image](https://user-images.githubusercontent.com/17429111/77538297-75699100-6eda-11ea-9385-d8f55cc21343.png)

### Technical details:

* MathJax Version: 3.0.1
* Client OS: Linux Mint 19.3
* Browser: Chromium 80.0.3987.87

**Comment by dpvc** [comment] 2020-03-25 12:59
This is a duplicate of issue #2312.  

Linebreaks are not yet implemented in version 3. This is one of the significant features from version 2 that been ported to version 3.

**Closed** 2020-03-26 02:47 UTC
Labels: Duplicate
