### ISSUE TITLE
Every rendered equation is followed by a vertical line on ubuntu/chrome

### ISSUE THREAD

**Issue by Strilanc** [mathjax/MathJax#1337] opened 2015-12-15 21:57 UTC
Although things look fine on my Windows machine with Firefox, MathJax appears to be appending a vertical pipe to everything when I view rendered equations in Chrome on Ubuntu.

Here's a highlighted screenshot of what I see from [a post on physicsforums.com](https://www.physicsforums.com/threads/are-photons-really-anti-correlated-off-their-basis-vectors.848175/):

![Highlighted errors](http://i.imgur.com/5efpq8O.png)

**Comment by dpvc** [comment] 2015-12-15 23:27
This is a duplicate of #1300, which is fixed in v2.6 (currently in the final stage of beta testing).

**Closed** 2015-12-15 23:27 UTC
Labels: Duplicate
