### ISSUE TITLE
[CommonHTML] AMScd error

### ISSUE THREAD

**Issue by netw0rkf10w** [mathjax/MathJax#1691] opened 2017-01-19 14:19 UTC
Hello,

In a previous version of MathJax (which I do not remember), the following AMScd diagram was rendered correctly: 
```
\begin{CD}
A @>a>b> B \\
@VlVrV @AlArA \\
C @<a<b< D
\end{CD}
```
but it is not the case in the current version.
Could you please check?
Thank you in advance.

**Comment by pkra** [comment] 2017-01-19 14:53
This works fine for me once you escape `<`  (or at least add spaces afterwards) to avoid browsers parsing the text as HTML tags.

**Comment by netw0rkf10w** [comment] 2017-01-19 15:08
@pkra I tried this in MathJax Live Demo and it failed:

$\require{AMScd}\begin{CD}
A @>a>b>  B \\
@VlVrV @AlArA \\
C @< a < b< D
\end{CD}$

An example of correctly rendering: http://www.hostmath.com/Show.aspx?Code=%5Crequire%7BAMScd%7D%5Cbegin%7BCD%7D%0AA%20%40%3Ea%3Eb%3E%20B%20%5C%5C%0A%40VlVrV%20%40AlArA%20%5C%5C%0AC%20%40%3Ca%3Cb%3C%20D%0A%5Cend%7BCD%7D

**Comment by dpvc** [comment] 2017-01-19 15:21
The error only occurs with CommonHTML output.  I'll have to look into it.

**Comment by pkra** [comment] 2017-01-19 16:03
> The error only occurs with CommonHTML output. 

Ah, I missed that -- sorry.

**Comment by dpvc** [comment] 2017-01-19 21:11
A more reduced test case is the following:

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable>
    <mtr>
      <mtd>
        <munder>
          <mo>&#x2192;</mo>
          <mi>b</mi>
        </munder>
      </mtd>
    </mtr>
  </mtable>
</math>
```

The issue is in the handling of the stretching of the arrow.

**Comment by dpvc** [comment] 2017-01-28 13:27
This is due to a problem with the CHTML `getNode()` function, which is used to locate the parts of an embellished operator (like the arrow in this case) when it is being stretched (as it is in the table cell).  The function descends the DOM tree looking for the proper node, but it fails to descend children properly when doing so (only looking through the *first* child.  The `getNode()` function has been a problem since the outset, and it should probably be replaced by an ID-based lookup instead.

**Comment by dpvc** [comment] 2017-07-07 15:05
The `issue1691` branch of my fork of MathJax fixes this issue.

**Comment by dpvc** [comment] 2017-07-11 11:12
==> Merged

**Comment by dpvc** [comment] 2017-07-14 18:39
==> In testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1691.html

**Closed** 2017-07-14 18:39 UTC
Labels: Accepted, Merged, Test Available
