### ISSUE TITLE
2.6-beta Safari 9 issues

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1283] opened 2015-10-09 09:02 UTC
Report from math.SE http://meta.math.stackexchange.com/a/21638/26910.

Seems like the CommonHTML output has some baselines issues and HTML-CSS some spacing issues.

I don't have access to Safari 9 right now.

**Comment by dpvc** [comment] 2015-10-09 09:55
I don't either.  It's possible that this is due to having the old MathJax fonts installed (though I doubt it because in that case the comparison image would show the MathJax fonts, not STIX fonts).  I would be interested in seeing if they have the same problem with Chrome or Firefox.

I am not able to reproduce, but I am using an earlier version of Safari (and OS).  There is a Safari bug that CHTML has to work around that is probably at the heart of this.  Not sure I'll be able to work out a better solution, since we are not using browser-specific output.

**Comment by pkra** [comment] 2015-10-09 10:52
Short update. I got my hands on iOS9 and saw the CommonHTML problem at least in part (can't see the other one since iOS doesn't come with STIX).

**Comment by dpvc** [comment] 2015-10-11 22:56
Some testing suggests that rounding the em's to the nearest pixel for the CSS that makes the tight character bounding boxes might do the trick.

**Comment by dpvc** [comment] 2015-10-11 22:58
The `issue1283` branch of my fork of MathJax includes the work-around.

**Comment by pkra** [comment] 2015-10-12 08:01
Awesome!

**Comment by dpvc** [comment] 2015-10-14 13:11
=> Merged

**Closed by dpvc** 2015-10-14 13:11 UTC
Labels: Accepted, Merged, Test Not Needed
