### ISSUE TITLE
Rendering bug in Edge and IE

### ISSUE THREAD

**Issue by fjwright** [mathjax/MathJax#2290] opened 2020-01-11 18:39 UTC
When I view https://www.mathjax.org/#samples in Microsoft Edge on Windows 10 the "Double angle formula for Cosines" example has a dashed square box containing the text f() overlaying each opening parenthesis and the following couple of characters; see below. If I use IE then the maths is not rendered at all. It all looks fine in Firefox and Chrome.

I initially noticed this problem on a web server that I manage. Everything is fine with an earlier version of MathJax, but when I experimented with the latest version I noticed this overlay bug in both Edge and IE (using the necessary polyfill).

![image](https://user-images.githubusercontent.com/59773998/72208963-462db100-34a1-11ea-8400-84028cbd1523.png)

**Comment by dpvc** [comment] 2020-01-11 20:51
This is a duplicate of mathjax/MathJax-src#385, and is resolved in PR mathjax/MathJax-src#397, but thanks for reporting the issue!

**Closed** 2020-02-19 14:18 UTC
Labels: Duplicate, Fixed, v3.0
