### ISSUE TITLE
SVG elements unresponsive to post-rendered CSS

### ISSUE THREAD

**Issue by isaacmast** [mathjax/MathJax#1516] opened 2016-06-08 16:30 UTC
From the attached screenshots, you can see that the enclose and cancel extensions aren't calculating the appropriate size for the SVGs. The encounered problems were the following: 
1. The circle option in the enclose extension would not encapsulate all of the text.
2. The strikethroughs in the cancel extension were improperly aligned and did not extend through all of the text. 

The problem can be recreated by applying CSS styles post-rendering of the SVG elements. By doing so, it appears that while the CSS is applied, the SVGs are unresponsive to the changes. 

An example of the problem has been reconstructed for your convenience and for additional testing. You can test the problem out at this link: http://jsfiddle.net/78bf6tk0/17/. 

![screen shot 2016-06-08 at 10 18 17 am](https://cloud.githubusercontent.com/assets/8737981/15897420/664ae862-2d62-11e6-94d7-fa2e3001ffb4.png)
![screen shot 2016-06-08 at 10 18 25 am](https://cloud.githubusercontent.com/assets/8737981/15897425/682e9dc2-2d62-11e6-8f0e-793f4b1f2ee2.png)

**Comment by maliknur** [comment] 2016-06-08 17:42
Your jsFiddle example has Math Render setting on CommonHTML, not SVG.
if you change it to SVG
`window.MathJax.Hub.setRenderer('SVG');` 
it scales properly as suppose to be.

**Comment by dpvc** [comment] 2016-06-08 17:46
The original complaint is about the CommonHTML output, not SVG output (CommonHTML uses SVG elements for a number the enclosures, such as the circles and diagonal lines).  The issue is that the dimensions in the SVG nodes are in pixels (which don't scale with `font-size` changes) rather than em's (which do).  It is probably possible to use em's instead.

**Comment by isaacmast** [comment] 2016-06-08 18:36
It also seems that using percentages works as well. 

![screen shot 2016-06-08 at 2 35 09 pm](https://cloud.githubusercontent.com/assets/8737981/15906328/53bfe084-2d86-11e6-8a6f-2e8ff713bb49.png)

**Comment by dpvc** [comment] 2022-03-11 12:40
In MathJax v3, the enclosures are not done using SVG, and scale properly.  So fixed in v3.

**Closed by dpvc** 2022-03-11 12:40 UTC
Labels: Accepted
