### ISSUE TITLE
Too different rendering on different browsers.

### ISSUE THREAD

**Issue by xrjunque** [mathjax/MathJax#3270] opened 2024-08-07 18:31 UTC
Rendering is always OK inside WebView2 control of .NET application, but not always showing properly in neither Edge nor Google Chrome browsers.

1. For example, the following MathML code inside a HTMl page:

``` js
<html>
<head>
</head>
<body>
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable displaystyle="true" columnalign="right left right left right left right left right left right left" columnspacing="0em 2em 0em 2em 0em 2em 0em 2em 0em 2em 0em" rowspacing="3pt">
    <mlabeledtr>
      <mtd id="mjx-eqn-eq:m">
        <mtext>(1)</mtext>
      </mtd>
      <mtd>
        <mi>M</mi>
      </mtd>
      <mtd>
        <mi></mi>
        <mo>=</mo>
        <mo stretchy="false">(</mo>
        <msub>
          <mi>M</mi>
          <mn>0</mn>
        </msub>
        <mo>+</mo>
        <msub>
          <mi>M</mi>
          <mn>1</mn>
        </msub>
        <mo>&#xD7;</mo>
        <mo stretchy="false">(</mo>
        <mi>J</mi>
        <mo>&#x2212;</mo>
        <msub>
          <mi>J</mi>
          <mrow>
            <mn>2000</mn>
          </mrow>
        </msub>
        <mo stretchy="false">)</mo>
        <mo stretchy="false">)</mo>
        <mo>mod</mo>
        <mn>360</mn>
        <mrow>
          <mo>&#xB0;</mo>
        </mrow>
      </mtd>
    </mlabeledtr>
    <mlabeledtr>
      <mtd id="mjx-eqn-2">
        <mtext>(2)</mtext>
      </mtd>
      <mtd>
        <msub>
          <mi>J</mi>
          <mrow>
            <mn>2000</mn>
          </mrow>
        </msub>
      </mtd>
      <mtd>
        <mi></mi>
        <mo>=</mo>
        <mn>2451545</mn>
      </mtd>
    </mlabeledtr>
  </mtable>
</math>
</body>
</html>
```

2. Inside Google Chrome and Edge, respectively, look like as:
![Chromw Captura de pantalla 2024-08-07 201623](https://github.com/user-attachments/assets/5d74db30-493e-47b5-8e36-1a2ade8321da)
![Edge Captura de pantalla 2024-08-07 201719](https://github.com/user-attachments/assets/371d4eb6-9512-4501-b372-9565ae6c6f03)

3. While, exactly the same MathML code rendering in a .NET application with WebView2 control shows right:
![Captura de pantalla 2024-08-07 200455](https://github.com/user-attachments/assets/5ce20a58-7b3a-4164-885a-0fdb28ef52f0)

I have seen more examples, some showing properly and others not. If necessary I can provide them.
There is no change in the rendering if added the following script to the HTML page

	<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'> </script>

**Comment by dpvc** [comment] 2024-08-07 21:30
The output you are showing for Chrome and Edge are not MathJax output, but rather the browser's native MathML rendering.  These two browsers implement the MathML Core specification, with is a limited version of MathML that does not include all the tags or attributes of MathML3, on which MathJax is based.  In particular, it doesn't include the `<mlabeledtr>`  that MathJax uses to handle the equation numbers, and that is the source of the bad rendering by those browsers.  If you change the `<mlabeledtr>` tags to `<mtr>` tags (and change the closing tags to match), you will get a better rendering in the native MathML renderers.  Alternatively, adding

``` html
<style>
mlabeledtr {
  display: table-row
}
</style>
```

to the document `<head>` would do the same thing.

Although this will help, the layout will still not be great, as the equation numbers will be in the wrong place, and the table cells will all be centered rather than properly aligned on the equal signs.  And you still won't be getting MathJax output, since there is no MathJax script in the HTML file you provide.

You mention adding the MathJax script to the file, and indicate that that doesn't change the output.  I am not able to reproduce that problem, as adding the script tag (from the bottom of your post) to the `<head>` of your document causes the results to be properly formatted by MathJax, as in your image in \#3 above.  So without an example file that actually includes MathJax, I can't tell you what you are doing wrong.  Do you have network access when you are trying this?

Finally, MathJax version 2.7.2 is very old.  The current version is 3.2.2, and version 4.0 is currently out in beta release.  The highest v2 is v2.7.9, so you should at least update to that, if you are not able to move to 3.2.2.

**Comment by xrjunque** [comment] 2024-08-08 06:45
Now I see it is the browser's native MathML rendering, thank you. But why, and how can I get MathJax's rendering? 
Please, find attached a zip file so you can reproduce the problem I am facing. 
[MathML_ToFrom_String.zip](https://github.com/user-attachments/files/16538761/MathML_ToFrom_String.zip)

There is internet connection because, for example, sample #22 does a call to MathJax's UpdateMath() to translate sample's 22 Latex code into MathML, for latter translating MathML to plain text. But you may see that samples #16 or #41 are not rendering MathJax's but browser's native.

**Comment by xrjunque** [comment] 2024-08-09 10:39
Thank you so much for your help and guidance. I've done as you told me (e.g. upgrade to v3) and now all the samples are working fine.
I just had to change:
<script>
function UpdateMath(TeX) {
return MathJax.tex2mml(TeX, {display: true});
};
</script>
to :
<script>
window.UpdateMath = function(TeX) {
return MathJax.tex2mml(TeX, {display: true});
};
</script>
Thanks again.

**Comment by dpvc** [comment] 2024-08-09 12:04
OK, great!  Glad you go it to work.

**Closed by dpvc** 2024-08-09 12:04 UTC
Labels: Expected Behavior, Upstream
