### ISSUE TITLE
Line on right hand side of equation.

### ISSUE THREAD

**Issue by DizzyZane** [mathjax/MathJax#1340] opened 2015-12-19 02:36 UTC
The line annoys me, and it occasionally interrupts the content.

My current solution to fix it is with CSS: `.MathJax>nobr>.math>:empty{border-left-color:transparent!important;}`

**Comment by dpvc** [comment] 2015-12-19 13:06
This is a duplicate of #1300, which is fixed in v2.6 (currently public beta).

**Closed by dpvc** 2015-12-19 13:06 UTC
Labels: Duplicate
