### ISSUE TITLE
MML3 Support in v3.x

### ISSUE THREAD

**Issue by edeustace** [mathjax/MathJax#2515] opened 2020-09-01 16:05 UTC
**Describe the solution you'd like**
I can see from #1753 that there were no immediate plans to complete support of MML3 in MathJax v2.7. I'm wondering if the plans have changed now that v3 is out?

**Comment by dpvc** [comment] 2020-09-03 18:13
It is on the long-term list of things to work on, but there are a number of features ahead of it.  

If someone wants to work on porting the version 2 extension for MML3 to Typescript for MathJax v3, that would be great.

**Comment by kevinhendricks** [comment] 2021-05-12 13:08
This really should be marked as a regression.  As support was present in 2.X but removed and never added back for 3.0+

**Comment by kevinhendricks** [comment] 2021-05-12 13:10
MML3 support is required as part of the epub3 mathml testsuite.  Without it, epub3 compliance can not be met.  That is why the Sigil project must stay with the 2.X releases.   Is anyone even looking at this?

**Comment by dpvc** [comment] 2021-05-15 20:55
@kevinhendricks:

> support was present in 2.X

It was present through an *experimental* extension (see the [documentation](https://docs.mathjax.org/en/v2.7-latest/options/extensions/MML3.html)).  This worked by using an XSLT transform to convert the original elementary MathML tags into other presentation tags that MathJax does support.  This does reasonably well for some situations, but considerably poorer for others.  So the elementary math support in v2 was spotty at best.

> Is anyone even looking at this?

I have made a version of the v2 XSLT-based MML3 extension, and will make a pull request for it, but the original poster was asking about "native" support (not the XSLT transform) for these tags in MathJax.  That is in our backlog of things to do, but is not at the top of the list.  Our priorities are driven largely by the needs of our sponsors, and elementary math support simply isn't something that they are asking for.  If Sigil wants this functionality, perhaps you would be interested in sponsoring its development.  Without that, we have to use our very limited resources in the places that make the most sense given the supporters that MathJax does have.

**Comment by kevinhendricks** [comment] 2021-05-15 21:30
Sorry, but Sigil is open source and totally free and we donate our developer time.  So we have no budget to sponsor anyone.  Just getting back to what was available in 2.5 would be enough.  Libxml supports xlst transforms and so does Chrome which QtWebEngine is derived from.

**Comment by dpvc** [comment] 2021-05-15 21:40
@kevinhendricks, yes, all modern browsers include the XSTLProcessor object, so that is not the problem.  As I mentioned, I have made a PR for the XSLT-based MML3 extension (see the PR link above your last comment).  The problem is that the XSLT transforms from elementary math to other tags is inadequate to handle the full elementary math specification, and is really just a hack to get "close to" the expected output.  It is just not good enough for serious authoring, and relying on it is probably not a good idea.

The real solution is to provide direct support in MathJax for these elements, which is what the OP had requested.  We would like to do that, but do not have the resources for it.  If someone wishes to contribute a PR to implement the elementary math tags, we would certainly be happy to see that, but it is not something we are working on ourselves at the moment.

**Comment by kevinhendricks** [comment] 2021-05-15 21:53
FYI, as I remember it was a MathJax developer who  wrote the mathml specification and test document for epub3 standard and he specifically included those test cases that required the MML3 extension!

**Comment by dpvc** [comment] 2021-05-15 22:29
@kevinhendricks:

> as I remember it was a MathJax developer who wrote the mathml specification and test document for epub3 standard and he specifically included those test cases that required the MML3 extension!

I'm pretty sure that's not correct.  The MathML specification was written before MathJax existed, and I think most of the writing was done by Neil Soifter while he was at Design Science, Inc.  The elementary math tests in the [MathML test suite](https://www.w3.org/Math/testsuite/build/main/overview.html) seem to have been written by Yecheng Gu (I don't know who that is), or by a generic "MathML3".

There have been only four MathJax developers (plus some contributors) since its inception, and while we did do some early work with EPUB and how to get MathJax to handle the MathML requirement, I don't believe any of us were involved in the actual specification.  One of the four didn't work out and was only with MathJax for a year; since then, he has been quite active with MathML, but that has not been in connection with MathJax.  I have not followed his career since he left the project (in 2013?), so he may have contributed to the test suite for MathML and EPUB.  I don't know.

I have not been able to locate an official test document or test suite for EPUB3 (though I admit that I didn't spend a lot of time looking), but I'm quite confident that MathJax was not involved.

**Comment by kevinhendricks** [comment] 2021-05-15 23:36
See pkra's reply to me on Jan 21, 2016 here:

https://github.com/pkra/MathJax-single-file/issues/3

Wasn't pkra mathjax dev?  Or did he just create the single-file version.

**Comment by kevinhendricks** [comment] 2021-05-16 00:02
Here is a link to the epub testsuite:

https://github.com/IDPF/epub-testsuite

**Comment by dpvc** [comment] 2021-05-16 12:01
I stand corrected.  I was not aware that Peter had contributed to the EPUB test suite.  

> Wasn't pkra mathjax dev?

He was the the MathJax project manager, which is more of an administrative position than a programming one, though he did make important contributions to tools like mathjax-node, the single-file version, versions with a slimmed-down footprint, the MathJax website, and the assistive support in MathJax.  And of course, he had considerable influence on the direct that MathJax took under his leadership.

I suspect, however, that his contribution to EPUB was made while wearing his hat as part of the AMS electronic publication team rather than as the MathJax project manager.

In any case, it doesn't change the fact that the elementary math support is not currently under development.

**Comment by kevinhendricks** [comment] 2021-05-16 12:52
Your PR once merged will be enough for us to move from the 2.x series to the 3.x series.

Thank you!

**Comment by pkra** [comment] 2021-05-16 14:46
> I suspect, however, that his contribution to EPUB was made while wearing his hat as part of the AMS electronic publication team rather than as the MathJax project manager.

No, it was part of keeping MathJax in Readium (and showing off how far ahead MathJax was / is of browser support, even though the xslt solution is of course a terribly bad solution in practically every way).

I'm disheartened to see that the toxic behavior of the recent comments "demanding" features is not rebuked but instead actively enabled.

**Comment by dpvc** [comment] 2021-05-16 15:12
> No, it was part of keeping MathJax in Readium (and showing off how far ahead MathJax was / is of browser support, even though the xslt solution is of course a terribly bad solution in practically every way).

OK, thanks for the clarification.

> I'm disheartened to see that the toxic behavior of the recent comments "demanding" features is not rebuked but instead actively enabled.

Yes, there have been a number of requests that have been on the rude side, as this one seemed to be.  On the other hand, we do want to port the missing features from v2 to v3, and when it is straightforward to do, as it was in this case, and took less than two hours (plus a little more to get the node version working), I'm willing to do it, despite rudeness.  They are, after all, useful features, often already available in v2, that may help others, and help to complete the v3 update.  

I'm not here to "rebuke" people.  I am here to make MathJax the best tool that I can.  A good feature, even if rudely requested, may still be worth pursuing.  I'm sorry this has disheartened you.  I have been trying to work on tempering my own visceral responses to various posts, which I hope you can appreciate.  I find that these posts, often hastily written, and sometimes by non-native English speakers, make it difficult to gauge the true emotional content behind them, and so have been trying to give people the benefit of the doubt, when possible, and to respond to them in as supportive a way as I can.  This has helped me to feel better about dealing with the large numbers of issues and forum posts that we receive.

**Comment by kevinhendricks** [comment] 2021-05-17 00:28
I apologize if my comments were perceived to be rude or demanding .  They were not meant to be.  They were meant to point out that this feature once existed in released and shipped 2x versions and has been missing for over 2 years now.  To me that made it a regression, and typically regressions are given a higher priority. 

I do appreciate the PR generated as it will finally allow Sigil to move to the Mathjax 3.x series was merged into a released version.  I simply do not see this as rude or demanding.  I see it as being a prompt/plea for help.   I started programming in the late 70s,  I guess I am too old to understand how younger devs think nowadays.  To me this was business as usual.  Again, if I stepped on toes, I apologize.

**Comment by dpvc** [comment] 2021-05-17 14:17
@kevinhendricks, thanks for your note.  That did help as did your "thank you" above (something not everyone does).

Your messages did rub me the wrong way.  I would not go so far as to say it was "toxic", as Peter indicates it was for him, but I did find it aggressive and somewhat entitled.  And it was not just Peter and me who felt that way.  Here's why:

First, your message was a comment on an earlier post that is asking not about the MML3 extension, but about moving from the experimental XSLT-based extension to true support for the elementary math tags in MathJax.  Your comment is about the MML extension from v2 being ported to v3, which is a different thing.  Your initial claim is that this is a regression, but that is incorrect, since the OP was about new native support for the elementary tags, something that never existed in v2, so not a regression.  And even if the OP were talking about the experimental support from v2, the mml3 extension is [documented](https://docs.mathjax.org/en/latest/upgrading/v2.html#v2-not-ported) as not yet ported to v3, so it is certainly something we know about, and I would not call that a regression, which I consider to be an *unexpected* reversion to a previous state.  We could debate whether that is the meaning or not, but that is how I see it.

Second, when you was "As support was present in 2.X but removed and never added back for 3.0+", it implies that the mml3 extension was removed from v2, and the "never" suggests that MathJax v3 is complete and that the mml3 extension has simply been left out.  Neither of those is true.  The mml3 extension was never removed from v2, and since it was never in v3, it wasn't removed from there either, but it is true that (until recently) it was not ported to v3 yet.  That is also true of a number of other v2 features as well.  We continue to work on moving the missing features from v2 to v3, and have been doing so since the initial release of v3.0.0.  Your comment seems to suggest that we simply ignoring the missing features, when, in reality, we are working as hard as we can to port these features, while still addressing the bugs that are always a part of a major rewrite, the questions raised by people about the new API, and the need for examples and illustrations of the new features in v3, as well as trying to support the ongoing needs of our sponsors and the MathJax community at large.  That work has to be prioritized, and additional mml3 support is not the highest priority task, as there are other more critical features from v2 that are also in need of being ported (like line-breaking support, support for additional fonts, missing TeX extensions, etc.).  

Third, your comment "Is anyone even looking at this?" reads as aggressive, especially in a second message before anyone could even respond to the first,.  It is not clear if you meant looking at the mml3 support that the OP was asking for, or your previous comment; but even if the former, the phrasing is off-putting.  Asking whether there is a timeline for full MathML3 support, for example, might have elicited a better response.

Fourth, your comment "Just getting back to what was available in MathJax 2.5 would be enough. Libxml supports xlst transforms and so does Chrome which QtWebEngine is derived from" suggests that you have not actually fully read my previous comment, where I said that I was making a PR for the XSLT-based mml3 extension.  There was not acknowledgement that that was occurring; "getting back to what was available in MathJax 2.5 would be enough" seems to be a request for that to happen, even though I already said that was being done (the PR was linked right above your comment), and suggesting tools for XSLT transforms suggest that you didn't believe that I already had it working for the PR and needed ideas for how to accomplish it.  I'm afraid that that came off to me as pretentious and not attentive to the replies I was making.

Fifth, the comment "FYI, as I remember it was a MathJax developer who wrote the mathml specification and test document for epub3 standard and he specifically included those test cases that required the MML3 extension!" also seems aggressive, as though you were providing a "gotcha" moment, catching MathJax in some kind of hypocrisy (the "FYI" make sit seem that way even more so).  Even if true, pointing that out doesn't seem like an effective way to encourage someone to provide a new feature that you are looking for.

Finally, to was several messages later when you finally acknowledge d the fact that I had already made the pull request that ported the v2 mml3 extension to v3 (which occurred directly after my first response to you, some seven or eight messages earlier).  

Those are the things that we were reacting too.  Of course, as I mentioned to Peter, it is difficult to tell the true intent of someone from this kind of written comment (and I know they my own writing has sometimes been taken the wrong way, as well).  That is why I trey to give people the benefit of the doubt, rather than rebuke them.  I appreciate your apology and explanation, as that helps to resolve the situation for me.  I hope my comments here help you to understand why we reacted as we did.

> I started programming in the late 70s, I guess I am too old to understand how younger devs think nowadays.

I also stared programming in the 70's, so I'm not sure I'd categorize myself as a "younger dev".  :-)

Thanks again for your response.  I think we can put this to bed at this point.

**Closed** 2021-07-06 21:29 UTC
Labels: Feature Request, Fixed, v3, v3.2
