### ISSUE TITLE
Vertical misalignment of pmatrix in v3

### ISSUE THREAD

**Issue by Milania1** [mathjax/MathJax#2203] opened 2019-09-17 20:08 UTC
Glad to see that version 3 was released, thanks for the hard work!

I noticed that there is a vertical misalignment when using `pmatrix` in version 3.0.
Input (tested [here](https://mathjax.github.io/MathJax-demos-web/input-tex2chtml.html))
```LaTeX
C_m(A) = \begin{pmatrix} 4 & 6 & 3 & 6 & 4 & 3 \end{pmatrix}
```
Output:
![grafik](https://user-images.githubusercontent.com/11442755/65075453-3ab8f600-d997-11e9-9d6f-f0ee2fcb2d11.png)

This problem did not exist in v2.

**Comment by dpvc** [comment] 2019-09-21 12:44
Can you tell me the browser and version number, and the OS you are using?  I am not able to reproduce the result (I can get about a 1 pixel shift, but not the extensive shift you are seeing.

**Comment by Milania1** [comment] 2019-09-21 12:57
I see this shift on Windows x64 1903 both in Firefox (69.0.1) and Chrome (77.0.3865.75).

I also just tested it on Safari (iOS 12.4.1) and then I only see a small shift of about 1 px as you. Maybe it is OS related?

**Comment by dpvc** [comment] 2019-09-21 13:03
> Maybe it is OS related?

It does seem to be.  I'll have to look into it.  Thanks for the additional information.

**Comment by dpvc** [comment] 2019-09-22 13:08
OK, I cn reproduce it.  It turns out that `vertical-align: middle` didn't work quite as I thought.  There is an extra .5ex upward shift, and it seems that the font metrics are handled differently on Windows from how they are where I do my testing.

I should be able to compensate for that, and will make a PR for it.

**Comment by dpvc** [comment] 2019-09-22 14:02
I've made the PR to fix this.

**Comment by dpvc** [comment] 2019-09-22 14:02
I'm closing this as a duplicate of #2186, since it is the same cause.

**Closed by dpvc** 2019-09-22 14:02 UTC
Labels: Duplicate
