### ISSUE TITLE
Improper rendering with nested roots

### ISSUE THREAD

**Issue by zopyx** [mathjax/MathJax#1364] opened 2016-01-30 15:57 UTC
See test #13

https://print-css.rocks/_static/lesson-mathml-torture-test/vivliostyle-output.pdf

Source is here

https://github.com/zopyx/css-paged-media-tutorial/tree/master/lesson-mathml-torture-test

**Comment by dpvc** [comment] 2016-01-30 16:18
I can not reproduce your result.  The output is fine for me in all output modes for my own test page.  The example page you point to doesn't include the MathJax configuration that Vivliostyle uses, so I don't know how MathJax is configured.  Do you have automatic line breaks turned on?  It looks like your result may be do to line-breaing within the roots that would have caused the table to be too wide.

**Comment by pkra** [comment] 2016-02-05 10:00
Thanks for following up downstream, @kwkbtr. Let us know if we can help with anything.

**Comment by kwkbtr** [comment] 2016-02-05 10:03
Currently Vivliostyle always enables the automatic line breaks.
The configuration is here:
https://github.com/vivliostyle/vivliostyle.js/blob/2016.1/resources/mathjax-config.js#L12

I confirmed that the math is rendered correctly when the automatic line breaks is turned off.

I filed an issue to Vivliostyle (vivliostyle/vivliostyle.js#167), but I'm not sure if this problem is specific to Vivliostyle. Even without Vivliostyle, the same problem occurs when width of the table column *before* typesetting is narrower than width required for the typeset math to fit inside the column.

**Comment by kwkbtr** [comment] 2016-02-05 10:06
> Even without Vivliostyle, the same problem occurs when width of the table column before typesetting is narrower than width required for the typeset math to fit inside the column.

You can see this by removing table rows except the row "13" from the sample (and turning on the automatic line breaks).

**Comment by pkra** [comment] 2016-02-05 10:22
Thanks @kwkbtr Is there any chance somebody could create a minimal sample, e.g., on codepen, jsbin?

**Comment by kwkbtr** [comment] 2016-02-05 10:29
> Is there any chance somebody could create a minimal sample, e.g., on codepen, jsbin?

Created one: http://jsbin.com/vojimahuno/edit?html,output

**Comment by pkra** [comment] 2016-02-05 12:00
Great! Thanks, @kwkbtr.

**Comment by dpvc** [comment] 2016-05-04 23:53
There are several issues going on, here.  The first is that line breaking can occur inside a square root, and that is what is happening here, because MathJax things the line width is small (more on this below).  The result is pretty ugly, but there isn't much voice about how this equation can be broken.  Perhaps it would help to left-jutify rather than center the parts, or indent the second line, but I'm note sure.  In any case, that part is "expected behavior" for line breaking this expression.

The reason MathJax thinks the equation must be broken is because of the table.  MathJax tries to measure the width of the container for the math and use that as the line-breaking width.  But that only works when the container *has* a width, and for elements that shrink-wrap their contents, like `<td>` elements, if there is no over content, the width is zero.

The CommonHTML jax has logic that is supposed to look at elements higher in the hierarchy in that case, but it turns out that it was failing.  The reason for the failure is the preview that is shown before the math is typeset.  That was forcing the `<td>` to have non-zero width, and so the container width was determined to be the width of the preview (slightly smaller than the final equation, which is why the first two square roots are broken, but the others aren't).

The `issue1364` branch of my fork of MathJax includes a fix that ignores the width of the preview (in CommonHTML, HTML-CSS, and SVG output, all of which were affected by this issue).

**Comment by dpvc** [comment] 2016-06-24 00:44
Since another (merged) branch changed the way that CHTML determines the container width, I've refactored the `issue1364` branch to only include the issue concerning the previews (thus avoiding merge conflicts with the previous version of the branch).

**Comment by dpvc** [comment] 2016-07-08 13:13
==> Merged

**Closed** 2016-07-08 13:13 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-18 14:49
==> In testsuite

MathMLToDisplay/issue1364.html
