### ISSUE TITLE
[Math Processing Error] when replacing msub by msup in an expression with nested mmultiscripts

### ISSUE THREAD

**Issue by michel2bec** [mathjax/MathJax#1480] opened 2016-05-18 14:13 UTC
Hi, here a surprising result I just encountered today :
The only difference between (A) and (C) is I replaced msub by msup, the difference between (B) and (C) seems to be the mrow.

**(A) This works:**
```
<math>
	<mmultiscripts>
		<mmultiscripts>
			<mi>A</mi>
			<mi>B</mi>
			<mprescripts />
			<none />
			<mi>D</mi>
		</mmultiscripts>
		<mrow>
			<mo>(</mo>
			<msub>
				<mi>g</mi>
				<mi>h</mi>
			</msub>
			<mo>)</mo>
		</mrow>
		<mprescripts />
		<none />
		<mi>i</mi>
	</mmultiscripts>
</math>
```

**(B) This works :**
```
<math>
	<mmultiscripts>
		<mmultiscripts>
			<mi>A</mi>
			<mi>B</mi>
			<mprescripts />
			<none />
			<mi>D</mi>
		</mmultiscripts>
		<msup>
			<mi>g</mi>
			<mi>h</mi>
		</msup>
		<mprescripts />
		<none />
		<mi>i</mi>
	</mmultiscripts>
</math>
```

**(C) This yields [Math Processing Error] :**

```
<math>
	<mmultiscripts>
		<mmultiscripts>
			<mi>A</mi>
			<mi>B</mi>
			<mprescripts />
			<none />
			<mi>D</mi>
		</mmultiscripts>
		<mrow>
			<mo>(</mo>
			<msup>
				<mi>g</mi>
				<mi>h</mi>
			</msup>
			<mo>)</mo>
		</mrow>
		<mprescripts />
		<none />
		<mi>i</mi>
	</mmultiscripts>
</math>
```

**Comment by michel2bec** [comment] 2016-05-18 14:15
I checked it today on the MathJax Live Demo.

**Comment by pkra** [comment] 2016-05-18 15:49
Thanks for the report. This looks like a problem with the live demo rather than MathJax. The MathML renders for me on its own, e.g., using http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html.

**Comment by pkra** [comment] 2016-05-18 15:50
Closing in favor of https://github.com/mathjax/MathJax-website/issues/57

**Comment by dpvc** [comment] 2016-05-18 16:01
I believe the issue is in MathJax, in the CommonHTML output (not HTML-CSS which is the default for the sample-dynamic-2 page that you cite).  I can reproduce it locally.

**Comment by dpvc** [comment] 2016-05-18 16:25
This is a reduced test case:

```
<math>
    <mmultiscripts>
        <mi>A</mi>
        <mrow>
            <mo>(</mo>
            <msup>
                <mi>g</mi>
                <mi>h</mi>
            </msup>
            <mo>)</mo>
        </mrow>
    </mmultiscripts>
</math>
```

**Comment by dpvc** [comment] 2016-05-18 16:32
The problem is that the boxes used for the scripts and prescripts are being constructed outside the DOM and then added in.  This means their contents are not in the DOM while they are being constructed, and that means that stretchy characters (the parentheses in this case) can't locate their DOM nodes using `document.getElementById()`, and that causes the stretching code to fail.

The `issue1480` branch of my fork of MathJax resolves the issue.

**Comment by pkra** [comment] 2016-05-18 19:43
> I believe the issue is in MathJax, in the CommonHTML output (not HTML-CSS which is the default for the sample-dynamic-2 page that you cite). I can reproduce it locally.

Thanks for correcting me!

**Comment by dpvc** [comment] 2016-06-08 10:45
==> Merged.

**Closed** 2016-06-08 10:45 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-09 20:21
==> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/mmultiscripts/issue1480.html
