### ISSUE TITLE
[SVG] vphantom produces too much width

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1637] opened 2016-10-13 08:19 UTC
E.g., `$a\vphantom {pretend something is here}b$` produces a wide output in SVG output (whereas HTML/CSS and CommonHTML output will not).

**Comment by dpvc** [comment] 2016-10-13 10:46
I can't reproduce your result.  The example works as expected in all three output renderers for me in Firefox and Chrome on Mac OS X.  What browser and OS are you using?

**Comment by pkra** [comment] 2016-10-13 14:48
I ran into this on mathjax-node; I do see it on Chrome as well. The output on http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html is ~190px for SVG but ~18px on HTML.

To clarify: the "space" is after the `b` (or "overlapping" it I suppose).

**Comment by dpvc** [comment] 2016-10-17 01:45
OK, I think I understand what you are seeing.  The problem is that the bounding box information for the expression is built up as the expression is generated, so the size of the phantom text is incorporated into the box before the phantom action occurs, and that size is maintained, so the SVG output thinks the output is wider than the final expression's visible extent.  The `<svg>` element is supposed to get a right margin that should compensate for that extra width, but that doesn't seem to be making it through to the output in MathJax-node (but does in the browser, which is why I wasn't seeing it).

I'll look into possible solutions.

**Comment by dpvc** [comment] 2016-10-17 02:05
Sorry, thought this was a mathjax-node complaint, but I see it is for MathJax itself.

**Comment by dpvc** [comment] 2016-10-17 02:12
PS, the problem with the missing `right-margin` is resolved in [this patch](https://github.com/mathjax/MathJax-node/commit/bd1d6c430dbd45d5e6db8e496bfc03619e411169) of mathjax-node, so if you actually *are* using MathJax-node, and you are using the `develop` branch, then you should be getting the `right-margin` that compensates for the extra width.

**Comment by dpvc** [comment] 2016-10-17 02:16
The difficulty is that the `\vphantom` produces

    <mpadded width="0">
      <mphantom>
         ...
      </mphantom>
    </mpadded>

The `<mphantom>` should have the full width of its content, as it does here, and the `<mpadded>` should keep track of the overflow, since it doesn't know that the content isn't being displayed, and if it *were* displayed (as in the output of `\rlap{}` for example), you *would* want the overflow to be part of the final svg (with `right-margin` to compensate).

Fixing this would require maintaining yet another value in the bounding box data (already a source of some performance issues) that would provide an "ignorable width" so that mpadded nodes could use to clip the results when their contents are hidden and the width is specified.  Note, however, that overflow an occur on all four sides (top, bottom, and left, as well as right), so to do it right, clipping values for all four would be needed, adding more overhead, though the right-hand clipping would be the most important case.

Is the `right-margin` compensation not sufficient?

**Comment by pkra** [comment] 2016-10-17 07:45
> The problem is that the bounding box information for the expression is built up as the expression is generated, so the size of the phantom text is incorporated into the box before the phantom action occurs, and that size is maintained, so the SVG output thinks the output is wider than the final expression's visible extent. 

Thanks for the background.

> Sorry, thought this was a mathjax-node complaint, but I see it is for MathJax itself.

Apologies for not being clearer myself. I first saw it on mathjax-node and then checked MathJax itself and saw it there, too.

> if you actually are using MathJax-node, and you are using the develop branch, then you should be getting the right-margin that compensates for the extra width.

Hm. I am using mathjax-node#develop and see the problem there. I'll investigate and file a bug downstream.

> Fixing this would require maintaining yet another value in the bounding box data (already a source of some performance issues) that would provide an "ignorable width" so that mpadded nodes could use to clip the results when their contents are hidden and the width is specified. Note, however, that overflow an occur on all four sides (top, bottom, and left, as well as right), so to do it right, clipping values for all four would be needed, adding more overhead, though the right-hand clipping would be the most important case.
> 
> Is the right-margin compensation not sufficient?

Thanks for the assessment. I don't have an opinion at this time. Let's discuss this F2F perhaps.

**Comment by dpvc** [comment] 2020-02-21 15:52
In testsuite:

MathMLToDisplay/issue1637.html

**Closed** 2020-04-10 16:11 UTC
Labels: Accepted, Merged, Test Available, v2
