### ISSUE TITLE
MathML matrix renders poorly

### ISSUE THREAD

**Issue by ktullavik** [mathjax/MathJax#2269] opened 2019-12-18 03:07 UTC
Looking at upgrading to mathjax 3, I have trouble getting matrices to render nicely.

MathJax3
![mathjax3_matrix](https://user-images.githubusercontent.com/12862451/71051895-f4b42f80-2149-11ea-901d-904b1ad54b78.PNG)

MathJax2 + Stix font
![mathjax2_matrix](https://user-images.githubusercontent.com/12862451/71051878-e8c86d80-2149-11ea-9cc1-f7e9a1d3b2fc.PNG)

```mathml       
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
    <mrow>  
        <mo>[</mo>
        <mtable>  
            <mtr>
                <mtd>
                    <mn>1</mn>
                </mtd>
                <mtd>
                    <mn>2</mn>
                </mtd>
            </mtr>
            <mtr>
                <mtd>
                    <mn>3</mn>
                </mtd>
                <mtd>
                    <mn>4</mn>
                </mtd>
            </mtr>
        </mtable>
        <mo>]</mo>
    </mrow>  
</math>
```

**Comment by dpvc** [comment] 2019-12-18 15:04
This is a duplicate of #2186, which is fixed in the pull request mathjax/MathJax-src#352.

**Closed** 2019-12-30 13:44 UTC
Labels: Duplicate
