### ISSUE TITLE
Top of Non-English Characters are clipped

### ISSUE THREAD

**Issue by thinkman** [mathjax/MathJax#168] opened 2011-09-05 17:07 UTC
When I use latex 

"\[\frac{พื้นที่\Delta ABC}{พื้นที่\Delta DEF}\]" or
 
"\[\frac{\text{พื้นที่}\Delta ABC}{\text{พื้นที่}\Delta DEF}\]" in jsMath, 

jsMath displays result as I expect.

But when I try to use Mathjax, Top of Non-English characters are clipped as screenshot below

http://www.mathcenter.net/temp/MathjaxBug01.png
http://www.mathcenter.net/temp/MathjaxBug02.png

**Comment by pkra** [comment] 2015-03-04 19:48
Closing this as a duplicate of #474 (even though it should be the other way around, I suppose, but that's where we made progresso n this.) and expected behavior (clipping of unknown characters).

**Closed by pkra** 2015-03-04 19:48 UTC
Labels: Duplicate, Expected Behavior
