### ISSUE TITLE
(v3) Cannot load amsCd (wrong casing in filename on CDN?)

### ISSUE THREAD

**Issue by nasosev** [mathjax/MathJax#2209] opened 2019-10-04 06:50 UTC
After updating to v3 I can't load amsCd anymore.
In the console output of my browser I get the error:
`Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/tex/extensions/amsCd.js”`

The filename on the server is `https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/tex/extensions/amsCd.js` does not appear to exist, however `amscd.js` does (`c` is not capitalised`).

I tried changing the config in my HTML to 
```    
<script>
      MathJax = {
        loader: { load: ["[tex]/amscd"] },
        tex: { packages: { "[+]": ["amscd"] } }
      };
</script>
```
but it didn't help.

**Comment by dpvc** [comment] 2019-10-04 09:50
This is a duplicate of mathjax/MathJax-src#335, for which is fixed in the next release.

**Closed** 2019-10-19 19:56 UTC
Labels: Duplicate

**Comment by nasosev** [comment] 2019-12-16 02:02
> 
> 
> This is a duplicate of [mathjax/MathJax-src#335](https://github.com/mathjax/MathJax-src/issues/335), for which is fixed in the next release.

Is there an ETA on the next release? It's been a couple of months now and the problem persists. Thanks.

**Comment by dpvc** [comment] 2019-12-17 21:21
@nasosev, I expect it to be in early January.

In the meantime, you can use

```
MathJax = {
  loader: {
    source: {
      '[tex]/amsCd': '[tex]/amscd'
    }
  }
};
```

to your configuration should allow you to load `amsCd` for now.  You will need to remove this once the file is properly named, however.

**Comment by nasosev** [comment] 2019-12-18 00:38
Thanks!
