### ISSUE TITLE
MathJax 2.7.5 fails to render number with tilda (~) character on Chrome v78

### ISSUE THREAD

**Issue by MrDarkHorse** [mathjax/MathJax#2228] opened 2019-10-29 16:18 UTC
**Note:  This issue was introduced with Chrome v78.  On Chrome v77, it works just fine.**

Using the following markdown:
```
No number shown (with tilda):
$$ 7.72\times{10}^{4}~\text{g} $$ 

Number shown (without tilda):
$$ 7.72\times{10}^{4}\text{g}  $$
```

On render, here's what I'm getting:
![Screen Shot 2019-10-29 at 11 13 28 AM](https://user-images.githubusercontent.com/9271182/67787033-d9784e00-fa3d-11e9-85b7-a1ae932cc678.png)

**Comment by dlsun** [comment] 2019-10-29 16:22
This is potentially related to my issue, which is also a problem with Mathjax 2.7 equations displaying in Chrome: #2227

**Comment by MrDarkHorse** [comment] 2019-10-29 16:31
> This is potentially related to my issue, which is also a problem with Mathjax 2.7 equations displaying in Chrome: #2227

Yup.  I'm seeing the same thing that you're seeing.

**Comment by dpvc** [comment] 2019-10-29 16:50
This is a duplicate of #2227, as you suspected.

**Closed** 2019-12-30 13:46 UTC
Labels: Duplicate

**Comment by dlsun** [comment] 2020-02-09 23:52
> On the other hand, the reason the breaking occurs is because MathJax has incorrectly set the width of a container element (it didn't take the scaling factor into account), so there is a MathJax bug as well.

Although Chrome fixed their bug, resolving the immediate issue, was this MathJax bug ever fixed?

**Comment by dpvc** [comment] 2020-02-10 15:08
> was this MathJax bug ever fixed?

There has not been a bug-fix release since the error was reported (versions 2.7.6 and 2.7.7 were to fix specific issues with the CDN and the npm package, not general bugs in MathJax).  A v2.7 release is one of the next steps for us, as there are a number of pull requests that are waiting to be merged.

On the other hand, the width issue is not present in v3, so in that sense, it is fixed.
