### ISSUE TITLE
Using HTML-CSS renderer, hlines and column separators are not always displayed

### ISSUE THREAD

**Issue by yrral86** [mathjax/MathJax#1095] opened 2015-03-15 04:17 UTC
Consider the following example LaTeX:
```
\begin{array}{|c|c|}
\hline \textbf{X}&\textbf{Y}\\
\hline 9&3\\
\hline 18&x\\
\hline 27&9\\
\hline 36&12\\
\hline 
\end{array}
```

While this renders just fine with the SVG renderer, using the HTML-CSS renderer is hit or miss.  The horizontal and vertical lines do not always appear.  In general, decreasing the zoom level of the browser makes more lines disappear, and zooming in makes more lines appear until at a certain level of zoom it finally renders properly.

100%:
![screenshot from 2015-03-15 00 14 00](https://cloud.githubusercontent.com/assets/40162/6654651/563192d2-caa8-11e4-86c5-bc28450c62aa.png)

90%:
![screenshot from 2015-03-15 00 14 11](https://cloud.githubusercontent.com/assets/40162/6654650/56310b64-caa8-11e4-952f-11abf0f6c220.png)

67%:
![screenshot from 2015-03-15 00 14 18](https://cloud.githubusercontent.com/assets/40162/6654652/5631eda4-caa8-11e4-887c-ba560c824651.png)

50%:
![screenshot from 2015-03-15 00 14 24](https://cloud.githubusercontent.com/assets/40162/6654653/563243e4-caa8-11e4-8cc9-22519a4864bb.png)

Of course, we can use SVG when it is available, but we need to support older versions of IE that do not have support for SVG.  This bug also appears [here](http://jsfiddle.net/AqDCA/522/) if you zoom out, so it seems it is not a problem with our particular environment.

Any help tracking this down would be greatly appreciated.

**Comment by yrral86** [comment] 2015-03-15 04:30
BTW, this is Mathjax 2.5.1, on Linux, OSX, and Windows, using at least chrome and firefox.

**Comment by pkra** [comment] 2015-03-16 07:35
Thanks for the report. We'll take a look.

**Comment by enismehmet** [comment] 2015-03-18 18:30
Hi, Has there been any developments with this issue?

**Comment by shuminheng** [comment] 2015-04-20 02:14
Hi @pkra,

Just chiming in to mention that I'm seeing this in one of my projects too. Here's a bit of LaTeX that is not _consistently_ rendering its horizontal or vertical lines for me:

    \( \begin{array} {r|l}
    \text{Stem} &amp; \text{Leaf}
    \\ \hline 6_L &amp; 1\;1\;2\;4
    \\ 6_H &amp; 6\;8\;9\;9\end{array} \)

Essentially:

* Tested on Windows 7
* IE11 and Firefox (37.0.1) display the lines perfectly at 100% zoom, and also at two zoom levels above and below 100% (I didn't test any further).
* Chrome (42.0.2311.90 m) displays the lines at 100% zoom **in some page environments**, and as such I unfortunately haven't been able to create a shareable example of it not working... you'll just have to trust me that it the lines don't show up all the time! Zooming in and out when the lines don't appear will tend to pop them in and out.

So far in my limited testing, it seems to be a fragile positioning / rounding issue in Chrome, but I need someone who actually knows the intricacies of MathJax to confirm :) Please let us know if you need any more info to help figure out what's going on. Thanks!

**Comment by dpvc** [comment] 2015-04-21 12:10
MathJax does all a its internal measurements in em's (to make them independent of the font size), and that includes the sizes of rule lines.  MathJax does try hard to make sure that the rules are at least a pixel thick, but not all browsers handle the situation the same.  You are correct that it is very closely tied to rounding and the pixel grid, and that zooming definitely does affect it.  I have not seen problems at 100% (except for very small initial font sizes), but it certainly does happen at other zoom levels.

I've done some experiments, and it looks like if the sizes are given in pixels, Firefox, Chrome, and Safari (haven't tried IE) are less likely to drop the lines.  So I will see about using units of `px` for vertical and horizontal lines.  The issue isn't currently in any milestone, so I'm not sure what version that will make it into.

**Comment by pkra** [comment] 2015-04-21 16:30
=> added to backlog

**Comment by shuminheng** [comment] 2015-04-23 03:43
Thanks @dpvc!

If it helps, I've noticed that tweaking the _position_ helps as well. For example, I have a vertical line that isn't displaying at 100% in Chrome. It has a 0px width and a 1px left border. Its left position is set to 3.077em. If I round this up to 3.09em in the inspector, the line becomes visible.

**Comment by dpvc** [comment] 2015-04-23 11:34
Yes, the position makes a difference as well.  I've seen situations where when you *scroll* the page, the lines appear and disappear (or change width).  So it depends not only on the position within the document, but also the scroll position.  That means that adjusting the position probably won't help (since that can change as you scroll).  But it is a good thought, none the less.

**Comment by dpvc** [comment] 2015-08-04 13:29
OK, it looks like switching to `px` rather than `em` for the thickness of the rules and also using `border-top` for the horizontal ones rather than `border-left` does the trick.  This is available in the `issue1095` branch of my fork of MathJax.

**Comment by dpvc** [comment] 2015-08-05 19:09
=> Merged.

**Closed** 2015-08-05 19:09 UTC
Labels: Accepted, Merged, Test Not Needed
