### ISSUE TITLE
verb does not respect white space

### ISSUE THREAD

**Issue by pzinn** [mathjax/MathJax#1953] opened 2018-03-20 14:27 UTC
I know this issue has been raised several times in the past, but unless I'm mistaken, I don't think it has been fixed properly.
try
```
$$\verb|a    b|$$
$$\verb|a1234b|$$
```
where there are 4 spaces between a & b; the width won't be the same after rendering.

**Comment by dpvc** [comment] 2018-03-21 14:44
The issue is that the spaces being used are not the correct width.  The space in the MathJax TeX Typewriter font was accidentally set to the wrong width when it was created, and although we added some patches to the processing to compensate for it, they were only for the actual space character, not the non-breaking space that is used in this situation.

Similar patches can be added to handle the non-breaking space. I have made a pull request to do that (you can see it above).  For now, you can add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/CommonHTML/fonts/TeX/Typewriter-Regular.js",function () {
  var FONTS = MathJax.OutputJax.CommonHTML.FONTDATA.FONTS;
  FONTS['MathJax_Typewriter'][0xA0][2] += 275;
  FONTS['MathJax_Typewriter'][0xA0][5] = {rfix:275};
});
MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/HTML-CSS/fonts/TeX/Typewriter/Regular/Other.js",function () {
  var FONTS = MathJax.OutputJax["HTML-CSS"].FONTDATA.FONTS;
  FONTS['MathJax_Typewriter'][0xA0][2] += 275;
  FONTS['MathJax_Typewriter'][0xA0][5] = {rfix:275};
});
MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/HTML-CSS/fonts/STIX/fontdata.js",function () {
  var MONOSPACE = MathJax.OutputJax["HTML-CSS"].FONTDATA.VARIANT.monospace;
  MONOSPACE.remap[0xA0] = [0xA0, "-STIX-variant"];
});
MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/HTML-CSS/fonts/STIX/Variants/Regular/All.js",function () {
  var FONTS = MathJax.OutputJax["HTML-CSS"].FONTDATA.FONTS;
  FONTS['STIXVariants'][0xA0][2] += 275;
  FONTS['STIXVariants'][0xA0][5] = {rfix:275};
});
</script>
```

to your page just *before* the script that loads MathJax.js itself in order to work around the problem.  You will need to remove the patch after the issue is fixed (in the next release).

**Comment by pzinn** [comment] 2018-03-22 13:10
Thanks for your reply. Incidentally, I've found another problem with \verb: it doesn't correctly deactivate the closing symbols, say $ or \) or $$ depending on what the opening symbol was.
i.e.
```
\( \verb|\)| \)
```
compiles fine with LaTeX but fails in mathJax. should I open a new issue?

**Comment by dpvc** [comment] 2018-03-22 13:31
No, this is a known limitation (see #375), and not something that we are likely to fix.  It has to do with the fact that MathJax locates the entire expression before parsing it (e.g., finds the `\(` and the following `\)` before parsing the math), so doesn't know that the first `\)` is inside `\verb` and should be ignored.  TeX, on the other hand, parses the math while it is looking for the close delimiter, and so can detect that the first one is not the actual close delimiter.

There are similar problems with things like `\verb|}|` which can cause the brace-matching to fail when looking for the closing delimiter.

Fixing this would require MathJax to operate substantially differently, and the use case is not one we plan to support.  You can use `\texttt{\)}` to get the output you want from `\verb|\)|`, and `\texttt{\}}` for `\verb|}|`.

**Comment by pzinn** [comment] 2018-03-22 13:34
yeah the workaround is easy enough, I was just wondering.

**Comment by dpvc** [comment] 2018-03-30 14:27
==> Merged.

**Closed by dpvc** 2018-03-30 14:27 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2018-03-30 17:26
==> In testsuite
MathMLToDisplay/Topics/WhiteSpace/issue1953.html
