### ISSUE TITLE
Why do horizontal line segments render poorly in Chrome under HTML-CSS?

### ISSUE THREAD

**Issue by mehrdadn** [mathjax/MathJax#1681] opened 2016-12-27 07:38 UTC
The image speaks for itself -- just try something simple like `f(z+1) = f(z)`: [link](http://imgur.com/Jpi6wW1)
Notice the cross on the "f" almost doesn't exist in Chrome? This general problem has existed for eons, both when Chrome used GDI, and now that it uses Direct2D; it's not a new thing. It doesn't really seem to occur on Firefox, and it makes the rendering on Chrome quite difficult to read. I've searched online, and I've been surprised that no one seems to have mentioned it... maybe I wasn't searching correctly? Anyway, I was wondering what the issue is, and if it might be fixed? Thank you!

**Comment by pkra** [comment] 2016-12-29 14:33
Can you post a live sample? I have not noticed the issue before. If this happens only on small font-sizes, it might be a browser bug.

**Comment by mehrdadn** [comment] 2016-12-29 21:30
Sure, [here's](http://math.stackexchange.com/revisions/757330/4) a random example from Math.StackExchange, and [here](http://imgur.com/a/8zTMz) is the rendering. (By the way, the small integral sign is also an issue. Any chance that could be fixed as well?)
If it renders differently on your machine, may I ask what it looks like?
Thanks you!

**Comment by TomasRiker** [comment] 2017-01-03 11:23
I too cannot reproduce this. This is how it look on my Chrome 55.0.2883.87 m:

![rendering](https://cloud.githubusercontent.com/assets/295205/21606393/79e206de-d1af-11e6-9213-08639919fcf6.png)

**Comment by mehrdadn** [comment] 2017-01-03 11:25
Strange, I'll have to try another computer. Just checking, are you actually on Windows?

**Comment by TomasRiker** [comment] 2017-01-03 11:25
Yes, it's Windows 10.

**Comment by mehrdadn** [comment] 2017-01-03 11:25
Okay thank you, let me see if I can reproduce it on another computer.

**Comment by mehrdadn** [comment] 2017-01-03 11:52
I figured it out! It is because I had the "STIX" fonts installed locally, which I recall doing over a year ago (likely to improve performance).
What happens now is that the rendering for HTML-CSS and Common HTML appear to be identical? Is that normal?

**Comment by pkra** [comment] 2017-01-03 11:58
This second set of images you posted looked like you're using the `PreviewHTML` output. Was that the case?

**Comment by mehrdadn** [comment] 2017-01-03 12:42
Nope, that was HTML-CSS when I had STIX fonts installed. [Here](http://imgur.com/a/SQfnd) is what PreviewHTML looks like now (this is after I have STIX uninstalled, but I believe it looked the same before, and different from HTML-CSS).

**Comment by mehrdadn** [comment] 2017-01-03 13:23
By the way, are you able to reproduce the earlier problem with STIX fonts installed? If so, then that is a bug that may need to be fixed (I'm not sure if it's a font problem or a MathJax problem).

**Comment by mehrdadn** [comment] 2017-01-03 13:38
Actually, it seems I can't even reproduce it myself anymore, even after reinstalling the STIX fonts. I'm guessing my font installation had just become corrupted somehow? Sorry for the red herring.

**Comment by pkra** [comment] 2017-01-03 13:52
> Nope, that was HTML-CSS when I had STIX fonts installed. 

Thanks for confirming. The rendering looks broken to me.

> By the way, are you able to reproduce the earlier problem with STIX fonts installed? 

I had not yet tried.

>  it seems I can't even reproduce it myself anymore, even after reinstalling the STIX fonts.

Good to know but worth double checking on our end.

**Comment by pkra** [comment] 2017-01-26 09:05
Can't reproduce it with STIX so closing this for now.

**Closed by pkra** 2017-01-26 09:05 UTC
Labels: Cannot Reproduce
