### ISSUE TITLE
HTML-CSS, FF32+, stretchy integral clipped

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1009] opened 2015-01-19 10:03 UTC
Something as simple as `$$\int$$` gets clipped on the right, , e.g., on mathjax.org or using http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html. 

It happens at default and smaller zoom levels for me, disappears at larger zoom levels.

Seeing this on the `develop` branch as well.

**Comment by dpvc** [comment] 2015-01-19 14:25
This is a display bug in Firefox.  We have seen it in the past, but it appears that it has become much more reproducible since version 32.  The HTML generated by MathJax is not in error, but Firefox seems to be using the wrong clipping region.  (The ink for the integral sign lies considerably outside its character bounding box, which is likely the issue.)  You can get it to display properly by zooming out and then back in, for example, or resizing the window, or forcing a reflow in other ways, so this indicates that the underlying HTML is OK, and it is just not being displayed properly.

One hack solution would be to force a reflow after the math has been displayed (this is fragile).

The `sample-dynamic-2.html` file is actually somewhat complicated in that it uses a double-buffering approach so that the displayed result never shows the raw TeX code.  It appears that that might be part of what triggers the problem, as `sample-dynamic.html` (which is single-buffered) doesn't seem to exhibit the clipping.  I will have to see if I can come up with a minimal test case (not involving MathJax) that produces the problem.

**Comment by pkra** [comment] 2015-01-19 15:01
> This is a display bug in Firefox. We have seen it in the past, but it appears that it has become much more reproducible since version 32. 

Got it.

>  You can get it to display properly by zooming out and then back in, for example, or resizing the window, or forcing a reflow in other ways,

Usually (i.e., with other clipping bugs), that works for me, but FYI not this time. I do get some funky rendering artefacts when resizing the window though (the missing top right piece is smeared across the viewport). Fun...

>  It appears that that might be part of what triggers the problem, as sample-dynamic.html (which is single-buffered) doesn't seem to exhibit the clipping.

The following reproduces the error for me.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>MathJax#1009</title>
<script type="text/javascript" src="http://beta.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  </head>
<body>
  <p> Testing https://github.com/mathjax/MathJax/issues/1009</p>  
$$\int$$
</body>
</html>
```

> I will have to see if I can come up with a minimal test case (not involving MathJax) that produces the problem.

Thanks!

**Comment by dpvc** [comment] 2015-01-20 10:35
OK, I see the problem with just

``` html
<!DOCTYPE html>
<html>
<head>
  <title>Bad clipping of integral sign</title>
</head>
<body>
  <span style="font-size: 123%; font-family: MathJax_Size2;">&#x222B;</span>
</body>
</html>
```

but this relies on the font being local.  If I switch to the web font, then it doesn't clip.  

``` html
<!DOCTYPE html>
<html>
<head>
  <title>Bad clipping of integral sign</title>
  <style>
   @font-face {
     font-family: INTEGRAL;
     src: url("http://cdn.mathjax.org/mathjax/latest/fonts/HTML-CSS/TeX/otf/MathJax_Size2-Regular.otf");
   }
  </style>
</head>
<body>
  <span style="font-size: 123%; font-family: INTEGRAL;">&#x222B;</span>
</body>
</html>
```

Are you running with local fonts?  I will ask on SE if the OP there has local fonts.

I get even word results with local STIX fonts, but again, the web fonts work fine.  Not sure what's up with that.  I would hate to have to force web fonts for Firefox.

**Comment by dpvc** [comment] 2015-01-20 19:54
Well, it looks like everyone having the problem has local fonts installed.  Since a number of systems now come with STIX fonts installed, that is probably pretty common, now.

A temporary workaround for those experiencing it is to force the use of web-based fonts, which don't seem to exhibit the problem.  To do that, take the following steps:

*  Open the debugging console (select `Tools -> Web Developer -> Web Console` in the menu bar).
*  Type
    
        MathJax.Menu.showFontMenu(true);
    
    in the console type-in area and press RETURN.
*  Right-click on any typeset expression to open the MathJax contextual menu.
*  Select `Math Settings -> Font Preferences -> TeX (web)` (or `STIX (web)` if you prefer).
*  The page will reload, and you should be using web fonts rather than local fonts (use the `About MathJax` contextual menu item to verify that).

**Comment by pkra** [comment] 2015-01-28 08:37
Filed upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1126704

**Comment by pkra** [comment] 2015-03-10 09:02
Seems to be resolved ing FF36.

**Comment by dpvc** [comment] 2015-03-11 15:49
Good to know.

**Comment by pkra** [comment] 2015-03-30 13:15
And it's back.

**Comment by pkra** [comment] 2016-01-04 11:17
There's update from Mozilla on this https://bugzilla.mozilla.org/show_bug.cgi?id=1126704 It's unfortunate expected behavior from their performance optimizations. A workaround would be to use `optimizeLegibilty` but AFAIK is costly in terms of performance, cf. https://bocoup.com/weblog/text-rendering. Then again, it's always applied to webfonts for FF so to some degree we're not getting worse (but this might also explain why FF is always slower).

**Comment by dpvc** [comment] 2016-01-30 14:18
I'll check to see if that helps.  It would be possible to add this only for the affected characters (the integral signs are the only ones I know about).

**Comment by pkra** [comment] 2016-02-01 08:26
> . It would be possible to add this only for the affected characters (the integral signs are the only ones I know about).

Not for 2.6.1, correct?

**Comment by dpvc** [comment] 2016-02-01 15:55
It could go in 2.6.1.  I can have it only add the style to those characters that extend appreciably beyond their character width, like the integral signs.  That is a one-line change that only affects a small number of characters and it can be restricted to Firefox, so it is easy to run the tests again. Shall I do that?  I'm still waiting for a reply from Volker on my comments on his pull request, so 2.6.1 isn't quite ready for release anyway.

**Comment by dpvc** [comment] 2016-02-01 16:02
PS, I think this only affects HTML-CSS output, even though CommonHTML also uses the same fonts.  I'm not sure exactly why that is, but it may be because CommonHTML uses `@font-face` directives to access even the local fonts, and that may trigger the `optimizeLegibility` rendering even though it is not actually a web-based font.

Has anyone seen this clipping effect in CommonHTML?

**Comment by pkra** [comment] 2016-02-01 16:58
>  Shall I do that? 

Seems you did :wink:

> Has anyone seen this clipping effect in CommonHTML?

Not as far as I know.

**Comment by dpvc** [comment] 2016-02-01 17:35
By "that" I meant include this fix in 2.6.2 and run tests.  I haven't done that yet.  Figuring out if it would work was effectively figuring out the fix, so I made a branch that included it rant rather than lose the work.  That doesn't have to added to 2.6.1.

**Comment by pkra** [comment] 2016-02-01 19:54
Copy that.

**Comment by dpvc** [comment] 2016-02-06 17:27
=> Merged

**Closed** 2016-02-06 17:27 UTC
Labels: Accepted, Browser Bug, Merged, Test Needed

**Comment by dpvc** [comment] 2016-02-07 12:57
=> In testsuite

MathMLToDisplay/issue1009.html
