### ISSUE TITLE
Subscript failing with \left. ... \right|_{...}

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1926] opened 2018-02-09 10:16 UTC
![imagem](https://user-images.githubusercontent.com/1136663/36022662-bd81e53a-0d81-11e8-8bb1-57c3f50b3493.png)
For a live example see https://cdi2tp.math.tecnico.ulisboa.pt/texto/20
Seen in both Firefox and Chrome under Linux.

**Comment by zorkow** [comment] 2018-02-09 14:31
Thanks for reporting this. This is an error in the semantic enrichment algorithm.
For the time being if you switch off ``Collapsible Math`` in the ``Accessibility`` submenu it will go away.

**Comment by zorkow** [comment] 2018-02-09 14:36
Here's a minimal sample: 
```latex
\begin{gather*}\left.a\right|_{t} \end{gather*}
```

MathJax generates the following MathML expression:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable rowspacing="3pt" columnspacing="1em" displaystyle="true">
    <mtr>
      <mtd>
        <msub>
          <mrow>
            <mo fence="true" stretchy="true" symmetric="true"></mo>
            <mi>a</mi>
            <mo>|</mo>
          </mrow>
          <mrow class="MJX-TeXAtom-ORD">
            <mi>t</mi>
          </mrow>
        </msub>
      </mtd>
    </mtr>
  </mtable>
</math>
```

The reason enrichment fails is that it does not deal with the empty ``mo`` correctly. If it is removed it works fine. 
While enrichment should nevertheless be able to handle this case (and in particular not rewrite msub into msup!), @dpvc what's the reason for this empty ``mo``? I assume it is the ``\left.``; but where else can I expect them to occur?

**Comment by dpvc** [comment] 2018-02-10 13:26
> what's the reason for this empty `mo`? I assume it is the `\left.`

Yes, it is the `\left.` that is causing it.  

In TeX, the `\left.` still gets some spacing (from `\nulldelimiterspace`), and also affects the spacing between it and the previous element due to the TeX class of the delimiter (which is `OPEN` in this case).  Without the empty `mo`, MathJax would not do either of these.  To see it, note that `f\left.x\right.` has different spacing from `fx`.  Without the empty `mo` elements, the spacing would be identical.

> where else can I expect them to occur?

From TeX, that should be the only way to produce it, but of course, in MathML there is no stopping anyone from including empty `mo` elements like this, and MathJax treats `mfenced` elements as the equivalent `mrow`s with `mo`s, so you may be able to get empty ones there from `<mfenced open="" close=")">`, for example.  This may only be in the output, not the internal format, so this may not be an issue.

**Comment by dpvc** [comment] 2020-02-18 21:04
This turns out to have been fixed in 2.7.5, so I'm closing the issue.

**Closed by dpvc** 2020-02-18 21:04 UTC
Labels: Accepted, Upstream

**Comment by codeHatcher** [comment] 2020-08-28 05:58
This appears to be an issue in the current version

**Comment by dpvc** [comment] 2020-08-28 11:16
@codeHatcher, which version are you using, 2.7.9 or 3.1.0?  I am not able to reproduce the issue in either version.  Can you give more details of your situation?
