### ISSUE TITLE
Sample handles quick changes to large content badly

### ISSUE THREAD

**Issue by jaredwindover** [mathjax/MathJax#1132] opened 2015-03-21 16:55 UTC
sample-dynamic-2.html ignores changes to the content if its currently rendering the mathjax. I largely copy-pasted the code into my own tool and found this to be a bit of an annoyance, resulting in me adding spaces to see changes, or typing and deleting quickly. Also doesn't really make sense since there's a queue being used.

**Comment by pkra** [comment] 2015-03-23 10:25
Thanks for the comment. The motivation for not rendering while typesetting is performance. Queuing every change while typing can lead to large queues of edits that the author does not actually need, reducing performance. Arguably, this was more the case when this sample was written in 2012. I suppose when #933 is solved, this sample could clean the queue and then queue the new content. But when this sample was written, this was the best compromise.

For now, I've marked this expected behavior since the sample was intentionally written this way. Happy to discuss this further but fwiw, it sounds to me like your local change is pretty much on target: the samples are meant as a base to be modified for other use cases.

**Comment by jaredwindover** [comment] 2015-03-23 17:51
I see what you mean about queuing every change. What about just setting a flag that the content has changed while typesetting and we should call CreatePreview again afterwards? I know the samples aren't intended to be complete tools, but it seems to me there must be a better option than dropping any changes while typesetting.

**Comment by pkra** [comment] 2015-03-24 07:53
Good point. For lack of a better term, I'm tagging this `feature request `. PR is welcome.

**Comment by pkra** [comment] 2015-04-02 12:01
Fixed by #1148 -- thanks again for the contribution!

**Closed by pkra** 2015-04-02 12:01 UTC
Labels: Expected Behavior, Feature Request
