### ISSUE TITLE
positioning of subscript or superscript minus

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1187] opened 2015-05-08 18:40 UTC
A subscript or superscript minus sometimes (but not always) wanders too far from the target.  It seems to especially happen when the neighboring superscript/subscript slot is occupied at the same time. Adding curly braces to whatever is on text line seems to negate the effect, but I'm not sure why.  

See https://jsfiddle.net/s830g49p/

**Comment by dpvc** [comment] 2015-05-08 21:22
The issue is a little complicated.  TeX's spacing rules sometimes rely on the font metrics being set up in a particular way, and this turns out to be one of them.  In the TeX fonts, the height and depth of the minus are set to be the same as that of a plus (even though the minus doesn't take up that amount of vertical space), and that has an impact in the case of a base with both super and subscript (where the spacing between the two is based on the height and depth of the subscript and superscript).  MathJax's fonts don't have the extra space around the minus sign (the bounding boxes are tight for all the characters).

It is possible to adjust the bounding box information used by MathJax, but in this case, you have to be a bit careful, as the minus sign is used for several purposes (like extending arrows, and making horizontal lines for things like square roots, `\overline`, and `\underline`.  So while changing the bounding box information for the minus would fix the super- and sub-script problem, it would cause other things to be spaced improperly.

It is easy to change the character used for the horizontal line to a different one (like U+00AF), so that is not really a problem.  But changing the height and depth of the minus will affect the height and depth of stretched arrows, and that is harder to fix.

Here is a work-around you can use for now, if you don't mind the slight change in positioning of stretched arrows.  Add the following to your page just *before* the script that loads MathJax.js itself.

``` html
<script>
MathJax = {
  AuthorInit: function() {
    MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/HTML-CSS/fonts/TeX/fontdata.js",function () {
      var FONTDATA = MathJax.OutputJax["HTML-CSS"].FONTDATA;
      var MAIN = FONTDATA.FONTS.MathJax_Main;
      MAIN[0x2212][0] = MAIN[0x002B][0];
      MAIN[0x2212][1] = MAIN[0x002B][1];
      FONTDATA.RULECHAR = 0x00AF;
      FONTDATA.DELIMITERS[0x2212] = {alias: 0x00AF, dir: "H"};
    });
    MathJax.Hub.Register.LoadHook("[MathJax]/jax/output/HTML-CSS/fonts/STIX/fontdata.js",function () {
      var FONTDATA = MathJax.OutputJax["HTML-CSS"].FONTDATA;
      var STIX = FONTDATA.FONTS.STIXGeneral;
      STIX[0x2212][0] = STIX[0x002B][0];
      STIX[0x2212][1] = STIX[0x002B][1];
    });
  }
};
</script>
```

This adjusts the height and depth of the minus is the TeX font (local or web based) and local STIX font (the two that are used by MathJax by default).  It also fixes the horizontal lines in the TeX font (this is not needed for STIX since it already uses a different one).  If you plan to use one of the other web fonts, similar changes would need to be added for them as well.

**Comment by andreacassioli** [comment] 2015-09-18 12:01
Hi,
I am experiencing something similar:

```
\mathcal{S}^n_+
```

is rendered perfectly with pdflatex, but with Mathjax the `n` superscript is too much on the right, exactly after the `+`.

**Comment by dpvc** [comment] 2015-09-19 12:28
@andreacassioli, I am not sure i understand the problem you are seeing.  These are what I see:

![super-sub](https://cloud.githubusercontent.com/assets/432782/9976141/21e176a2-5ea8-11e5-9e28-2f823da79740.png)

I don't see a significant difference between them.  Perhaps you can link to a page that exhibits the problem.

**Comment by dpvc** [comment] 2016-06-17 02:21
The `font-fixes` branch of my fork of MathJax includes fixes for the minus-sign height/depth problem.

**Comment by dpvc** [comment] 2016-07-08 12:56
==> Merged

**Closed** 2016-07-08 12:56 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-18 11:34
==> In testsuite

MathMLToDisplay/issue1187.html
