### ISSUE TITLE
Latex New Line Command "\\" Do Not Create New Line

### ISSUE THREAD

**Issue by zayn7lie** [mathjax/MathJax#3036] opened 2023-04-20 08:43 UTC
### Issue Summary

When I want to create new line in a latex block, it appears success in vscode preview but I fail to do that in my webpage.

### Steps to Reproduce:

1. Create a Latex block in a post:

```latex
$$
Something_A \\
Somgthing_B
$$
```

2. Compiling to webpage using MathJax

It is expected to appear:

```
Something_A
Something_B
```

but it appears:

Something_ASomething_B

### Technical details:

* MathJax Version: 3.2
* OS: windows 11
* Browser: Mozilla/5.0(firefox 112.0.1)

I am using the following MathJax configuration:

``` js
MathJax = {
...
};
```

and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

### Supporting information:

This is a discussion of this issue:
https://github.com/cotes2020/jekyll-theme-chirpy/issues/999

**Comment by dpvc** [comment] 2023-04-20 11:35
This is a duplicate of #2312.  Linebreaks are not pat of v3, but are in v4, which is now out in [alpha release](https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1).

**Comment by zayn7lie** [comment] 2023-04-20 14:00
> This is a duplicate of #2312.  Linebreaks are not pat of v3, but are in v4, which is now out in [alpha release](https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1).

Sorry, I did not find it.
Get it now, thanks.

**Closed** 2023-04-21 04:52 UTC
Labels: Duplicate
