### ISSUE TITLE
problem with default.js config settings for displayed equations and tags

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1015] opened 2015-01-21 18:15 UTC
In trying the 2.5-beta download, I've noticed that numbered displays aren't working as expected when using default.js for the configuration settings.  First, the displays are pushed all the way to the left rather than being centered.   Second, if I change the preference for the tag side to left instead of right (line 508: TagSide: "left"), then the tags overlap the equations.  This is different from how 2.4 behaves, but the file looks pretty much the same.

It looks like the script may be misinterpreting lines 176 and 177 (displayAlign: "center", displayIndent: "0em").  It seems to be acting as if displayAlign were set to "left" instead of "center".  The displays stay on the left regardless of whether we opt for left, center or right.  But in 2.4, we can choose any of the three positions and the displays render as desired.  If I block lines 176 and 177 by commenting them out, the displays move to the center.

Here's are some examples where I've tried to replicate problem with the settings using the CDN:
http://jsfiddle.net/0jL9f5q5/  (tags on right, displays not centered)
http://jsfiddle.net/bL843ugj/  (tags on left, displays not centered)
http://jsfiddle.net/8bjr0mz4/  (tags on right, with displayAlign and displayIndent omitted)
http://jsfiddle.net/r2nhtt5m/  (tags on left, with displayAlign and displayIndent omitted)

**Comment by dpvc** [comment] 2015-01-21 18:32
This is a duplicate of issue #1000 (which has been resolved, but not yet pushed to the CDN).

**Comment by dpvc** [comment] 2015-01-21 18:35
PS, changing `displayIndent` from `"0em"` to just `"0"` should avoid the problem until the fix is pushed to the CDN.

**Closed** 2015-01-21 18:35 UTC
Labels: Duplicate

**Comment by dpvc** [comment] 2015-01-21 18:37
PPS, thanks for the detailed and careful report.  That would have been very helpful if we hadn't already worked it out earlier.
