### ISSUE TITLE
MathJax3 left curly brace misaligned and not smooth

### ISSUE THREAD

**Issue by MacroUniverse** [mathjax/MathJax#2311] opened 2020-02-02 05:30 UTC
Hi,
I found these two little bugs after switching to MathJax3 (I'm using Chrome browser)
1. The brace is not smooth when there are many lines ([html page](http://wuli.wiki/online/Arctan.html))
![image](https://user-images.githubusercontent.com/33382811/73603602-833e0e00-454a-11ea-922f-568260e87338.png)
![image](https://user-images.githubusercontent.com/33382811/73603605-96e97480-454a-11ea-853b-ece5a36a486a.png)
2. The brace is lower than it should be ([html page](http://wuli.wiki/online/BndSho.html))
![image](https://user-images.githubusercontent.com/33382811/73603609-a4066380-454a-11ea-9ac7-10e632015de8.png)
![image](https://user-images.githubusercontent.com/33382811/73603613-af598f00-454a-11ea-8d66-dac47a310402.png)
3. Also, if multiple & are used for alignment, no error will be reported, but this is not allowed in LaTeX

**Comment by dpvc** [comment] 2020-02-03 19:17
You first issue is a duplicate of #2186 and #2038 

For your second, can lousy what browser and OS you are using?  Does it change if you zoom in our out?

**Comment by MacroUniverse** [comment] 2020-02-06 09:24
@dpvc I'm using Windows 10, and it become smoother if I zoom in

**Comment by dpvc** [comment] 2020-02-10 19:48
What browser are you using?

The middle part is handled using a transform that stretches the piece (vertically) so that only one piece is needed regardless of the size of the brace.  That means that the rounding to pixel positions may not be exactly the same for the stretched and unstreched parts.  Because that is dependent on scaling and other factors, it may be hard to find a solution that works at all scales in all browsers on all platforms.

I'll have to see what I can figure out.

**Comment by dpvc** [comment] 2020-03-05 16:34
I have made a pull request with a change that helps the brace situation at most scaling factors.

For now, you can add

``` css
mjx-stretchy-v > * > mjx-c {
    transform: scaley(1.0000001) ! important
}
mjx-stretchy-h > * > mix-c {
   transform: scalex(1.00000001) ! important
}
```

to the CSS for your page in order to get the same result until the next release of MathJax is available.

**Closed** 2020-04-10 16:13 UTC
Labels: Accepted, Fixed, Merged, Test Needed, v3
