### ISSUE TITLE
CommonHTML fraction rendering results in overlap with surrounding punctuation

### ISSUE THREAD

**Issue by barillax** [mathjax/MathJax#1393] opened 2016-02-18 16:08 UTC
Test cases:

`Here's a fraction $ \dfrac{11}{100} $.`
`Here's a fraction $ \dfrac{11}{100} $!`

Notice that the punctuation ending the sentence will overlap with the fraction due to the `position: absolute` fraction bar not contributing to the width of MathJax span.

There are ways to hack around this, such as manually inserting `\space` onto the end of the MathJax, but  it wasn't necessary in the HTML-CSS processor previously. Suggestions for better workarounds are welcome!

**Comment by pkra** [comment] 2016-02-18 16:35
I'm unable to reproduce this. Please provide a live sample and information on browser and OS versions. For more suggestions, see also https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports

**Comment by barillax** [comment] 2016-02-18 16:43
Sorry about that. OS/Browser info:

Mac OS X 10.11.2
Chrome 48.0.2564.109
MacBook Pro Retina Display

I used the demo on MathJax.org to test and reproduce. Here's a screenshot on [Imgur](http://i.imgur.com/p6o0zCh.png).

**Comment by pkra** [comment] 2016-02-18 16:53
Thanks for the follow up. For mathjax.org, this is caused by CSS interference (bootstrap's aggressively resetting box-sizing after every element).

ping @dpvc

**Comment by barillax** [comment] 2016-02-18 16:55
Oh interesting! We're using bootstrap on our site, too, so perhaps that's why we're hitting the same problem.

I assume bootstrap compatibility is somewhat important. Is there a known way to "unbreak" this in bootstrap?

**Comment by mattblang** [comment] 2016-02-18 17:03
We are seeing this as well. You can definitely notice the difference by toggling the `box-sizing: border-box` on and off in chrome debugger.

**Comment by booleanbetrayal** [comment] 2016-02-18 17:06
```css
.MJXc-stacked {
    box-sizing: content-box;
}
```

Maybe?

**Comment by barillax** [comment] 2016-02-18 17:09
I added:

.mjx-chtml {
    &, 
    span {
        box-sizing: initial;
    }
}

and that also seemed to fix it. Sound safe?

**Comment by booleanbetrayal** [comment] 2016-02-18 17:11
:+1:

**Comment by dpvc** [comment] 2016-06-07 14:47
The `issue1393` branch of my fork of MathJax adds CSS to the CommonHTML output to prevent the bleed-through of the `box-sizing` CSS set by bootstrap.

**Comment by dpvc** [comment] 2016-07-06 17:52
==> Merged

**Closed** 2016-07-06 17:52 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-15 00:40
==> In testsuite

MathMLToDisplay/issue1393.html
