### ISSUE TITLE
svg parse error

### ISSUE THREAD

**Issue by OnePsycho** [mathjax/MathJax#2661] opened 2021-03-22 06:33 UTC
![e569895c7732dd6cd3d4c6700a4e753](https://user-images.githubusercontent.com/43296632/111949373-911e6c00-8b1b-11eb-88fa-6a7230e1818b.png)
![59941abb9433849b7ef4f8f4258b6ce](https://user-images.githubusercontent.com/43296632/111949375-9380c600-8b1b-11eb-8972-6b7004bd2613.png)

**Comment by dpvc** [comment] 2021-03-22 11:57
The output in your image is correct for the TeX commands that you have entered.  In TeX, a macro name is initiated by a `\` and consists of the longest string of letter (a-z, A-Z) that follows, or by a single non-letter character that follow.  So when you type `\pix` that is the command that TeX receives.  Since that is not defined, MathJax displays it in red to inform you that it is not recognized.  What you should type is `\pi x` if you want *π x*.  The space is no optional, as it is necessary in order to end the `\pi` command.

Similarly, for `\deltax` you should enter `\delta x` and for `\deltay` it should be `\delta y`.  

So this is not a TeX parse error, it is an author TeX entry error.

**Comment by dpvc** [comment] 2021-03-22 11:58
This is duplicate of #2657.

**Closed** 2021-03-31 14:29 UTC
Labels: Duplicate, Expected Behavior
