### ISSUE TITLE
norm sign is incorrect

### ISSUE THREAD

**Issue by polo88hu** [mathjax/MathJax#1621] opened 2016-09-15 17:39 UTC
If letters have different heigh, and they are wrapped with the norm sign in mathml, the high of norm sign is different.
![wrong](https://cloud.githubusercontent.com/assets/22222665/18560416/b46b60a0-7b7b-11e6-904c-b03beecf2023.png)

The expected behavior would be to apply the same high. 
![correct](https://cloud.githubusercontent.com/assets/22222665/18560434/cbe02522-7b7b-11e6-9b02-9a13b3ee258f.png)

The problem is perhaps that MathJax consider the U+2225 as the norm sign, but U+2016 is [recommended](https://en.wikipedia.org/wiki/Norm_(mathematics)#Notation). E.g. MathType follows the recommendation when it produces MathML output.

**Comment by polo88hu** [comment] 2016-09-15 18:40
I used
`<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>`
Windows 7, Chrome 53. The code:
`<math display='block'>
 <mrow>
  <mrow><mo>&#x2016;</mo> <mrow>
   <mi>a</mi><mi>b</mi></mrow> <mo>&#x2016;</mo></mrow><mo>&#x2264;</mo><mrow><mo>&#x2016;</mo> <mi>a</mi> <mo>&#x2016;</mo></mrow><mo>&#x22C5;</mo><mrow><mo>&#x2016;</mo> <mi>b</mi> <mo>&#x2016;</mo></mrow></mrow>
</math>`

But if as you've written, it is already an issue, then there's no need to take action.

**Comment by pkra** [comment] 2016-09-15 19:06
> But if as you've written, it is already an issue, then there's no need to take action.

The fix for #1175 was already deployed to the CDN so you shouldn't encounter that anymore. Could you try clearing your browser cache and see if that fixes things?

**Comment by dpvc** [comment] 2016-09-15 20:32
@pkra, the fix is only in the beta version at this point, not the main CDN version, so the OP won't get that unless he switches to the beta copy.  And there is also #1612, which hasn't been merged to develop yet (pending a review), that would cause the beta version on the CDN to produce incorrect results anyway.

**Comment by dpvc** [comment] 2016-09-15 20:35
I just confirmed that #1612 resolves the issue for me (and I do see the OP's same results without it), so I think the issue is resolved in 2.7

**Comment by pkra** [comment] 2016-09-16 07:06
> @pkra, the fix is only in the beta version at this point, not the main CDN version, so the OP won't get that unless he switches to the beta copy. And there is also #1612, which hasn't been merged to develop yet (pending a review), that would cause the beta version on the CDN to produce incorrect results anyway.

Ah, thanks, @dpvc! I had missed that. I'm too focused on the beta ;-)

**Comment by dpvc** [comment] 2016-09-27 22:47
The PR has been merged to develop.

**Closed by dpvc** 2016-09-27 22:47 UTC
Labels: Duplicate
