### ISSUE TITLE
MathJax_Processed not removed

### ISSUE THREAD

**Issue by shuminheng** [mathjax/MathJax#1171] opened 2015-04-23 05:37 UTC
Hi guys,

We have been noticing a strange issue recently. Every now and then, MathJax is processed but is not displayed. We noticed it happening after we upgraded to 2.5.* but obviously that doesn't mean it's an issue with version 2.5.* specifically.

Unfortunately, there are no known reproduction steps. It seems to happens randomly on both Windows and Mac. However, it just happened on one of our pages and we managed to have a dig around in the inspector to see if we could track down the cause of the issue.

**1**
![1](https://cloud.githubusercontent.com/assets/9277931/7290935/30a0d4be-e9cb-11e4-9c72-63c572798ec6.gif)

These are the contents of a container where the MathJax displays *correctly*.

**2**
![2](https://cloud.githubusercontent.com/assets/9277931/7290941/5052acb0-e9cb-11e4-9ec4-782d2446cf37.gif)

These are the contents of a different container where the MathJax *doesn't* display correctly. We've inferred by comparison with **1** that:

* There should only be one MathJax-Element-155-Frame span. The two here have the same id, which obviously isn't valid, so is likely not intentional
* One of the two blocks of maths in the first MathJax-Element-155-Frame span should be in the second (which is empty here)
* The first MathJax-Element-155-Frame span with the MathJax_Processed class shouldn't be there. This span also has a display:none !important rule set on it, which leads us to believe that MathJax knows, in some way, that it's not supposed to be there

This is all speculation of course, and we're hoping the MathJax team can help shed some light on why this might be happening. Thanks in advance for any tips!

**Comment by pkra** [comment] 2015-04-23 09:14
Duplicate of #1131? We'd need more information than this. A live sample is always best, even if it's erratic, browser OS version are also important. 

Please re-check https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md

**Comment by dpvc** [comment] 2015-04-23 11:31
The data you provide is actually quite useful, as it does suggest a possible cause for the problem.  The fact that there are two frame spans with the same number, and two copies of the expression (both in the same frame) suggests that `MathJax.Hub.Typeset()` is getting called twice without proper synchronization, so that the second call is being made before the first one has completed.

MathJax's output is done in three separate phases:  the first phase creates the frames for all the equations and does some measurements needed to get the scaling and em-size right (this is done for all equations at once to avoid reflowing the page for each equation).  The second phase does the actual typesetting of the equations, but marks them with `MathJax_Processed` so that they are not displayed immediately (this is controlled by MathJax's chunking parameters, and improves both the performance by not doing reflows for each equation, but also helps the visual jitter by updating the page fewer times).  The third phase remeasures all the equations in one chunk to make sure the proper amount of space is reserved, and then removes the `MathJax_Processed` class to let them be displayed.

If an equation requires an extension to be loaded, or a new font to be used, this causes MathJax to pause while that data is retrieved, and during that time, your code can run and may be initiating a second typeset run while the first is waiting for something to load.  That would cause MathJax to insert a *second* frame element for any math that hasn't been processed yet, and a second copy of the output.

It turns out that the second and third phases look up the frame element in two different ways (phase two find it by ID, while phase three uses the element just before the script tag containing the original math shown at the bottom of your images).  So if there are two frame elements with the same ID phase two will find the first of these both times it runs (accounting for two copies of the math in one frame element) and apply the `MathJax_Processed` class to that, while the third phase will find the second frame in both cases try to remove `MathJax_Processed` from that (leaving the first frame still with its `MathJax_Processed` class in place).

So the issue, then, is why are two typesetting calls being done simultaneously?  This has to do with how you are calling MathJax on your page.  Can you say something about your page setup?  I'm assuming it is dynamically created and that you are calling `MathJax.Hub.Typeset()` when the contents change.  Can you let us know how that works for you?  Also, are you using `MathJax.Hub.Queue(["Typeset",MathJax.Hub])`, or are you calling `MathJax.Hub.Typeset()` directly?

Peter's call for a live page would make it possible for us to check on things like this.

**Comment by andybluntish** [comment] 2015-04-24 01:43
Hi David, I'm working with @shuminheng on this issue.

Firstly, thanks for that awesome response, it's helped our understanding a lot.

This problem presents itself inside a piece of dynamically loaded content, so there is a high chance it's getting typeset twice simultaneously. The sequence goes like this:

1. Main page content loads and maths is typeset with `MathJax.Hub.Queue(["Typeset",MathJax.Hub, el])`
2. Dynamic content (which also contains LaTeX) is loaded and injected into the page
3. Once complete, we queue another typeset, but scope it to the dynamic element we just inserted to render the maths in the dynamic content.

So, from your explanation, it sounds like (sometimes) the dynamic content is being injected into the page before the initial typeset, and thus being rendered. Then, before the initial typeset is complete, the second is triggered in the callback.

Does this sound right to you? I was under the impression that by queuing each typeset they would happen in sequence.

My guess is that we can solve this by either ensuring the initial typeset ignores our dynamically created element, or waiting for the initial typeset to finish before injecting more content.

**Comment by dpvc** [comment] 2015-04-24 15:14
If you are using `MathJax.Hub.Queue()` as in your example above, that *should* prevent exactly this from happening.  The whole point of the queue is to make sure that the things later in the queue don't execute until the earlier ones are completely finished, even if they do have to wait for file access.

Can you check to make sure that *all* calls to `MathJax.Hub.Typeset()` are within a `Mathjax.Hub.Queue()` call?  Is it possible to post the code that interacts with MathJax?

I can try to work out some tests to see if we can isolate what is happening.

**Comment by dpvc** [comment] 2015-04-24 15:23
Here is one thing you can try right away.  Add

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.signal.Interest(function (message) {console.log("HUB: "+message)});
</script>
```

to your page somewhere `BEFORE` the script that loads `MathJax.js` itself.  This will generate a lot of output concerning MathJax's internal processing of the page, and one of the key things we want to see is whether there are `Begin Math/End Math` pairs interleaved.  If so, w can look further into where they are coming from.

If you could post the console log you get from this, I'll take a look and see what can be learned from that.

**Comment by dpvc** [comment] 2015-04-24 15:24
@andybluntish, Here is one thing you can try right away.

Add

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.signal.Interest(function (message) {console.log("HUB: "+message)});
</script>
```

to your page somewhere `BEFORE` the script that loads `MathJax.js` itself.  This will generate a lot of output concerning MathJax's internal processing of the page, and one of the key things we want to see is whether there are `Begin Math/End Math` pairs interleaved.  If so, w can look further into where they are coming from.

If you could post the console log you get from this, I'll take a look and see what can be learned from that.

**Comment by andybluntish** [comment] 2015-04-25 04:06
Thanks @dpvc, I'll give it a shot.

**Comment by dpvc** [comment] 2016-04-08 18:33
@shuminheng and @andybluntish, are you still having this issue?  I have recently made some updates to issue #1384 that might resolve your issue as well, especially if your pages are removing math that MathJax hasn't typeset yet.  You might give it a try...

**Comment by shuminheng** [comment] 2016-04-18 05:36
Hi @dpvc, thanks for getting back in touch about this (you have a good memory!).

For what it's worth, we recently found that by not using the "MatchWebFonts" extension, we could eliminate disappearing MathJax from occurring in a very specific scenario. This scenario involves integration with a 3rd party component, so it's not really a straightforward, everyday use case that you probably want to hear about. We haven't noticed MathJax disappearing in any other context anymore, which is great :)

The other issue you mention is also helpful because we actually do have another problem involving _duplicate_ MathJax appearing (i.e. MathJax expressions rendering twice under certain conditions), but I'm pretty sure we have narrowed that down to an integration issue with the aforementioned 3rd party. Regardless, I will link them to your findings, just in case it helps their debugging.

Again, thanks for getting back in touch. We'll let you know if this issue pops up again :)

**Comment by dpvc** [comment] 2016-04-18 12:15
@shuminheng, thanks for the update.  I'm glad you resolved one of your problems by dropping MatchWdbFonts.  One way to check if the duplicate math issue is the one resolved in issue 1384 would be to switch (temporarily) to the CommonHTML output (new in v2.6).  If that doesn't show the duplication, then it is a good bet that it is the same issue.

Good luck!

**Comment by dpvc** [comment] 2016-08-31 11:54
I believe that the changes I rented above will resolve this problem, so I'm closing it.

**Closed** 2016-08-31 11:54 UTC
Labels: Accepted

**Comment by pkra** [comment] 2016-08-31 12:37
@dpvc "rented"?

**Comment by dpvc** [comment] 2016-08-31 12:39
Sorry, autocorrect.  It should have been "mentioned".  I'll fix it.

**Comment by pkra** [comment] 2016-08-31 12:57
Thanks! I couldn't reconstruct the auto-correct 📲
