### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by dnlbaines** [mathjax/MathJax#1180] opened 2015-04-30 18:41 UTC
Since the latest update MathJax has all sorts of rendering issues on my website:
![render](https://cloud.githubusercontent.com/assets/3681102/7419986/c4a3cbf8-ef70-11e4-8d29-fa7ed696350b.png)
Reverting to 2.4-latest solves the issue:
![render2](https://cloud.githubusercontent.com/assets/3681102/7420008/e6c32fa8-ef70-11e4-833b-7f8f59aaacb7.png)

**Comment by dpvc** [comment] 2015-04-30 18:49
This looks like a duplicate of #1179.  Is your content loaded dynamically using a container that has `display:none` while the math is processed by MathJax, and then revealed afterward?

**Comment by dnlbaines** [comment] 2015-04-30 18:51
Yes I suppose it is, as the page is split into expandable topics which are shown on click.

**Comment by dpvc** [comment] 2015-04-30 18:51
Thanks for the confirmation.  I'm closing the issue as a duplicate, then.

**Closed by dpvc** 2015-04-30 18:51 UTC
Labels: Duplicate
