### ISSUE TITLE
<wbr> tags

### ISSUE THREAD

**Issue by mark-wade** [mathjax/MathJax#1087] opened 2015-03-10 14:46 UTC
I am a developer for a forum software which, to prevent long user-provideds topic titles with no spaces from breaking the layout, inserts wbr tags every 20 characters in words in titles that are longer than that. For example, if a user creates a title "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", it will get rendered as "aaaaaaaaaaaaaaaaaaaa-wbr-aaaaaaaaaaaaaaaaaaaa" (am using "-wbr-" rather than the actual tag as GitHub seems to parse it)

A bug report was submitted to us that this causes MathJax to not work correctly: http://community.invisionpower.com/4bugtrack/wbrwbr-randomly-added-to-topic-titles-after-upgrading-r3931/

The HTML5 <wbr> tag represents a word-break oppertunity within text. Since MathJax modifies the content, it would be appropriate for it to ignore such tags within the content it intends to replace.

**Comment by pkra** [comment] 2015-03-10 17:30
Unfortunately, TeX-like syntax and HTML markup do not play well together.

For sanity reasons, the tex2jax preprocessor stops parsing at HTML elements. I don't think it's likely we will change this behavior anytime soon (if ever).

If the situation is restricted enough, I suppose you could do some regexp clean up before `tex2jax.js` starts up but then again it might be cleaner to isolate the TeX while saving (since the forum software modifies the content anyway).

**Comment by mark-wade** [comment] 2015-03-10 18:01
Could you direct me to where abouts in the code that's done?

**Comment by pkra** [comment] 2015-03-10 21:00
Which part are you referring to? The tex2jax part or the "do it yourself" part? For the latter, just run whatever works for your setup before MathJax.js is loaded, e.g., as part of a custom configuration (see http://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options).

**Comment by mark-wade** [comment] 2015-03-12 15:21
Wherever it halts on a HTML tag.
As an aside, someone mentioned to me that it ignores br tags... is that right? If so, would it actually be terribly dramatic to alter that to also do whatever it does there for wbr?

**Comment by pkra** [comment] 2015-03-12 15:42
Hm... did I put my foot in my mouth? [Looks](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents) like [it](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/tex2jax.js#L167). So now we're in a slippery-slope discussion. @dpvc ?

**Comment by dpvc** [comment] 2015-03-12 18:41
There is also an instance at [this line](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/tex2jax.js#L259).

I was going to say that we already handle `<br>` (and that was because some blog software inserted it automatically), so there is precedent for adding `<wbr>`.  I don't have a particular problem adding it, and it would be possible, I suppose, to make the list of such elements customizable.  For elements with no children, like `<br>` and `<wbr>`, it is not hard to ignore them; it is less clear what one should do with other markup, however.

**Comment by pkra** [comment] 2015-03-12 22:30
I'm ok with ignoring `<wbr>`. I'd be in favor of hardcoding that list; it's simpler and it seems a very rare request. There's always `AuthorInit` for those who need more.

**Comment by dpvc** [comment] 2015-03-13 11:31
A lookup list can actually simplify and speed up the code when there are multiple things to match against, and probably would do so in this case.  I'm not sure what you have in mind for `AuthorInit`, as I don't see how it helps (unless you mean to set up a listener for `tex2jax` and override its internal routines).

**Comment by pkra** [comment] 2015-03-13 17:05
>  I'm not sure what you have in mind for AuthorInit,

I meant that in the situation as in the OP -- where the underlying software inserts HTML elements -- developers can hook up their own pre-processing to undo changes caused by their software of choice. After all, they know best what needs to be done. I don't think we necessarily need to provide anything beyond that.

**Comment by dpvc** [comment] 2015-03-13 17:08
OK, got it, thanks.

**Comment by ehku** [comment] 2015-07-19 15:01
Hello,
It's been 4 months now. Could you please consider adding this feature to the next update?

**Comment by pkra** [comment] 2015-07-23 10:31
@ehku wrote

> Could you please consider adding this feature to the next update?

I'm afraid this issue is not in the milestone for the next release. But we're always open to pull requests, see https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md. @dpvc already suggested a path to generalize the current approach and we're happy to help with any questions.

**Comment by ehku** [comment] 2015-08-19 19:14
@pkra @dpvc Thank you for your replies.

In both extensions/tex2jax.js and unpacked/extensions/tex2jax.js of my local installation, I have made the following modifications 

Line 167: 

replace 
element.nodeName.toLowerCase() === 'br'

with 
element.nodeName.toLowerCase() === 'br' || element.nodeName.toLowerCase() === 'wbr'

Line 259:

replace 
math.nextSibling.nodeName.toLowerCase() === "br" ? "\n" : " "

with
math.nextSibling.nodeName.toLowerCase() === "br" || math.nextSibling.nodeName.toLowerCase() === "wbr"

but the results are the same :( 

Any idea please?
Thank you very much in advance!

**Comment by dpvc** [comment] 2015-08-19 21:37
Your changes work for me (provided you also include the `? "\n" : " "` in the line 259 change, which I assume you did).

Note, however, that you might need to quite the browser and start it again after making the change, as otherwise the old version may still be in the cache (and forced reload may not clear it).  That is true for Chrome, for example.  Firefox works better for this kind of testing; I don't have to restart it on Mac OSX, at least.

**Comment by ehku** [comment] 2015-08-21 13:51
Thanks, @dpvc .
Yes I did included ``` ? "\n" : " " ```:
```javascript
math.nodeValue += ( (math.nextSibling.nodeName.toLowerCase() === "br" || math.nextSibling.nodeName.toLowerCase() === "wbr") ? "\n" : " ");
```
Could you please have a look at this: http://networkflow.net/index.php?/forum/4-optimization/ ? (The top topic title is ignored by MathJax.)

**Comment by dpvc** [comment] 2015-08-21 14:21
The version of `tex2jax` that you are using on that page is actually coming from the combined configuration file (it contains the code for most of the components that you are using) and so is the unmodified version.  You would need to either replace the code in the `TeX-AMS-MML_HTMLorMML-full.js` file, or remove the `tex2jax` that is there (both in the `MathJax.Ajax.Preloading()` call, and the compressed code itself lower down in the file, or switch to the unpacked version by adding `unpacked/` before the `MathJax.js` in the script call that loads MathJax.

**Comment by ehku** [comment] 2015-08-21 14:57
Oh yes, I modified the configuration file and now I see something has changed :D It remains a problem, though.
In the previous example, the resulting formula is still not correct. I guess that MathJax replaced "<wbr>" with a space so code like "\mat<wbr>hbf{"  are converted to "\mat hbf{". 
If that was MathJax that replaced the tag with a space, then how to simply remove the tag and not add a space?
I tried to replace ```? "\n" : " "``` in the line 259 by ```? "\n" : ""``` but it does not work. 
Thanks again, @dpvc !!!

**Comment by dpvc** [comment] 2015-08-21 15:27
It's actually the space in the next line that is the one that is breaking up your macros.  Note that 259 is only executed when `msieNewlineBug` is true (which is only the case in IE8 and below).  I would say you want to replace

``` javascript
} else if (this.msieNewlineBug) {
  math.nodeValue += (math.nextSibling.nodeName.toLowerCase() === "br" ? "\n" : " ");
} else {
  math.nodeValue += " ";
}
```

by

``` javascript
} else if (this.msieNewlineBug) {
  math.nodeValue += (math.nextSibling.nodeName.toLowerCase() === "br" ? "\n" : 
                     math.nextSibling.nodeName.toLowerCase() === "wbr" ? "" : " ");
} else if (math.nextSibling.nodeName.toLowerCase() !== "wbr") {
  math.nodeValue += " ";
}
```

or something along those lines.

**Comment by ehku** [comment] 2015-08-21 15:42
It works like a charm now :D Thank you so so much, Davide!!!!!

**Comment by dpvc** [comment] 2015-08-21 15:47
Glad it is working for you.

**Comment by dpvc** [comment] 2016-07-06 01:07
The `issue1087` branch of my fork of MathJax contains the patch for this.

**Comment by dpvc** [comment] 2016-07-23 19:57
==> Merged.

**Closed** 2016-07-23 19:57 UTC
Labels: Feature Request, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-18 23:24
==> In testsuite

Parsing/issue1087.html
