### ISSUE TITLE
Regression in v2.5 beta with handling of LaTeX `label` command

### ISSUE THREAD

**Issue by timtylin** [mathjax/MathJax#1018] opened 2015-01-23 02:13 UTC
There seems to be some weird regressions in the handling of TeX equations with a `\label` command with v2.5. The problem seems to be on the parsing side since it happens with the default configuration that doesn't even have equation numbering turned on.

The following parses correctly with the current v2.4 off CDN

<http://jsfiddle.net/jdnde3tz/>

![](https://www.evernote.com/shard/s145/sh/0a3c550e-b8af-45ef-a3c2-46a0be54154b/ac03a65c7d267447468212bcee328c44/deep/0/Edit-fiddle---JSFiddle.png)

but if you change it to the v2.5 beta, it refuses to parse

<http://jsfiddle.net/jdnde3tz/2/>

![](https://www.evernote.com/shard/s145/sh/71ac7e9f-e551-4390-bbab-2adc391ca831/b74ad92bd056d050b844b2e63b805ae1/deep/0/Edit-fiddle---JSFiddle.png)

removing the label command causes it to parse correctly again

<http://jsfiddle.net/jdnde3tz/3/>

![](https://www.evernote.com/shard/s145/sh/76a3524a-6dd6-42e8-89d4-ab3af244d70f/cb5a82051c901c5f5da7a9c06a3bbda1/deep/0/Edit-fiddle---JSFiddle.png)

**Comment by pkra** [comment] 2015-01-23 09:55
Thanks for the report. The TeX error is `Label 'eq:EPSIoptimForm' multiply defined`. 

This seems to be caused by the new preview mode. Disabling it seems to fix it. See http://jsbin.com/datipaneme/1/edit

We'll look into it.

**Comment by dpvc** [comment] 2015-01-23 16:21
The problem turns out to be a subtle issue with the new fast preview mode.  Under some conditions, the preview code must load other files (in this case, part of the operator table was being loaded), and since file loads are asynchronous, that has to interrupt the processing of the equations temporarily.  After the file is loaded, the current equation is reprocessed.  It turns out the CHTML-preview code wasn't handling that condition correctly, and the code that records the labels and other information was running while the CHTML-preview was waiting for the file to arrive.  Then when the file arrived and the equation was reprocessed, the label was listed as already in use, causing the error the Peter reported above.

For now, you can either disable the fast preview, as Peter suggests, or add

``` html
<script type="text/x-mathjax-config">
  MathJax.Extension["CHTML-preview"].postFilter =
    function (preview,data) {data.math.root.toCommonHTML(preview)}
</script>
```
just before the script that loads MathJax.js itself provided you are using one of the combined configuration files, not your own configuration or the default.js configuration file; for those you would need a more complicated replacement.

I am working on a more general fix for the v2.5 release.

**Comment by dpvc** [comment] 2015-01-23 17:48
The `issue1018` branch of my fork of MathJax has a fix or the issue.

**Comment by timtylin** [comment] 2015-01-23 21:38
It's really awesome how quickly this got figured out. Thanks!

**Comment by dpvc** [comment] 2015-01-24 18:43
==> Merged

**Closed** 2015-01-24 18:45 UTC
Labels: Accepted, Merged, QA - Unit Test Wanted
