### ISSUE TITLE
use mathjax3 in andriod5 show error "getExplicit of null"

### ISSUE THREAD

**Issue by Daisy1213** [mathjax/MathJax#3014] opened 2023-03-08 07:43 UTC
**Replace the text below with the details of the issue you are facing.  
DO NOT simply erase the form and type a free-form response.**
-----

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. If
suitable, include the steps required to reproduce the bug.

### Steps to Reproduce:

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 3.2
* Client OS: Mac OS X 11.5.2

I am using the following MathJax configuration:

``` js
  window.MathJax = {
    chtml: {
      matchFontHeight: false,
      mtextInheritFont: false
    },
    options: {
      renderActions: {
        addMenu: [],
        checkLoading: []
      },
      skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code', 'a'],
      includeHtmlTags: {
        br: '\n',
        wbr: '',
        '#comment': ''
      },
      ignoreHtmlClass: 'tex2jax_ignore',
      processHtmlClass: 'tex2jax_process'
    },
    tex: {
      inlineMath: [['<latex>', '</latex>'], ['$', '$'], ['_mathjax_','_mathjax_'], ['$','$'], ['$$','$$'], ['\\(','\\)']],
      displayMath: [],
      macros: {
        ykparallelogram: '\\unicode{x25B1}',
        ykparallel: '//'
      },
      autoload: {
        color: [],
        colorV2: ['color']
      },
      packages: {
        '[+]': ['trap-undefined'],
        '[-]': ['noundefined']
      }
    },
    loader: {
      load: ['[tex]/noerrors']
    },
    startup: {
      ready: function () {
        var tex = null;

        var Configuration = MathJax._.input.tex.Configuration.Configuration;
        var TexError = MathJax._.input.tex.TexError.default;
        Configuration.create('trap-undefined', {
          fallback: {
            macro: function (parser, cs) {
              tex.inputData.codecogs = true;
            },
            environment: function (parser, env) {
              tex.inputData.codecogs = true;
            }
          }
        });

        var toDOM = function (math, node, html) {
          this.setDocument(html);
          if (math.inputData.codecogs) {
            var adaptor = html.adaptor;
            if (math.display) adaptor.setAttribute(node, 'display', true);
            var imageNode = adaptor.node('img', {
              src: 'https://gallery.fbcontent.cn/latex?decode=false&fontSize=34&latex=' + encodeURIComponent(math.math.trim() + '\\quad'),
              alt: tex.math.trim()
            })
            imageNode.onload = function () {
              imageNode.style.height = imageNode.naturalHeight / 2 + 'px'
              imageNode.style.width = imageNode.naturalWidth / 2 + 'px'
            }
            html.adaptor.append(node, imageNode);
            math.display = null;
          } else {
            this._toDOM(math, node, html);
          }
        };

        var getOutputJax = MathJax.startup.getOutputJax;
        MathJax.startup.getOutputJax = function () {
          var output = getOutputJax();
          output._toDOM = output.toDOM;
          output.toDOM = toDOM;
          return output;
        }

        MathJax.startup.defaultReady();

        MathJax.startup.input[0].preFilters.add(function (filter) {
          var math = filter.math
          tex = math
        });

        MathJax.startup.output._toDOM = MathJax.startup.output.toDOM;
        MathJax.startup.output.toDOM = toDOM;

      }
    }
  }

```

and loading MathJax via

``` html
<script src="https://solar.fbcontent.cn/h5/solar-web-mathjax3/es5/tex-chtml.js"></script>
```

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and include them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

**Comment by netw0rkf10w** [comment] 2023-03-08 10:32
I encountered the same issue on my forum. Please help @dpvc !!!

Steps to reproduce: Please visit https://diendantoanhoc.org, on the bottom left of the page, click on "Thay giao diện" and select "Beta" (c.f. screenshot below), which is the theme that uses MathJax v3.

<img width="320" alt="theme" src="https://user-images.githubusercontent.com/8569515/223689553-b988256a-dcf4-488c-8d52-1c986d19b434.png">

Thank you so much in advance for your help!

**Comment by dpvc** [comment] 2023-03-08 13:24
@netw0rkf10w, your web page has replaced the native `Array.from()` method with an alternative that is not fully compatible with the native one, and this means that MathJax's use of `Array.from()` doesn't work as it should.

It appears that there is a script that is loading an `index.php` file that seems to include `Prototype.js` version 1.7.1 that is replacing the `Array.from()` with the broken one.  This version is more than 10 years old, and even the current version of 1.7.3 is 8 years old, so this project is not being maintained.  Modifying the native functions like Prototype.js does is considered a bad idea, as it causes exactly the types of issues you are facing here.

It may be that moving to version 1.7.3 will provide a better `Array.from()` implementation, so trying that might be the first step.  Otherwise, you will need to either modify Prototype.js to not modify `Array.from()`, or drop it entirely.  I suspect you no longer need it, as a lot has changed in the last 8 (or 10) years.  There are better libraries, such as `polyfill.io` that you may be able to use instead to support older browsers.

In any case, this is not MathJax's error, but is due to overriding the native `Array.from()` function.

**Comment by dpvc** [comment] 2023-03-08 14:24
See also my earlier [comment](https://github.com/mathjax/MathJax/issues/2810#issuecomment-999066606) on a similar issue.

**Comment by netw0rkf10w** [comment] 2023-03-08 21:37
@dpvc Thank you so much for your reply!

Indeed, the website uses prototype 1.7.1 and this occurs at multiple places:

- The script on our server: https://diendantoanhoc.org/public/js/3rd_party/prototype.js, which is extensively used in the source code of the website.

- Doing a string search in the source code, I found that two other scripts are also included in some files: `https://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js` and `https://ajax.googleapis.com/ajax/libs/prototype/1.7/prototype.js`.

I have checked the implementation of `Array.from` of the 3 above `.js` and compared them with the one from the 1.7.3 version: `https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js`, and it seems to me that **their implementations are identical**:

```javascript
Array.from = $A;
```

where `$A` is defined by:
```javascript
function $A(iterable) {
  if (!iterable) return [];
  if ('toArray' in Object(iterable)) return iterable.toArray();
  var length = iterable.length || 0, results = new Array(length);
  while (length--) results[length] = iterable[length];
  return results;
}
```

Am I missing something?

I have also tried replacing prototype.js on the server with the 1.7.3 version, and also replacing all `https://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js` and `https://ajax.googleapis.com/ajax/libs/prototype/1.7/prototype.js` instances with `https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js`, but this broke the website (`Failed to load resource: the server responded with a status of 500 ()`). I guess I'll have to stick with MathJax 2.7 for the moment...

**Comment by dpvc** [comment] 2023-03-08 22:26
> it seems to me that their implementations are identical:

OK, I did say "it *may* be ..." so it seems that their `Array.from` has never been fixed.  Of course, they stopped working on it in 2015.

One possible solution would be to modify the local copy to make 

``` js
Array.from = $A;
```

be

``` js
if (!Array.from) Array.from = $A;
```

instead.  You would also have to replace the calls to `ajax.googleapis.com` to ones that load your local version.  Perhaps that will work for you?

**Comment by netw0rkf10w** [comment] 2023-03-08 22:26
Simply replacing `if (!Array.from) Array.from = $A;` works!

**Comment by dpvc** [comment] 2023-03-08 22:27
Great, glad that works.

**Comment by netw0rkf10w** [comment] 2023-03-08 22:29
Haha we commented exactly at the same time! :D
I did exactly as you described in your comment above: replacing all calls to `ajax.googleapis.com` with the local version in which I replaced `Array.from = $A;` with `if (!Array.from) Array.from = $A;` as you suggested in https://github.com/mathjax/MathJax/issues/2810#issuecomment-999066606, and it worked!

Thank you so so much again!!!!

**Comment by dpvc** [comment] 2023-03-08 22:31
> Haha we replied exactly at the same time! :D

Yes, that was funny!

I'm glad you have it working now.

I'm going to close the issue.

**Closed by dpvc** 2023-03-08 22:31 UTC
Labels: Expected Behavior, Upstream, v3

**Comment by Daisy1213** [comment] 2023-03-09 09:16
oh, I check my polyfill.js , It's not the same thing.
please help me review this file: https://xyst.yuanfudao.com/h5/solar-web-resultspage/polyfill.js
