### ISSUE TITLE
symbol on top of other symbol (hat, tilde, vec) puts it in superscript position in Safari

### ISSUE THREAD

**Issue by mbakker7** [mathjax/MathJax#1913] opened 2018-01-23 10:47 UTC
The functions $\hat{x}$, $\tilde{x}$, $\vec{x}$ put the hat, tilde and vector in the superscript position rather than on top in a markdown cell. See, for example, http://data-blog.udacity.com/posts/2016/10/latex-primer/

Strangely enough $\widehat{h}$ does work and puts a (wide) hat on top of x. So why doesn't $\hat{x}$ do that?

I gut this problem with Jupyter Notebooks using mathjax. 

Problems occurs on Safari 11.0.1, but not when using Chrome on a Mac.  

Thanks, Mark

**Comment by pkra** [comment] 2018-01-23 11:39
Duplicate of https://github.com/mathjax/MathJax/issues/1737

**Comment by mbakker7** [comment] 2018-01-23 12:09
You are right. Sorry about that.

**Comment by dpvc** [comment] 2018-01-23 12:19
Note that the website you link to is using MathJax v2.7.1, and the issue was fixed in v2.7.2.  Updating to 2.7.2 should fix the problem.

**Comment by mbakker7** [comment] 2018-01-23 12:38
I only added the website as an easy example of the problem.
I use mathjax in Jupyter notebooks and I don't know how to update that.
Will investigate.

On Tue, Jan 23, 2018 at 1:19 PM, Davide P. Cervone <notifications@github.com

**Closed** 2018-06-27 20:08 UTC
Labels: Duplicate
