### ISSUE TITLE
Invisible font in SVG Rendering

### ISSUE THREAD

**Issue by Herst** [mathjax/MathJax#831] opened 2014-05-30 20:09 UTC
Odd issue, reproduced on latest Firefox on Windows (/edit: and Linux) with MathJax 2.3 and 2.4 on one website (but not e.g. the MathJax Play Area) using my bookmarklet:

Steps to reproduce:
1.) Go to http://www.informatik-forum.at/showthread.php?t=107276 (inofficial forum of my university, thread where I present my bookmarklet that brings MathJax power to there for those interested)
2.) In the first box after "Code:" you will see a bookmarklet, press F12 to go into the JS console and execute it there (interestingly no need to remove the "javascript:" prefix) (alternatively save it as a bookmarklet and then run it or use the unminimized code from the second box).
3.) The MimeTex-generated images will be replaced by MathJax-generated content. Change the rendering mode to SVG.
4.) Then it looks the following (at least for me):
![mj_svg_bug](https://cloud.githubusercontent.com/assets/1042176/3135541/bb6012ca-e834-11e3-8e81-72599e003b46.png)
(for CDN version now, for beta replace the domains in the bookmarklet code)

Like I said reproduced on latest Firefox on Windows 8.1 (and latest Ubuntu). Fine on latest Google Chrome and and IE11 on Win8.1 (although in former I get a probably unrelated bug with the zoom window albeit also just in SVG mode: ![mj_svg_zoom_bug](https://cloud.githubusercontent.com/assets/1042176/3135579/3789b554-e835-11e3-8a35-a423bd787016.png) [should I fill extra bug report?])

PS: Notice also the lonely Eszett ("ß") that plays a role in bug #826 but the bug doesn't show here because STIX has that character (I guess).

PPS: Feedback on my bookmarklet is always appreciated.

**Comment by pkra** [comment] 2015-03-04 16:33
I cannot reproduce the OP with 2.5.1. @Herst can you?

I'll create a separate bug for the about box issue.

**Comment by Herst** [comment] 2015-03-06 20:54
@pkra Yes I can. Same procedure as described in the first post: ran Bookmarklet from there, changed to SVG and voila! (Firefox 37b2, with some add-ons and not a clean profile though)

**Comment by pkra** [comment] 2015-03-06 22:06
Strange. Now I see the problem again. I could swear it was working 2 days ago... bummer.

**Comment by episodeyang** [comment] 2015-08-08 05:20
I'm running into the same problem.

**Comment by Herst** [comment] 2015-08-10 07:38
@episodeyang With a different testcase? If yes then please share it with us.

**Comment by pkra** [comment] 2016-02-04 12:25
This has come up on the Readium tracker, https://github.com/readium/readium-js-viewer/issues/394#issuecomment-179794692 but specific to Microsoft Edge. That also makes it tied to xhtml.

**Comment by pkra** [comment] 2016-02-17 20:06
I finally have an up-to-date copy of Edge that exhibits the problem. 

For Edge, this is related to the font/path caching. While disabling the global cache seem to make no difference, disabling the local cache seems to fix the problem.

cc @dvpc

**Comment by pkra** [comment] 2016-02-17 20:07
Side note: this was working on Edge until version 20.xxx but isn't now in 25.xxx. We should check for a bug upstream or file one.

**Comment by pkra** [comment] 2016-02-17 20:15
@Herst if you still see the problem, try the following in the console

```javascript
MathJax.Hub.config.SVG.useFontCache = false;
MathJax.Hub.Queue(["Rerender", MathJax.Hub]);
```

or set `useFontCache: false` in the [SVG output configuration](http://docs.mathjax.org/en/latest/options/SVG.html).

**Comment by pkra** [comment] 2016-02-18 19:27
The Readium folks to the rescue. It seems the problem is due to the use of a `<base>` tag and the MathJax SVGs using relative url's in the `use` elements (which resolve incorrectly due to the `base` tag). 

The page linked to in the OP also uses the `base` tag, so it's likely the same issue. But obviously Edge just changed its behavior in 25.

This can be worked around by using absolute links, so perhaps we could detect the `base` tag and change the SVG output to absolute links. (Or we could jump ahead, e.g., in 3.0, and just use [this approach](https://css-tricks.com/svg-use-external-source/))

**Comment by dpvc** [comment] 2016-02-22 16:05
The `issue831` branch of my fork of MathJax includes a patch that uses full URLs for the `<use>` elements when there is a `<base>` tag in the page.  The xlink references get pretty ugly in this case, but I guess it is better (in most cases) than duplicating the paths.  I'm not sure if this will work with a URL that includes query parameters (i.e., that ends with `?...`).  In such cases, the only solution is to set `useFontCache:false` in the `SVG` section of the MathJax configuration, so that no xlink references will be made.

@herst, you could probably make your bookmarklet configure SVG with `useFontCache:false` (or do so only when there is a `<base>` element), which would get around the problem for now.

**Comment by dpvc** [comment] 2016-05-17 15:25
==> Merged.

**Closed** 2016-05-17 15:25 UTC
Labels: Accepted, Merged, Test Not Needed
