### ISSUE TITLE
[v3] Math in Blogspot comment ruins whole math in blog post

### ISSUE THREAD

**Issue by jfcg** [mathjax/MathJax#2253] opened 2019-12-04 09:00 UTC
I am using MathJax v3 on my [blog](https://thuum7.blogspot.com/2019/11/most-efficient-bucket.html) (no polyfill) with:
```
<script async id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```
Everything works great (thanks!) until I try math in comments. Then the whole math rendering in the blog post gets ruined after posting the comment:
![blog](https://user-images.githubusercontent.com/1410597/70127931-1236c300-168d-11ea-8321-2dec37a1349f.jpg)
I am not sure if this is a MathJax bug or a Blogspot bug. I reported the problem to Blogspot via their Send Feedback feature, did not get a reply yet.
Thanks..

**Comment by jfcg** [comment] 2019-12-04 11:40
v2.7 [seems](https://kristerw.blogspot.com/2016/07/using-mathjax-in-blogger.html) to work on blogspot comments

**Comment by dpvc** [comment] 2019-12-04 17:21
When the page changes (e.g., new math has been added), Blogspot needs to call MathJax to re-render the updated material.  It looks like the whole page is being replaced in your case.

The way that that is done has changed between version 2 and version 3, so Blogspot probably needs to be updated in order to work with MathJax v3.  There is an [example](http://docs.mathjax.org/en/latest/upgrading/v2.html#version-2-compatibility-example) in the MathJax documentation (at the bottom of the linked section) that might be able to be used to cover the v2 calls to the v3 calls, if Blogspot isn't doing anything too sophisticated.

**Comment by dpvc** [comment] 2019-12-04 17:22
Check the browser console to see if there are any error messages from MathJax-related calls.  That might tell you what MathJax functions Blogspot is using.

**Comment by jfcg** [comment] 2019-12-06 13:46
I get an error about a "splitText":
![blog2](https://user-images.githubusercontent.com/1410597/70327438-df84fa00-1847-11ea-9b3e-c1495cce4e8d.jpg)

**Comment by dpvc** [comment] 2019-12-09 13:51
OK, this is probably issue #2202, which will be fixed in the next release.  It is caused by math directly following a `<br>` in the HTML for the page.  Can you check if that is the case for your page?  It looks like your comment has a line break rather than a paragraph break before the displayed math; try using a blank line rather than just a line break.  Or try adding a space before the dollar signs (as even a space is enough to get around the bug).

**Comment by jfcg** [comment] 2019-12-09 19:33
putting a space before $$ in the comment seems to fix the rendering..

**Comment by dpvc** [comment] 2019-12-10 01:48
Great!  Thanks for letting us know.  I'm going to mark this as a duplicate since that what #2202 takes care of.

**Closed** 2019-12-30 13:45 UTC
Labels: Duplicate

**Comment by sofia5334** [comment] 2020-04-14 08:47
I really loved reading your blog. It was very well authored and easy to understand. Your blog put really very helpful information. Thank you for sharing superb information…
[Custom Packaging Boxes](https://www.thecustomboxesprint.us/)
