### ISSUE TITLE
MathJax2.5 and Chrome Version 48.0.2564.97 m issue

### ISSUE THREAD

**Issue by madhu-panisetty** [mathjax/MathJax#1367] opened 2016-02-01 06:24 UTC
Hi,

MathJax 2.5 is having issue with latest chrome Version 48.0.2564.97 m.
All expressions has a span with line at the end.
![mathjax2 5 and chrome version 48 0 2564 97 m issue](https://cloud.githubusercontent.com/assets/5527503/12710215/5db93e8e-c8da-11e5-83e7-211236491bc4.PNG)

Please check [https://jsfiddle.net/j56pkrq9/1/](https://jsfiddle.net/j56pkrq9/1/)

This is fine with MathJax 2.1 and also with latest 2.6, but having issue with 2.5 only and only with latest chrome.

Please do not ask to use 2.6 as this involves lot of our content need to be re-verified. Please suggest a solution.

Thank you,
Madhu

**Comment by pkra** [comment] 2016-02-01 08:14
Duplicate of https://github.com/mathjax/MathJax/issues/1300

**Closed** 2016-02-21 20:55 UTC
Labels: Duplicate
