### ISSUE TITLE
README "Installation and Usage" is incorrect/outdated

### ISSUE THREAD

**Issue by cmcfarla** [mathjax/MathJax#1331] opened 2015-12-09 11:26 UTC
README.md currently says:

> The MathJax installation and usage documentation is available in the docs/html directory of the MathJax distribution (see docs/html/index.html for the starting point). The documents are also available on the MathJax web site on line at http://www.mathjax.org/resources/docs/.

On inspection though, docs/html just has an HTML file saying that the documentation is no longer included. Also, the URL mentioned in README.md (i.e. http://www.mathjax.org/resources/docs/ ) returns a 404 which said "404 - Allow us to redirect you." and then failed to redirect me to anything with my default browser configuration. After changing my configuration, I found it would have taken me to the www.mathjax.org landing page rather than docs.mathjax.org if it had worked.

It appears that http://docs.mathjax.org/en/latest/start.html contains the current getting started information. If this is indeed the most up-to-date URL, could you please update the README to include it and remove the outdated information?

**Comment by pkra** [comment] 2015-12-09 11:30
This a duplicate of #1160 which is fixed in `develop`

**Closed by pkra** 2015-12-09 11:30 UTC
Labels: Duplicate
