### ISSUE TITLE
MathJax entirely wedges if set to impossible rendering backend

### ISSUE THREAD

**Issue by saurik** [mathjax/MathJax#1347] opened 2016-01-07 05:01 UTC
I have a friend who set his iPython Jupyter to use MathML rendering, but he is using Chrome, which doesn't have native MathML. This caused MathJax to wedge and never render anymore, which made him unable to access the menu to switch back to another renderer from MathML. We spent an hour, and tracked it down to this code, which attempts to get the id of the preferred renderer.

```JavaScript
  Menu: function () {
    var menu = MathJax.Hub.config.menuSettings, jax = MathJax.Hub.outputJax, registered;
    for (var id in jax) {if (jax.hasOwnProperty(id)) {
      if (jax[id].length) {registered = jax[id]; break}
    }}
    if (registered && registered.length) {
      if (menu.renderer && menu.renderer !== registered[0].id)
        {registered.unshift(MathJax.OutputJax[menu.renderer])}
      menu.renderer = registered[0].id;
    }
  },
```

https://github.com/mathjax/MathJax/blob/0715ef97f8328f80cb1b4bc3a35e64cdd47678e5/unpacked/MathJax.js#L2648

The problem is that ```MathJax.OutputJax[menu.renderer]``` is undefined, as there is no NativeMML support. This undefined value gets unshifted to the beginning of the array, and then ```registered[0].id``` tries to get the id property of undefined, which throws an exception. This exception splits a Suspend/Resume pair elsewhere in the code, which "wedges" the renderer.

FWIW, I can also see an argument for doing something about the code that is capable of wedging, which is the disconnected Suspend/Resume: this pattern is to me screaming for a try/finally block. (Though maybe there's some internal state that is also not exception safe. I'm really used to going extremely out of my way to use exceptions and be exception safe, but I don't know if this project does.)

```JavaScript
    Process: function (queue) {
      while (!this.running && !this.pending && this.queue.length) {
        var callback = this.queue[0];
        queue = this.queue.slice(1); this.queue = [];
        this.Suspend(); var result = callback(); this.Resume();
        if (queue.length) {this.queue = queue.concat(this.queue)}
        if (ISCALLBACK(result) && !result.called) {WAITFOR(result,this)}
      }
    },
```

```JavaScript
this.Suspend();
try {
    var result = callback();
} finally {
    this.Resume();
}
```

https://github.com/mathjax/MathJax/blob/0715ef97f8328f80cb1b4bc3a35e64cdd47678e5/unpacked/MathJax.js#L488

**Comment by pkra** [comment] 2016-01-11 14:16
Could you share a minimal live sample exhibiting the problem, e.g., on nbviewer? Also, any errors from the console, `MathJax.Hub.lastError` etc might be helpful.

**Comment by dpvc** [comment] 2016-01-11 17:26
I also can not reproduce the problem (though I don't use Jupyter).  The fact that Chrome doesn't have native MathML support should not cause MathJax to fail even if NativeMML has been selected as the renderer.  The `MathJax.OutputJax[menu.renderer]` should be defined even though Chrome doesn't implement MathML natively.  In an earlier part of the MathJax setup code, the `menu.renderer` output jax should have been loaded, so the output jax for that renderer should be be available.  If it is not, then that suggests that the `menu.renderer` value is invalid to begin with (and so the output jax could not be loaded), or that the `menu.renderer` has been changed somewhere between that earlier code and the block you have listed.

The first of these is most likely, and should result in a message about on output jax not being able to be loaded (issue the command `MathJax.Message.Log()` in the browser console to see if there is such a message).  For example, if the configuration asks for `output/nativeMML` rather than `output/NativeMML` that could result in this error.  Or it could be that the cookie that stores this value contains an invalid value (try deleting the cookie to see if that is the case).

**Comment by milindsmart** [comment] 2016-02-01 19:12
I experienced a similar thing where I set my renderer to MathML, but in my case Anaconda Jupyter apparently doesn't even come with the nativeMML config files. The cookie was the issue... deleting the cookie reverted the renderer to HTML-CSS

**Comment by pkra** [comment] 2016-02-01 19:53
@milindsmart thanks for the additional information. Sounds like a Jupyter problem. Has anybody files an issue upstream?

**Comment by milindsmart** [comment] 2016-02-01 21:38
I could not find any other mention of this curious omission anywhere on the web. Also for context, I am running jupyter from Anaconda, don't know if that's relevant.

**Comment by dpvc** [comment] 2016-02-01 22:11
> Anaconda Jupyter apparently doesn't even come with the nativeMML config files

That is consistent with the result that you and the OP experienced (the selected output renderer can't be loaded).  They should either provide the full MathJax package, or disable the renderer menu (or at least the specific rendered that they don't provide).

@pkra, I'm thinking this should be marked as upstream.  It doesn't look like our problem.

**Comment by pkra** [comment] 2016-02-02 08:11
> I'm thinking this should be marked as upstream. It doesn't look like our problem.

cc @minrk do you have a suggestion where to file this upstream?

**Comment by pkra** [comment] 2016-02-02 08:17
Nevermind. I think https://github.com/jupyter/notebook/issues/1035 is at the right place.

**Comment by minrk** [comment] 2016-02-02 08:21
Looks like you found it, thanks for reporting! Continuing over there.

**Comment by pkra** [comment] 2016-02-02 10:43
As always: thanks @mrink!

**Comment by pkra** [comment] 2016-02-05 10:02
FYI, downstream issue was fixed.

**Closed by pkra** 2016-02-05 10:02 UTC
Labels: Cannot Reproduce
