### ISSUE TITLE
Matrices including fractions and parenthesis, strange rendering in MathJax 3

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2642] opened 2021-03-05 22:05 UTC
Bonjour,

In Chrome, Firefox, Edge, using MathJax 2.7.9, rendering is perfect for the following matrice
$$
  \begin{pmatrix}
    \dfrac{1}{2} & 0            \\
    0            & \dfrac{1}{2} \\
  \end{pmatrix}
$$

![matrice-frac-mathjax2](https://user-images.githubusercontent.com/50557334/110177888-efeaa280-7e05-11eb-8be7-c7e1101a1e34.png)
 
In Chrome, Firefox, Edge, using MathJax 3.1.2, rendering size is imprecise in the middle of the matrice (thiner)

![matrice-frac-mathjax3](https://user-images.githubusercontent.com/50557334/110178100-422bc380-7e06-11eb-8a31-b070581a124b.png)

Best regards

**Comment by dpvc** [comment] 2021-03-17 13:35
There is a pull request that I think may resolve the issue that will be part of the next release.  I am not able to reproduce the effect you are seeing, but these things tent to be size dependent, and may also be affected by other CSS on the page.

You don't say which output renderer you are using (CHTML or SVG), but I suspect it is CHTML. As an alternative, you could switch to the SVG output, which may produce more reliable results for you.

**Comment by dpvc** [comment] 2021-03-17 13:36
I'm marking as a duplicate, as I think the PR will take care of it.

**Comment by sqlpac** [comment] 2021-03-18 01:04
Thank you.

Sorry, indeed the full context has not been detailed : yes it is `chtml` and before submitting the case all custom CSS files and properties have been disabled in a test page for reproductibility.
Rendering is perfect when we switch to `tex-svg.js`. The number of affected pages is very low : we keep `chtml` output waiting for version 3.1.3.

Best regards

**Closed** 2021-04-27 20:22 UTC
Labels: Duplicate, Fixed, v3, v3.1
