### ISSUE TITLE
MathJax.tex2svg("\\iiiint") got TypeError: Cannot read property 'chars' of undefined in 3.0.5

### ISSUE THREAD

**Issue by qq240814476** [mathjax/MathJax#2476] opened 2020-07-22 11:11 UTC
In 3.0.0 it works well, but when i update 3.0.5, when i debug, I find a little bug in  `ts/output/common/Wrapper.ts`

```js
/**
     * @param {string} text     The text to turn into unicode locations
     * @param {string} variant  The name of the variant for the characters
     * @return {number[]}  Array of numbers represeting the string's unicode character positions
     */
    protected unicodeChars(text: string, variant: string = '') {
        let chars = unicodeChars(text);
        //
        //  Remap to Math Alphanumerics block
        //

        // Tip: this.font.getVariant(variant) sometimes will be undefined
here:         const map = this.font.getVariant(variant).chars;
it should be: const map = this.font.getVariant(variant)?.chars;
        if (map) {
            //
            //  Is map[n] doesn't exist, (map[n] || []) still gives an CharData array.
            //  If the array doesn't have a CharOptions element use {} instead.
            //  Then check if the options has an smp property, which gives
            //    the Math Alphabet mapping for this characger.
            //  Otherwise use the original code point, n.
            //
            chars = chars.map((n) => ((map[n] || [])[3] || {}).smp || n);
        }
        return chars;
    }
```

I will fix it, and commit a pr

the whole callstack like this:
```
Uncaught TypeError: Cannot read property 'chars' of undefined
    at l.y.unicodeChars (tex-mml-svg.js:formatted:21788)
    at l.p.placeChar (tex-mml-svg.js:formatted:1246)
    at l.toSVG (tex-mml-svg.js:formatted:27882)
    at c.p.addChildren (tex-mml-svg.js:formatted:1081)
    at c.toSVG (tex-mml-svg.js:formatted:25409)
    at p.addChildren (tex-mml-svg.js:formatted:1081)
    at p.c.toSVG (tex-mml-svg.js:formatted:25289)
    at h.p.addChildren (tex-mml-svg.js:formatted:1081)
    at h.p.toSVG (tex-mml-svg.js:formatted:1073)
    at h.toSVG (tex-mml-svg.js:formatted:25169)
    at L.typesetSVG (tex-mml-svg.js:formatted:9641)
    at L.processMath (tex-mml-svg.js:formatted:9593)
    at L.p.toDOM (tex-mml-svg.js:formatted:21009)
    at L.p.typeset (tex-mml-svg.js:formatted:20983)
    at Q.T.typeset (tex-mml-svg.js:formatted:2969)
    at Object.renderMath (tex-mml-svg.js:formatted:9891)
    at d.renderConvert (tex-mml-svg.js:formatted:9951)
    at Q.T.convert (tex-mml-svg.js:formatted:2960)
    at e.w.convert (tex-mml-svg.js:formatted:10093)
    at Object.g.MathJax.<computed> [as tex2svg] (tex-mml-svg.js:formatted:36306)
    at <anonymous>:1:9
```

**Comment by dpvc** [comment] 2020-07-22 13:54
This is a duplicate of #2402, which is fixed in PR mathjax/MathJax-src#498.

**Closed** 2020-08-14 17:37 UTC
Labels: Duplicate, v3
