### ISSUE TITLE
spacing in second equation column in align

### ISSUE THREAD

**Issue by Alex-Jordan** [mathjax/MathJax#1722] opened 2017-03-17 23:13 UTC
With this minimal example:

```
\begin{align*} -2&=-2& -4&=-4 \end{align*}
```

when I paste into this test site: 
https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html

there is something wrong with the second equation column. The minus sign on the left `-4` is processed as a subtraction sign instead of as a negative sign. This is not the behavior I see if I put this into a regular LaTeX document.

The MathML from MathJax is as below, where I have commented where I think the problem is:

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true" scriptlevel="0">
    <mrow class="MJX-TeXAtom-ORD">
      <mtable columnalign="right left right left right left right left right left right left" rowspacing="3pt" columnspacing="0em 2em 0em 2em 0em 2em 0em 2em 0em 2em 0em" displaystyle="true">
        <mtr>
          <mtd>
            <mo>&#x2212;<!-- − --></mo>
            <mn>2</mn>
          </mtd>
          <mtd>
            <mi></mi>
            <mo>=</mo>
            <mo>&#x2212;<!-- − --></mo>
            <mn>2</mn>
          </mtd>
          <mtd>
            <mi></mi>  <!-- I don't think this should be here. -->
            <mo>&#x2212;<!-- − --></mo>
            <mn>4</mn>
          </mtd>
          <mtd>
            <mi></mi>
            <mo>=</mo>
            <mo>&#x2212;<!-- − --></mo>
            <mn>4</mn>
          </mtd>
        </mtr>
      </mtable>
    </mrow>
  </mstyle>
</math>
```

**Comment by dpvc** [comment] 2017-03-17 23:23
This is actually a duplicate of #1690.  The extra `<mi></mi>` should only be added to even columns (but currently is added to any column other than the first).

**Comment by Alex-Jordan** [comment] 2017-03-18 01:18
Ah, I searched but couldn't hit the right combo of search terms to find this one. OK, thanks.

**Closed** 2017-04-25 09:27 UTC
Labels: Duplicate
