### ISSUE TITLE
ResetEquationNumbers

### ISSUE THREAD

**Issue by rylan** [mathjax/MathJax#1419] opened 2016-03-22 17:22 UTC
Calling ```MathJax.Hub.Queue( ["resetEquationNumbers", MathJax.InputJax.TeX] );``` on a page without tex can cause Error("Can't make callback from given data") to be thrown intermittently.

**Comment by dpvc** [comment] 2016-03-31 22:09
By "without TeX" do you mean one that doesn't load the TeX input jax, or one with no math notation in the page?

You also haven't said where this call is coming in your page, which could also make a difference.  For example, since the resetEquationNumbers method is part of the AMSmath extension, if it came before that extension is loaded, then that could account for it.

You also don't say what your configuration is.  Are you loading a combined configuration file (via `?config=...` on the script that loads `MathJax.js`), or doing an in-line configuration.  I think all the TeX-based combined configuration files load the AMSmath extension, so that suggests you are doing a configuration by hand.  Do you load the AMSmath extension?  If so, is it in the TeX extensions array?

If it is in the TeX extensions array, that would mean that the extension isn't loaded until the main TeX jax is loaded, and the main TeX jax isn't loaded unless there is actual TeX notation on the page.

In this case, there are two possible solutions.  One would be to move the AMSmath extension to the main extensions array as in

```
MathJax.Hub.Config({
  extensions: ["TeX/AMSmath.js"]
});
```

which will force the extension to load at configuration time rather than during the typesetting phase, so the `resetEquationNumbers` would be available even when there is no TeX on the page.
 
Alternatively, you could use

```
if (MathJax.InputJax.TeX.resetEquationNumbers) MathJax.Hub.Queue(["resetEquationNumbers",MathJax.Hub]);
```

so that if the AMSmath extension hasn't run, you won't try to queue the call.

**Comment by dpvc** [comment] 2016-03-31 22:12
From MathJax's end, it would be possible to have a no-op `resetEquationNumbers` method in the `TeX/config.js` file that is overridden when the AMSmath extension is loaded, but I'm not sure that is really required, since testing for whether it exists is pretty straight-forward.

**Comment by pkra** [comment] 2016-04-01 07:15
@dpvc so this is `cannot reproduce`?

**Comment by dpvc** [comment] 2016-04-01 12:30
No, it can be reproduced under the right circumstances.  I just don't know which circumstances are the ones that pertain for this OP.  People using the combined configuration files that include the AMSmath extension (all the TeX) shouldn't experience this.

**Comment by rylan** [comment] 2016-04-01 13:20
@dpvc   Sorry, I should have been more detailed in my report. I do have the if-stmt guarding the call, my configuration is using ```TeX-AMS-MML_HTMLorMML,Safe```. The error I am seeing is intermittent, only on pages without Math, whether is MathML or Tex, ```MathJax.InputJax.TeX.resetEquationNumbers``` is present. The only calls after it are to 
```
MathJax.Hub.Queue(
			["PreProcess", MathJax.Hub],
			["Reprocess", MathJax.Hub]
		);
``` 

The pages it happens on are pages where there are lot of pieces dynamically popping into place causing lots of calls to my update function because their could be math in those pieces. Even then it does not happen all the time, so I am thinking it could be a weird timing thing, where MathJax is in a state that resetEquationNumbers is not expecting and just be caught and boiled up from that point.

**Comment by rylan** [comment] 2016-04-01 13:37
Oh @dpvc the docs also say to use ``` ["resetEquationNumbers",MathJax.InputJax.TeX]``` not ```MathJax.Hub.Queue(["resetEquationNumbers",MathJax.Hub]);```  http://docs.mathjax.org/en/v2.6-latest/advanced/typeset.html?highlight=resetequationnumbers  Just wondering if that is a typo or if the docs are out of date and the source of my problems>

**Comment by dpvc** [comment] 2016-04-01 14:26
@rylan, oops, you are right, it was a typo.  I've fixed the post above to use the correct `MathJax.InputJax.TeX`.

**Comment by dpvc** [comment] 2016-04-01 14:41
> I am thinking it could be a weird timing thing, where MathJax is in a state that resetEquationNumbers is not expecting

The error is saying that the callback could not even be created, so `resetEquationNumbers` isn't being called, so it hasn't to do with that routine specifically.  The only reasons that these would not be able to create a callback would be if either `MathJax.InputJax.TeX` wasn't defined, or if `MathJax.InputJax.TeX.resetEquationNumbers` was not a function.  If you are checking for the existence of `MathJax.InputJax.TeX.resetEquationNumbers`, then certainly `MathJax.InputJax.TeX` is an object, and unless you are overriding `resetEquationNumbers` (which I doubt), it should be a function.  So I don't know why this would not be able to make the callback.

The only thing I can think of is that the test for `MathJax.InputJax.TeX` uses `x instanceof Object`, and `instanceof` checks fail if `x` is not in the same document where MathJax was compiled.  So if you are using iframes or other nested documents, and called MathJax from the outer document in the inner one, you could get this kind of behavior.

You might try putting your `MathJax.Hub.Queue()` call in a `try/catch` structure and report the status of `MathJax.InputJax.TeX.resetEquationNumbers` in the `catch` to see what is going on at that time.  Something like

```
try {
  MathJax.Hub.Queue(["resetEquationNumbers",MathJax.InputJax.TeX]);
} catch (e) {
  console.log("Is an Object: " + (MathJax.InputJax.TeX instanceof Object));
  console.log("Method exists: " + (typeof MathJax.InputJax.TeX.resetEquationNumbers === "function"));
  throw e;
}
```

and see what gets reported.

**Comment by dpvc** [comment] 2016-05-04 12:47
The `issue1419` branch of my fork of MathJax makes sure `resetEquationNumbers()` is defined whenever the TeX input jax is loaded, even when there is no math on the page, and `AMSmath` isn't loaded.

**Comment by dpvc** [comment] 2016-05-11 21:23
==> Merged.

**Closed** 2016-05-11 21:23 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-09 00:10
==> In testsuite

LaTeXToMathML/issue1419.html
