### ISSUE TITLE
Bug: Italic instead of roman rendering of greek characters

### ISSUE THREAD

**Issue by balagge** [mathjax/MathJax#1995] opened 2018-05-17 15:55 UTC
### Issue Summary

Greek characters are displayed italic even if the `mathvariant` attribute is explicitly or implicitly set to `"normal"`.

Characters should be rendered italic by default if all of the following are true:
- the character is within an `<mi>` tag, **and**
- no explicit `mathvariant` attribute specified on the `<mi>` tag, **and**
- the identifier is **a single character**

**In any other case**, the rendering should use roman  (i.e. "upright") style.

References:
- https://www.w3.org/TR/MathML3/chapter3.html#id.3.2.3.2 (for `<mi>`)
- https://www.w3.org/TR/MathML3/chapter3.html#presm.commatt (for other tags)

### Steps to Reproduce

E.g. in the online demo version at https://www.mathjax.org/#demo the following MathML renders all 3 occurrences of the character 'mu'  incorrectly.

```
<math>
    <mi>&#x3BC;m</mi>
    <mo>&#x3BC;</mo>
    <mi mathvariant="normal">&#x3BC;</mi>
</math>
```

### Expected rendering

All occurrences of the letter 'mu' should be roman (upright):
(1) the `<mi>` tag contains more than a single character
(2) not an `<mi>` tag
(3) the `<mi>` tag explicitly contains a `mathvariant` attribute setting.

See the Firefox built-in renderer, which renders correctly.

### Actual rendering

All occurrences are rendered italic.

### Technical details

    MathJax Version: current demo version
    Client OS: Ubuntu 14.04
    Browser: Firefox / Chromium
    Renderer: HTML-CSS, Common HTML, SVG

Note: the preview HTML and the MathML renderer (if using Firefox) renders correctly.

**Comment by pkra** [comment] 2018-05-17 16:39
Duplicate of https://github.com/mathjax/MathJax/issues/1076

**Comment by pkra** [comment] 2018-05-17 16:40
See also https://github.com/mathjax/MathJax/issues/1859

**Closed** 2020-05-12 16:11 UTC
Labels: Duplicate
