### ISSUE TITLE
SVG output drops a non-breaking space in mtext

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1316] opened 2015-11-27 11:11 UTC
[From the User Group](https://groups.google.com/forum/#!topic/mathjax-users/Se2mxUysWtk).

The nbsp in `$\text{$x$ y}$` is lost but not in `$\text{$x$ y z}$`.  This only affects the SVG output.

**Comment by dpvc** [comment] 2015-11-27 13:09
Actually `\text{ x}` is sufficient to show the issue.

**Comment by poulter7** [comment] 2015-11-29 06:21
Hi Peter, Davide

I attempted to take a look at this issue. It seems like a problem with the old code adjusting the svg width, not having quite the desired effect here. I wasn't able to get the full test suite working from MathJax-Test, so I've not ran any regression.

**Comment by pkra** [comment] 2015-11-30 08:36
Thanks, Jonathan. Small warning: review will be a bit slow (end of year etc).

**Comment by poulter7** [comment] 2015-11-30 08:37
No problem 😊

**Comment by dpvc** [comment] 2015-12-02 20:01
@poulter7, It turns out that the real problem was severe lines lower, where nested groups are removed to simplify the SVG structure.  The spacing was being lost.  I've made a commit that fixes that problem rather than introduce the unneeded rectangle element.  See the commit listed above.

**Comment by poulter7** [comment] 2015-12-02 20:06
I'll check it out, thanks Davide

**Comment by dpvc** [comment] 2015-12-04 19:41
=> Merged.

**Closed** 2015-12-04 19:41 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2015-12-05 17:49
=> In testsuite

MathMLToDisplay/Presentation/TokenElements/mtext/issue1316.html
