### ISSUE TITLE
Wrong size of brackets

### ISSUE THREAD

**Issue by pzinn** [mathjax/MathJax#1977] opened 2018-04-07 01:51 UTC
Apologies if this has already been posted, but something that really bothers me.
The code below will produces { } of the wrong size. This bug seems to depend on lots of fine details (varying the number of lines below or the length of the text will erratically change the size of the { })

```
\[
\left\{\begin{array}{l}
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
  \vphantom{\big|}\verb!TESTTESTTESTTESTTESTTESTTESTTESTTEST!\\
\end{array}\right\}
\]
```

**Comment by dpvc** [comment] 2018-04-07 20:55
I am not able to reproduce the issue you are experiencing.  The braces are correct for me no matter how many lines there are or how long the text is.  Although you didn't mention which output renderer you are using, I could not produce a problem using any of HTML-CSS, CommonHTML, or SVG output.

Can you provide a link to a page that exhibits the problem for you?  Also, what browser and OS are you using?

One possible cause of problems could be other CSS on the page interfering with MathJax's layout.  Have you tried disabling any CSS files you re loading and seeing if that helps?

**Comment by pzinn** [comment] 2018-04-08 03:00
does seem like a CSS issue, but the problem is, this occurs for me both on the official page
https://www.mathjax.org/#demo
or in the linked jsbin.
for the record, I'm running linux, Google Chrome | 65.0.3325.181 (Official Build) (64-bit)

**Comment by dpvc** [comment] 2018-04-25 00:16
OK, I'm able to reproduce the issue using CommonHTML in Safari on Mac OS.

The problem is due to round-off issues when the various dimensions used in the elements that make up the brace are converted by the browser to the actual pixels on screen.  The positions and size are given in decimal parts of an em, and the browser has to match those to actual pixel positions and sizes.  How well this works depends on how close the requested positions and sizes are to integral pixel positions and sizes.  The results can change depending on the zoom level, for example, as well as other factors.

In this case, the braces are made up of 39 separate pieces, and a small difference in requested size to actual size can add up to a significant difference in actual size.  That appears to be what is happening here.  Note that zooming in or out can change the amount of discrepancy (it is even possible to have the result be too large at some zoom levels and too small at others, those that doesn't happen with this example).

The results are also dependent on how the browser does the rounding.  For example, in Firefox (on Mac OS), the results for your example are good at all zoom levels.  Since the CommonHTML output is the same for all browsers, and it is accurately displayed in Firefox, I take that to mean that the dimensions used in the placement are correct, and that it is the browser rounding that is causing WebKit to render the results poorly.

Resolving this issue would likely require a different approach to the way stretchy characters are generated in MathJax.  We are currently working on MathJax v3 and it does have a different approach that should prevent (or at least reduce) this type of problem.  But it is not yet ready for release.

**Comment by dpvc** [comment] 2022-03-11 15:29
This is fixed in v3.

**Closed by dpvc** 2022-03-11 15:29 UTC
Labels: Accepted, Browser Bug
