### ISSUE TITLE
Positioning of presub and presup (HTML-CSS, SVG output)

### ISSUE THREAD

**Issue by akotynski** [mathjax/MathJax#1200] opened 2015-06-05 14:38 UTC
When one of presub or presup have different width then smaller string is align to left instead of right (HTML-CSS and SVG output) 
Sample: https://jsfiddle.net/1va6y0xf/1/

Attachment shows NativeMML output in firefox (this one is correct):
![firefox_mml_demo](https://cloud.githubusercontent.com/assets/1667747/8007896/0cf21b18-0b9f-11e5-8123-9bf7e6299744.PNG)

**Comment by dpvc** [comment] 2015-06-05 14:41
This is a duplicate of #1072.  The fix is ready and will be included in v2.6.

**Closed** 2015-06-05 14:41 UTC
Labels: Duplicate
