### ISSUE TITLE
Backslash spacing causing equation to fail to display in Chrome

### ISSUE THREAD

**Issue by dlsun** [mathjax/MathJax#2227] opened 2019-10-29 15:52 UTC
This is a weird bug, as it only seems to happen in Chrome (latest version 78.0.3904.70, in incognito mode, no extensions), not in Safari. So I'm not sure if it's a bug with Chrome or a bug with MathJax. 

I discovered it while browsing another website that I do not own, and I was able to trace down the problem to the presence of backslashes in the LaTeX expression. The following minimal HTML example reproduces the problem:

```
<html>
  <head>
    <title>Minimal Example</title>
    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
  </head>

  <body>
    <p>Some text above</p>
    <p>An expression without backslashes: \(\frac{2}{2+x}\). An expression with backslashes: \(Y\ |\ X=x\)</p>
    <p>And some text below.</p>
  </body>

</html>
```

The expression without backslashes appears normally. The expression with backslashes appears briefly when initially rendered but then sinks down and out of view. 

Another observation, whose relevance is unclear to me: if I replace the `config=` with `TeX-MML-AM_CHTML`, then the expression seems to display fine.

**Comment by MrDarkHorse** [comment] 2019-10-29 16:31
I can confirm this same behavior for me.  Probably related to https://github.com/mathjax/MathJax/issues/2228

**Comment by dlsun** [comment] 2019-10-29 16:47
This seems like a bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1018526

**Comment by dpvc** [comment] 2019-10-29 16:50
It looks like Chrome is allowing line breaks to occur even within `<nobr>` or elements with `white-space:nowrap` set.  So that does seem to be a Chrome bug.  On the other hand, the other hand, the reason the breaking occurs is because MathJax has incorrectly set the width of a container element (it didn't take the scaling factor into account), so there is a MathJax bug as well.

This is specific to the HTML-CSS output, so if you switch to CommonHTML or SVG, it will work properly.

**Comment by dpvc** [comment] 2019-11-08 02:03
I'm no longer able to reproduce the big with latest version of Chrome.  Is anyone still seeing it?

**Comment by dlsun** [comment] 2019-11-08 02:08
This MathJax bug was caused by the following Chrome bug, whose patch was pushed early, after feedback from users: https://bugs.chromium.org/p/chromium/issues/detail?id=1017465

**Comment by dpvc** [comment] 2019-11-08 02:09
OK, thanks, @dlsun.

**Comment by dpvc** [comment] 2019-12-30 13:47
I;'m closing this issue, since it is fixed in Chrome.

**Closed by dpvc** 2019-12-30 13:47 UTC
Labels: Accepted, Ready for Development, Upstream
