### ISSUE TITLE
MathJax can't find its script tag in XHTML if XHTML tags use an explicit prefix

### ISSUE THREAD

**Issue by sdh4** [mathjax/MathJax#1016] opened 2015-01-22 04:46 UTC
If I create an xhtml page that uses explicit prefixes on the html tags, MathJax's code for finding its `<script>` tag fails. There also seems to be a similar issue with the `<head>` tag. 

Test case:
```html
<html:html xmlns:html="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
  <html:head>
    <html:script type="text/javascript" src="MathJax/MathJax.js?config=default"/>
    <html:title>test</html:title>
  </html:head>
  <html:body>
    <html:h1>This is a test</html:h1>
    <html:div>
      Here is an equation: \( x=5 \)
    </html:div>
  </html:body>
  
</html:html>
```

Expected results: Correctly render the equation x=5
Actual results: No rendering  (tested with Firefox 35)

The issue can be worked around by 
  * removing the namespace prefix from the `<head>` and `<script>` tags, or
  * Modifying MathJax.js to use getElementsByTagName("html:script") instead of getElementsByTagName("script"), and similarly getElementsByTagName("html:head") in place of getElementsByTagName("head")

**Comment by pkra** [comment] 2015-01-22 08:21
I cannot reproduce this. Are you serving the xhtml file with the correct mimetype?

**Comment by dpvc** [comment] 2015-01-22 14:16
I can reproduce it (on a local document with extension `.xhtml`) in Firefox, though it works as expected in Safari and Chrome.  I haven't tried IE.  Yes, having namespaces on those element can be problematic.  

It's not actually the script tags that are the problem (since these are created without namespaces by the `tex2jax` preprocessor, and so will be found by `getElementsByTagName()`), it is the document head that is the problem (MathJax isn't even getting to the place where it looks for the script tags).  I guess MathJax could use `document.head` when available and look it up otherwise (conveniently, `document.head` is set in Firefox even with the namespaces).

**Comment by dpvc** [comment] 2015-01-22 14:34
OK, I see, finding its own script tag is what you mean.  Yes, that is also a problem.  I'll think about that further.

**Comment by dpvc** [comment] 2015-01-22 15:10
The `issue1016` branch of my fork of MathJax includes the work-arounds that I suggest above.

**Comment by sdh4** [comment] 2015-01-22 15:52
This is not quite yet solving it for me, at least not on files served through the web server. 
My server, or the various transformations therein, put a `<!DOCTYPE html>` at the top of the document. So when document.getElementsByTagName("head")[0] on line 3041 gives a null, the fall-through creates HEAD from document.childNodes[0]. Unfortunately, document.childNodes[0] is the `<!DOCTYPE html>`, not the actual HEAD tag or any other meaningful tag, so namespaceURI is null and the problem is not solved. 

Possible fixes: 
   * hardwire the namespaceuri to the xhtml namespace "http://www.w3.org/1999/xhtml", and/or
   * Use the routine from line 644 to find the head

**Comment by dpvc** [comment] 2015-01-22 16:04
Oops, I thought I had caught them all.  See if the change I just made to the `issue1016` branch takes care of it for you.

**Comment by dpvc** [comment] 2015-01-22 16:55
Glad it worked.  Thanks for helping diagnose the problem, and checking the fixes.  I'll merge into the v2.5 candidate soon.

**Comment by dpvc** [comment] 2015-01-24 18:41
==> Merged.

**Comment by dpvc** [comment] 2015-01-24 18:42
It turns out the test suite can't be used to test this issue, due to the way that MathJax is injected into the page.

**Closed** 2015-01-24 18:42 UTC
Labels: Accepted, Merged, QA - Do Not Write Automated Test
