### ISSUE TITLE
Invalid characters appearing against braces

### ISSUE THREAD

**Issue by meetrij** [mathjax/MathJax#2291] opened 2020-01-13 09:46 UTC
When I try to use this equation from word document
![image](https://user-images.githubusercontent.com/51752377/72244980-6a120380-3615-11ea-98bb-5d291f90570f.png)
It's MathML format is given below

`<mml:math xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><mml:mi>f</mml:mi><mml:mfenced separators="|"><mml:mrow><mml:mi>x</mml:mi></mml:mrow></mml:mfenced><mml:mo>=</mml:mo><mml:mfenced open="{" close="" separators="|"><mml:mrow><mml:mtable><mml:mtr><mml:mtd><mml:mrow><mml:maligngroup/><mml:mfrac><mml:mrow><mml:msup><mml:mrow><mml:mfenced separators="|"><mml:mrow><mml:mi>x</mml:mi><mml:mo>+</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mfenced></mml:mrow><mml:mrow><mml:mn>2</mml:mn></mml:mrow></mml:msup><mml:mo>-</mml:mo><mml:mn>36</mml:mn></mml:mrow><mml:mrow><mml:mi>x</mml:mi><mml:mo>-</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mfrac><mml:mo>,</mml:mo><mml:mi>x</mml:mi><mml:mo>≠</mml:mo><mml:mn>3</mml:mn><mml:mi> </mml:mi></mml:mrow></mml:mtd></mml:mtr><mml:mtr><mml:mtd><mml:mrow><mml:maligngroup/><mml:mi>k</mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mo>,</mml:mo><mml:mi>x</mml:mi><mml:mo>=</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mtd></mml:mtr></mml:mtable></mml:mrow></mml:mfenced></mml:math>`

the result that I am getting using the mathjax plugin in application is like below
![image](https://user-images.githubusercontent.com/51752377/72245077-b2312600-3615-11ea-9cab-75c4905b2697.png)
an extra text "separators=|" coming along with equation
After that removed every equation except that curly brace again the text "separators=|" appears. Then I realized that it's the issue with braces

**Comment by dpvc** [comment] 2020-01-13 13:21
The MathML code you provide displays properly for me, so I am not able to reproduce your result.  Can you link to a page where you obtained your image?  What browser and OS are you using?  What version of MathJax?

It looks like `<mml:mfenced open="{" close="" separators="|">` is being treated as `<mml:mfenced open="{" close="separators=|">`.  Can you right-click on the math in your image and use "Show Math As MathML" and post the MathML code that appears?

**Comment by meetrij** [comment] 2020-01-14 11:32
Can't find any option on right click the html structure is shown below

`<span><span class="MathJax_Preview" style="color: inherit; display: none;"></span><span id="MathJax-Element-1-Frame" class="mjx-chtml MathJax_CHTML" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mi>f</mi><mfenced separators=&quot;|&quot;><mrow><mi>x</mi></mrow></mfenced><mo>=</mo><mfenced open=&quot;{&quot; close=&quot;separators=|&quot;><mrow><mtable><mtr><mtd><mrow><maligngroup /><mfrac><mrow><msup><mrow><mfenced separators=&quot;|&quot;><mrow><mi>x</mi><mo>+</mo><mn>3</mn></mrow></mfenced></mrow><mrow><mn>2</mn></mrow></msup><mo>-</mo><mn>36</mn></mrow><mrow><mi>x</mi><mo>-</mo><mn>3</mn></mrow></mfrac><mo>,</mo><mi>x</mi><mo>&amp;#x2260;</mo><mn>3</mn><mi>&amp;#xA0;</mi></mrow></mtd></mtr><mtr><mtd><mrow><maligngroup /><mi>k</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mi>&amp;#xA0;</mi><mo>,</mo><mi>x</mi><mo>=</mo><mn>3</mn></mrow></mtd></mtr></mtable></mrow></mfenced></math>" role="presentation" style="font-size: 113%; position: relative;"><span id="MJXc-Node-1" class="mjx-math" aria-hidden="true"><span id="MJXc-Node-2" class="mjx-mrow"><span id="MJXc-Node-3" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.501em; padding-bottom: 0.501em; padding-right: 0.06em;">f</span></span><span id="MJXc-Node-4" class="mjx-mfenced MJXc-space1"><span id="MJXc-Node-13" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.445em; padding-bottom: 0.611em;">(</span></span><span id="MJXc-Node-6" class="mjx-mrow"><span id="MJXc-Node-7" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.224em; padding-bottom: 0.279em;">x</span></span></span><span id="MJXc-Node-14" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.445em; padding-bottom: 0.611em;">)</span></span></span><span id="MJXc-Node-9" class="mjx-mo MJXc-space3"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.058em; padding-bottom: 0.335em;">=</span></span><span id="MJXc-Node-10" class="mjx-mfenced MJXc-space3"><span id="MJXc-Node-15" class="mjx-mo"><span class="mjx-char MJXc-TeX-size4-R" style="padding-top: 1.551em; padding-bottom: 1.551em;">{</span></span><span id="MJXc-Node-12" class="mjx-mrow"><span id="MJXc-Node-16" class="mjx-mtable" style="vertical-align: -1.378em; padding: 0px 0.167em;"><span class="mjx-table"><span id="MJXc-Node-17" class="mjx-mtr" style="height: 2.016em;"><span id="MJXc-Node-18" class="mjx-mtd" style="padding: 0px; width: 6.872em;"><span id="MJXc-Node-19" class="mjx-mrow"><span id="MJXc-Node-20" class="mjx-mrow"><span id="MJXc-Node-21" class="mjx-maligngroup"></span><span id="MJXc-Node-22" class="mjx-mfrac"><span class="mjx-box MJXc-stacked" style="width: 3.532em; padding: 0px 0.12em;"><span class="mjx-numerator" style="font-size: 70.7%; width: 4.995em; top: -1.857em;"><span id="MJXc-Node-23" class="mjx-mrow" style=""><span id="MJXc-Node-24" class="mjx-msup"><span class="mjx-base"><span id="MJXc-Node-25" class="mjx-mrow"><span id="MJXc-Node-26" class="mjx-mfenced"><span id="MJXc-Node-27" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.445em; padding-bottom: 0.611em;">(</span></span><span id="MJXc-Node-28" class="mjx-mrow"><span id="MJXc-Node-29" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.224em; padding-bottom: 0.279em;">x</span></span><span id="MJXc-Node-30" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.279em; padding-bottom: 0.445em;">+</span></span><span id="MJXc-Node-31" class="mjx-mn"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.39em; padding-bottom: 0.39em;">3</span></span></span><span id="MJXc-Node-32" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.445em; padding-bottom: 0.611em;">)</span></span></span></span></span><span class="mjx-sup" style="font-size: 70.7%; vertical-align: 0.71em; padding-left: 0px; padding-right: 0.071em;"><span id="MJXc-Node-33" class="mjx-mrow" style=""><span id="MJXc-Node-34" class="mjx-mn"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.39em; padding-bottom: 0.335em;">2</span></span></span></span></span><span id="MJXc-Node-35" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.279em; padding-bottom: 0.445em;">−</span></span><span id="MJXc-Node-36" class="mjx-mn"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.39em; padding-bottom: 0.39em;">36</span></span></span></span><span class="mjx-denominator" style="font-size: 70.7%; width: 4.995em; bottom: -0.681em;"><span id="MJXc-Node-37" class="mjx-mrow" style=""><span id="MJXc-Node-38" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.224em; padding-bottom: 0.279em;">x</span></span><span id="MJXc-Node-39" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.279em; padding-bottom: 0.445em;">−</span></span><span id="MJXc-Node-40" class="mjx-mn"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.39em; padding-bottom: 0.39em;">3</span></span></span></span><span class="mjx-line" style="border-bottom: 1.3px solid; top: -0.285em; width: 3.532em;"></span></span><span class="mjx-vsize" style="height: 1.795em; vertical-align: -0.482em;"></span></span><span id="MJXc-Node-41" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="margin-top: -0.163em; padding-bottom: 0.556em;">,</span></span><span id="MJXc-Node-42" class="mjx-mi MJXc-space1"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.224em; padding-bottom: 0.279em;">x</span></span><span id="MJXc-Node-43" class="mjx-mo MJXc-space3"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.445em; padding-bottom: 0.556em;">≠</span></span><span id="MJXc-Node-44" class="mjx-mn MJXc-space3"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.39em; padding-bottom: 0.39em;">3</span></span><span id="MJXc-Node-45" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span></span><span class="mjx-strut"></span></span></span></span><span id="MJXc-Node-46" class="mjx-mtr" style="height: 1.24em;"><span id="MJXc-Node-47" class="mjx-mtd" style="padding: 0.221em 0px 0px;"><span id="MJXc-Node-48" class="mjx-mrow" style="margin-top: -0.2em;"><span id="MJXc-Node-49" class="mjx-mrow"><span id="MJXc-Node-50" class="mjx-maligngroup"></span><span id="MJXc-Node-51" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.445em; padding-bottom: 0.279em;">k</span></span><span id="MJXc-Node-52" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-53" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-54" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-55" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-56" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-57" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-58" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-59" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-60" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-61" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-62" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-63" class="mjx-mi"><span class="mjx-char MJXc-TeX-math-I" style="margin-top: -0.218em; padding-bottom: 0.279em;">&nbsp;</span></span><span id="MJXc-Node-64" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="margin-top: -0.163em; padding-bottom: 0.556em;">,</span></span><span id="MJXc-Node-65" class="mjx-mi MJXc-space1"><span class="mjx-char MJXc-TeX-math-I" style="padding-top: 0.224em; padding-bottom: 0.279em;">x</span></span><span id="MJXc-Node-66" class="mjx-mo MJXc-space3"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.058em; padding-bottom: 0.335em;">=</span></span><span id="MJXc-Node-67" class="mjx-mn MJXc-space3"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.39em; padding-bottom: 0.39em;">3</span></span></span><span class="mjx-strut"></span></span></span></span></span></span></span><span id="MJXc-Node-68" class="mjx-mo"><span class="mjx-char MJXc-TeX-main-R" style="padding-top: 0.445em; padding-bottom: 0.611em;">separators=|</span></span></span></span></span><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>f</mi><mfenced separators="|"><mrow><mi>x</mi></mrow></mfenced><mo>=</mo><mfenced open="{" close="separators=|"><mrow><mtable><mtr><mtd><mrow><maligngroup></maligngroup><mfrac><mrow><msup><mrow><mfenced separators="|"><mrow><mi>x</mi><mo>+</mo><mn>3</mn></mrow></mfenced></mrow><mrow><mn>2</mn></mrow></msup><mo>-</mo><mn>36</mn></mrow><mrow><mi>x</mi><mo>-</mo><mn>3</mn></mrow></mfrac><mo>,</mo><mi>x</mi><mo>≠</mo><mn>3</mn><mi>&nbsp;</mi></mrow></mtd></mtr><mtr><mtd><mrow><maligngroup></maligngroup><mi>k</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mi>&nbsp;</mi><mo>,</mo><mi>x</mi><mo>=</mo><mn>3</mn></mrow></mtd></mtr></mtable></mrow></mfenced></math></span></span><script type="math/mml" id="MathJax-Element-1"><math xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><mml:mi>f</mml:mi><mml:mfenced separators="|"><mml:mrow><mml:mi>x</mml:mi></mml:mrow></mml:mfenced><mml:mo>=</mml:mo><mml:mfenced open="{" close="separators=|"><mml:mrow><mml:mtable><mml:mtr><mml:mtd><mml:mrow><mml:maligngroup></mml:maligngroup><mml:mfrac><mml:mrow><mml:msup><mml:mrow><mml:mfenced separators="|"><mml:mrow><mml:mi>x</mml:mi><mml:mo>+</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mfenced></mml:mrow><mml:mrow><mml:mn>2</mml:mn></mml:mrow></mml:msup><mml:mo>-</mml:mo><mml:mn>36</mml:mn></mml:mrow><mml:mrow><mml:mi>x</mml:mi><mml:mo>-</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mfrac><mml:mo>,</mml:mo><mml:mi>x</mml:mi><mml:mo>≠</mml:mo><mml:mn>3</mml:mn><mml:mi> </mml:mi></mml:mrow></mml:mtd></mml:mtr><mml:mtr><mml:mtd><mml:mrow><mml:maligngroup></mml:maligngroup><mml:mi>k</mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mo>,</mml:mo><mml:mi>x</mml:mi><mml:mo>=</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mtd></mml:mtr></mml:mtable></mml:mrow></mml:mfenced></math></script></span>`

Screenshot of the same above html structure via console

![image](https://user-images.githubusercontent.com/51752377/72341060-5dfa7480-36ef-11ea-9335-1cad0a60d555.png)

Front end is angular js so don't know if any conflict with curly braces exists or not, and is seen in every browser with latest version...

**Comment by dpvc** [comment] 2020-01-14 11:36
Can you link to the page you are using?  Screen shots are nice but not sufficient to diagnose the problem.

**Comment by meetrij** [comment] 2020-01-20 06:19
We cannot give it directly need authentication/authorization

**Comment by meetrij** [comment] 2020-01-20 12:18
That page requires authorization/authentication, so if you could give us an email id to which we can send you the URL plus credentials then that would be better.

**Comment by dpvc** [comment] 2020-01-21 15:58
You can obtain my email using the code snippet in [this StackOverflow post](https://stackoverflow.com/a/44229207/502334)using my userID here.  I'd rather not post it directly, but I doubt the robots will run the code listed there, while you will be able to do it with ease.

**Comment by dpvc** [comment] 2020-01-23 20:04
The actual MathML that appears in the page is the following:

```
<math xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><mml:mi>f</mml:mi><mml:mfenced separators="|"><mml:mrow><mml:mi>x</mml:mi></mml:mrow></mml:mfenced><mml:mo>=</mml:mo><mml:mfenced open="{" close="separators=|"><mml:mrow><mml:mtable><mml:mtr><mml:mtd><mml:mrow><mml:maligngroup></mml:maligngroup><mml:mfrac><mml:mrow><mml:msup><mml:mrow><mml:mfenced separators="|"><mml:mrow><mml:mi>x</mml:mi><mml:mo>+</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mfenced></mml:mrow><mml:mrow><mml:mn>2</mml:mn></mml:mrow></mml:msup><mml:mo>-</mml:mo><mml:mn>36</mml:mn></mml:mrow><mml:mrow><mml:mi>x</mml:mi><mml:mo>-</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mfrac><mml:mo>,</mml:mo><mml:mi>x</mml:mi><mml:mo>≠</mml:mo><mml:mn>3</mml:mn><mml:mi> </mml:mi></mml:mrow></mml:mtd></mml:mtr><mml:mtr><mml:mtd><mml:mrow><mml:maligngroup></mml:maligngroup><mml:mi>k</mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mi> </mml:mi><mml:mo>,</mml:mo><mml:mi>x</mml:mi><mml:mo>=</mml:mo><mml:mn>3</mml:mn></mml:mrow></mml:mtd></mml:mtr></mml:mtable></mml:mrow></mml:mfenced></math>
```

or better formatted:

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>f</mi>
  <mfenced separators="|">
    <mrow>
      <mi>x</mi>
    </mrow>
  </mfenced>
  <mo>=</mo>
  <mfenced open="{" close="separators=|">
    <mrow>
      <mtable>
        <mtr>
          <mtd>
            <mrow>
              <maligngroup />
              <mfrac>
                <mrow>
                  <msup>
                    <mrow>
                      <mfenced separators="|">
                        <mrow>
                          <mi>x</mi>
                          <mo>+</mo>
                          <mn>3</mn>
                        </mrow>
                      </mfenced>
                    </mrow>
                    <mrow>
                      <mn>2</mn>
                    </mrow>
                  </msup>
                  <mo>-</mo>
                  <mn>36</mn>
                </mrow>
                <mrow>
                  <mi>x</mi>
                  <mo>-</mo>
                  <mn>3</mn>
                </mrow>
              </mfrac>
              <mo>,</mo>
              <mi>x</mi>
              <mo>&#x2260;</mo>
              <mn>3</mn>
              <mi></mi>
            </mrow>
          </mtd>
        </mtr>
        <mtr>
          <mtd>
            <mrow>
              <maligngroup />
              <mi>k</mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mi></mi>
              <mo>,</mo>
              <mi>x</mi>
              <mo>=</mo>
              <mn>3</mn>
            </mrow>
          </mtd>
        </mtr>
      </mtable>
    </mrow>
  </mfenced>
</math>
```

Note that this includes `<mfenced open="{" close="separators=|">`, which says that the closing delimiter should be `separators=|`, which is how MathJax is displaying it.  You can see this in your screen shot above (that includes the DOM viewer).  So if your original MathML really includes `<mfenced open="{" close="" separators="|">`, then somewhere in your pipeline the attributes are getting mangled. 

So MathJax is properly rendering the MathML that it gets, but that MathML just isn't what you intend it to be.  You will have to look into your content management system and see where along the way the data is being corrupted.  But it is sometime before MathJax runs, so it isn't a MathJax error.

**Comment by meetrij** [comment] 2020-01-24 12:30
Okay, thank you for your assistance and quick responses...

**Closed** 2020-05-12 15:24 UTC
Labels: Expected Behavior
