### ISSUE TITLE
Arabic letters doesn't appear connected when using whole Arabic words

### ISSUE THREAD

**Issue by aboudzakaria** [mathjax/MathJax#1307] opened 2015-11-23 07:10 UTC
Arabic letters doesn't appear connected when using whole words (for example sin and cos should be جب and تجب in arabic but they're appearing like this ج ب and ت ج ب).

**Comment by pkra** [comment] 2015-11-23 09:53
This is a duplicate of https://github.com/mathjax/MathJax/issues/474

**Closed by pkra** 2015-11-23 09:53 UTC

**Comment by pkra** [comment] 2015-11-23 09:58
Maybe I closed too soon? #474 started out as a duplicate but focused more on the TeX input recently. I'd be ok if you prefer to reopen this.
