### ISSUE TITLE
[CommonHTML] regression on develop branch: horizontal stretch causes processing error

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1541] opened 2016-07-04 09:27 UTC
I ran into a regression on the develop branch.

Here's a minimal example. It seems to require the mtable and the mover (this came from an AMScd source).

```html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable rowspacing="5pt" columnspacing="5pt" displaystyle="true">
    <mtr>
      <mtd>
        <mi>F</mi>
      </mtd>
      <mtd>
        <mover>
          <mo minsize="2.75em">&#x2192;</mo>
        </mover>
      </mtd>
      <mtd> 
        <mi>F</mi>
      </mtd>
    </mtr>
  </mtable>
</math>
```

`lastError` gave me:

```console
TypeError: Cannot read property 'firstChild' of null
    at CHTMLstretchH (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1959:22)
    at CHTMLstretchCoreH (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1472:28)
    at CHTMLstretchH (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1704:14)
    at CHTMLstretchCoreH (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1472:28)
    at CHTMLstretchH (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1468:36)
    at CHTMLstretchCells (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/autoload/mtable.js?rev=2.6.1:422:55)
    at toCommonHTML (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/autoload/mtable.js?rev=2.6.1:71:12)
    at CHTMLaddChild (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1395:25)
    at CHTMLdefaultNode (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1380:42)
    at toCommonHTML (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:2604:21)
    at CHTMLaddChild (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1395:25)
    at CHTMLdefaultNode (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1380:42)
    at toCommonHTML (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:1733:21)
    at Translate (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:507:14)
    at Object.processOutput (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:2306:51)
    at Function.execute (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:236:26)
    at Function.WAITEXECUTE (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:337:31)
    at cb (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:218:59)
    at Function.WAITEXECUTE (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:341:50)
    at cb (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:218:59)
    at Execute (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:419:36)
    at Object.loadComplete (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:951:35)
    at Function.execute (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:236:26)
    at cb (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:218:59)
    at Process (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:488:38)
    at Push (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:478:49)
    at Init (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:463:17)
    at Function.Init (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:88:23)
    at Function.Queue (https://rawgit.com/mathjax/MathJax/develop/unpacked/MathJax.js:66:54)
    at fontLoaded (https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/jax.js?rev=2.6.1:334:24)
    at https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/fonts/TeX/AMS-Regular.js?rev=2.6.1:287:7
    at https://rawgit.com/mathjax/MathJax/develop/unpacked/jax/output/CommonHTML/fonts/TeX/AMS-Regular.js?rev=2.6.1:289:3
```

**Comment by dpvc** [comment] 2016-07-04 15:05
Of course, the MathML is invalid, because `<mover>` requires two children, but the issue is still present if you add a second child (as long as the base is stretchy).

It turns out that this is related tot he `getNode()` changes, and the main fix is to handle that better.  But there are also some issues with the stretching code not matching the element being stretched to the proper container DOM node (a problem in `CHTMLcoreNode()`, and an issue with `CHTMLaddChild()` not adding a box of the proper type when `forceChild` forces an empty element to be added.

**Comment by dpvc** [comment] 2016-07-04 15:06
The `issue1541` branch of my fork of MathJax includes fixes for all three issues.

**Comment by pkra** [comment] 2016-07-04 15:21
> Of course, the MathML is invalid, because <mover> requires two children

D'Oh! for overly minimizing my example without sanity checking it (though IIRC the HTML-CSS output handled it ok). Thanks for the quick fix!

**Comment by dpvc** [comment] 2016-07-04 15:26
Yes, both HTML-CSS and SVG handled the missing element OK.  With the patch, so does CommonHTML.

**Comment by dpvc** [comment] 2016-07-08 13:14
==> Merged

**Closed** 2016-07-08 13:14 UTC
Labels: Accepted, Merged, Test Needed

**Comment by dpvc** [comment] 2016-08-09 19:09
There are tests already in the testsuite that should catch this, so I'm marking as "Test Not Needed".
