### ISSUE TITLE
\class{className}{math} problem when math is \ref{} or \eqref{} 

### ISSUE THREAD

**Issue by parhizkari** [mathjax/MathJax#2224] opened 2019-10-21 16:51 UTC
If you use ```\class{className}{math}``` it works fine unless you apply it over ```\ref{}``` or ```\eqref{}``` inside a math environment. Doing so you will recieve a **Math output error**, substituting the whole math environment by:
```<span data-mjx-error="String contains an invalid character">Math output error</span>```
I am in linux, using firefox

**Comment by dpvc** [comment] 2019-10-24 16:23
I believe this is resolved by PR mathjax/MathJax-src#340, which will be in the next release of MathJax 3.

**Comment by dpvc** [comment] 2019-10-24 16:24
Duplicate of #2185 (though not readily apparent as the same problem).

**Comment by parhizkari** [comment] 2019-10-24 20:30
Thank you, I had seen those pages as I had also the same problem, but I couldn't guess they are the same; sorry for the duplication.

**Comment by dpvc** [comment] 2019-10-26 17:41
No problem.  It was not readily apparent.  The reason is that the `\ref` automatically adds a `MathJax_ref` class, so your additional class triggered the problem identified in #2185.

**Closed** 2019-12-30 13:48 UTC
Labels: Duplicate
