### ISSUE TITLE
Emtpy column separator @{} is ignored: arrays always have an extra space

### ISSUE THREAD

**Issue by jsmaniac** [mathjax/MathJax#1802] opened 2017-07-10 19:49 UTC
In the format specification for an array, the `@{}` separators is ignored, and the column sep is always inserted.

So far, I have not found any way to get two things on top of each other without extra space on the sides, short of patching with `\!` negative spaces: `array` and `matrix` add a bit of space on the left and a lot on the right, `aligned` and `split` add a lot of space on the left and a bit on the right, `\choose` adds some parentheses, `\arraycolsep=0pt` causes an error, the `@{}` column separator is ignored, `\substack` and `subarray` have extra spacing and change the font size, `\frac` draws a horizontal line and changes the font size… is there a way to produce a vertical superposition of two elements without adding any horizontal spacing, aside from using `\!` or a negative `\hspace` to shift things back into place?

HTML: https://jsfiddle.net/wdbngtxb/

![The "a" has an extra space on each side.](https://user-images.githubusercontent.com/299872/28036292-09c8c48a-65b8-11e7-8b7d-d12de2492b55.png)

```html
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: { inlineMath: [['$','$'],], },
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=default"></script>
<body>
  $x\begin{array}{@{}l@{}}a\end{array}y$
</body>
```

LaTeX document:

![With LaTeX, there is no extra space around the "a".](https://user-images.githubusercontent.com/299872/28036316-1ba55d94-65b8-11e7-9247-6172caca2f81.png)

```latex
\documentclass{article}
\begin{document}
$x\begin{array}{@{}l@{}}a\end{array}y$
\end{document}
```

**Comment by dpvc** [comment] 2017-07-10 20:24
MathJax only implements a ver limited subset of the array environment's preamble.  Basically, only the `l`, `r`, `c`, and `|` characters, plus `:` for dashed lines.  Everything else is ignored.

If you want to do a vertical stack, you could use `\atop`:

```
x{a\atop b}y
```

but this will reduce the fonts size.  If you want the text size use

```
x{\textstyle a\atop\textstyle b}y
```

These do insert the null delimiter space, however, though that is relatively small.

There is also the (non-standard)

```
x\vcenter{a\\b}y
```

which does not insert any extra space, but the spacing between the lines is a bit wider, and there is no easy way to reduce that.

There is also the rather complicated and ugly

```
x\vcenter{\mathord{\mathop{a}\limits_{\textstyle b}}}y
```

Perhaps one of those will help.

**Comment by dpvc** [comment] 2017-07-10 20:25
I'm marking this "expected behavior" because MathJax doesn't implement `@{}` in the array preamble.

**Comment by jsmaniac** [comment] 2017-07-10 20:41
I had seen in other places that `@{…}` was not supported, but didn't see any mention of it in the docs. Unless I missed it (which is quite likely, the docs are large), maybe this should be written somewhere? Especially the meaning or `:`, which I could not find anywhere and learned just now.

Otherwise, feel free to close this.

**Comment by jsmaniac** [comment] 2017-07-10 21:08
A quick note to say that `\vcenter{a\\b}` seems to gobble everything after it on the line when rendered in CommonHTML mode. Should I open a bug for this or is `\vcenter` not meant to be supported in CommonHTML mode?

https://jsfiddle.net/84a7yxkn/1/

`x\vcenter{a\\b}yzt` renders without the `yzt`:

![yzt is missing after the `a\\b`](https://user-images.githubusercontent.com/299872/28040038-b1805218-65c4-11e7-805a-d8aaa1c4f168.png)

**Comment by pkra** [comment] 2017-07-11 06:42
> `x\vcenter{a\\b}yzt` renders without the `yzt`:

It's actually there but far too the right. I've filed #1804

**Comment by dpvc** [comment] 2017-07-11 14:37
> maybe this should be written somewhere? 

I don't think it is listed anywhere.  Yes, it should be.

See issue #1804 for more details about `$x\vcenter{a\\b}y$`.  I was wrong to suggest it, and you should use one of the other approaches.

**Comment by pkra** [comment] 2017-08-31 08:09
I've filed https://github.com/mathjax/MathJax-docs/issues/205 for the docs. Closing this here as expected behavior.

**Closed by pkra** 2017-08-31 08:09 UTC
Labels: Expected Behavior, Needs Documentation
