### ISSUE TITLE
Math processing errors

### ISSUE THREAD

**Issue by zopyx** [mathjax/MathJax#1365] opened 2016-01-30 15:58 UTC
See tests 19+22

https://print-css.rocks/_static/lesson-mathml-torture-test/vivliostyle-output.pdf

Source is here

https://github.com/zopyx/css-paged-media-tutorial/tree/master/lesson-mathml-torture-test

**Comment by dpvc** [comment] 2016-01-30 16:12
This is a duplicate of #1360, which has been fixed and is scheduled for the 2.6.1 release.

**Closed by dpvc** 2016-01-30 16:12 UTC
Labels: Duplicate
