### ISSUE TITLE
TypeErrors on simple example

### ISSUE THREAD

**Issue by MatthewDaws** [mathjax/MathJax#2477] opened 2020-07-22 16:14 UTC
### Issue Summary

I am trying to learn MathJax 3, and have stumbled across a very simple example which causes a `TypeError` in the web console, and broken output.

### Steps to Reproduce:

The following is a minimal example which doesn't work.

    <html>
    <head>
        <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
    </head>

    <body>
    <p>Why not working: \( = \int \)</p>
    </body>

    </html>

Removing the `=` sign from the LaTeX code does work, printing correctly an integral sign.

Error message in Chrome console:

    Uncaught (in promise) TypeError: Cannot read property 'dataset' of undefined
    at Object.sre.DomUtil.getDataAttribute (sre_browser.js:135)
    at Object.sre.WalkerUtil.getAttribute (sre_browser.js:570)
    at sre.RebuildStree.makeNode (sre_browser.js:574)
    at sre.RebuildStree.assembleTree (sre_browser.js:572)
    at sre.RebuildStree.e (sre_browser.js:573)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (sre_browser.js:573)
    at sre.RebuildStree.e (sre_browser.js:573)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (sre_browser.js:573)

Similar but different error from Firefox.  I regret that I am not a javascript developer, and do not know where to start understanding the cause.

### Technical details:

* MathJax Version: As above, from cdn server
* Client OS: Windows 10
* Browser: Firefox 78.0.1 and Chrome 83.0.4103.116

**Comment by dpvc** [comment] 2020-07-22 16:19
Thanks for the report.  We will look into it.

It seems to be generated by MathJax's assistive technology tools, specifically the speech-rule engine (sre).  Have you turned on the assistive explorer, either in your configuration or through the MathJax contextual menu?  If so, does it work if you turn it off?

**Comment by dpvc** [comment] 2020-07-22 16:20
@zorkow, can you take a look at this issue?  I am able to reproduce it in the interactive lab.

**Comment by MatthewDaws** [comment] 2020-07-22 16:22
Re: assistive technology.  Yes!  I had indeed turned them on (I was trying to test ChromeVox in particular) and indeed turning them off stops the error.

**Comment by zorkow** [comment] 2020-07-22 17:18
SRE creates too much semantic structure, which it can't embed. 
I'll fix it for 3.1.

**Comment by dpvc** [comment] 2021-02-01 17:03
@zorkow, was this fixed in 3.1, and can I close the issue?

**Closed** 2022-03-11 18:23 UTC
Labels: Accepted, Upstream, v3, SRE
