### ISSUE TITLE
An issue with placing of superscript minus sign

### ISSUE THREAD

**Issue by samiiali** [mathjax/MathJax#1397] opened 2016-02-24 02:49 UTC
When I render `A_n^-`, the superscript minus sign, is not rendered at the correct position. One can compare `A^-` with `A_n^-`, to see this issue.

**Comment by pkra** [comment] 2016-02-24 12:17
Thanks for the report. I can reproduce this for HTML-CSS and SVG output; CommonHTML output seems ok so you might want to switch to that for a temporary workaround.

**Comment by dpvc** [comment] 2016-02-24 13:51
This is a duplicate of #1187.  See that post for some work-arounds.

**Comment by samiiali** [comment] 2016-02-24 14:05
I saw #1187 before submitting this issue. These are not similar issues (at least in the outcome). Here, when you do not have subscript, minus sign is rendered in the correct position. Also, if you have plus sign instead of minus sign it will be rendered correctly. By correctly, I mean superscript is really superscript when we have plus sign. With minus sign it is not even a superscript. So, the justification in #1187 about font metrics seems irrelevant here.

**Comment by dpvc** [comment] 2016-02-24 14:30
Trust me, it really is the same issue.  If you apply the patch suggested there, it will resolve the issue.  The problem with the metrics only affects the case where both scripts are present, and only when one is a minus.  If you look at the jsFiddle linked in the statement of the issue, you will see that minus in superscript or scrip script by itself is just fine, but when both super- and subscripts are present, it is not (his first two blocks of examples).  If you change those to pluses, everything is fine.  If you don't have a single-character base (his third block of examples, since the braces make it not just a single character anymore), everything is OK.  You situation is exactly his first two blocks of examples.  Try the solution there and see if that works for you.

**Comment by samiiali** [comment] 2016-02-24 15:19
I hereby confirm that, adding braces solves the issue ! So, for later reference, `A_n^-` is not OK, but `{A}_n^-` is OK. Thank you all !

**Closed** 2016-02-24 20:09 UTC
Labels: Duplicate
