### ISSUE TITLE
SVG jax not handling non-empty <maligngroup> and <malignmark> properly.

### ISSUE THREAD

**Issue by corinnaSchultz** [mathjax/MathJax#1233] opened 2015-08-05 22:37 UTC
I have not fully tracked down the root cause, but, I've gotten this far:

In the SVG/jax.js code, for BBOX.ROW.Stretch, it is possible for SVGstretchV to get called with an object instead of a number as the first argument. This will ultimately result in a y value of NaN in the resulting svg, and cause significant rendering errors. Perhaps, somewhere in the code path, mathJax should check for a valid value.

The object appears to contain font information. I'm not sure what produces it, or where it comes from, but the mathML that caused the problem contained unicode characters. When we converted the unicode characters into entity codes, the svg was renderer correctly.

One wrinkle in tracking down this problem, is that it seemed to make a difference what machine we were running this on. I didn't see it only Yosemite Mac, but saw it on the Linux server. Perhaps there's an OS difference, or something to do with installed fonts, or something else. I didn't track it down all the way. The server /proc/version output is:

    Linux version 2.6.32-504.1.3.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) )

This produced errors in the Javascript console about NaN values for y:

    <math xmlns="http://www.w3.org/2010/Math/MathML"><mrow><mrow><mo>(</mo><mn>2</mn><mo>)</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>[</mo><mn>4</mn><mo>]</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>{</mo><mn>6</mn><mo>}</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>〈</mo><mn>8</mn><mo>〉</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>|</mo><mn>10</mn><mo>|</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>⌈</mo><mn>12</mn><mo>⌉</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>⌊</mo><mn>14</mn><mo>⌋</mo></mrow><mo>,</mo><mtext></mtext><mrow><mo>‖</mo><mn>16</mn><mo>‖</mo></mrow></mrow></math>

This produced a correct svg:

    <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mstyle scriptsizemultiplier="0.715"><mrow><mrow><mo>(</mo><mrow><mn>1</mn></mrow><mo>)</mo></mrow><mo>,</mo><mrow><mo>[</mo><mrow><mn>2</mn></mrow><mo>]</mo></mrow><mo>,</mo><mrow><mo>{</mo><mrow><mn>3</mn></mrow><mo>}</mo></mrow><mo>,</mo><mrow><mo>&#x2329;</mo><mrow><mn>4</mn></mrow><mo>&#x232a;</mo></mrow><mo>,</mo><mrow><mrow><mo>|</mo><mrow><mn>5</mn></mrow><mo>|</mo></mrow><mo>,</mo><mrow><mo>&#x2308;</mo><mrow><mn>6</mn></mrow><mo>&#x2309;</mo></mrow><mo>,</mo><mrow><mo>&#x230a;</mo><mrow><mn>7</mn></mrow><mo>&#x230b;</mo></mrow><mo>,</mo><mrow><mo>&#x2016;</mo><mrow><mn>8</mn></mrow><mo>&#x2016;</mo></mrow></mrow></mrow></mstyle><annotation encoding="text/plain">Palette 004 - All Characters</annotation></semantics></math>

Example of a bad this.sh value:

    this.sh: [object Object]
    { fonts:
         [ 'STIXMathJax_Main',
           'STIXMathJax_Monospace',
           'STIXMathJax_Latin',
           'STIXMathJax_Alphabets',
           'STIXMathJax_Marks',
           'STIXMathJax_Arrows',
           'STIXMathJax_Operators',
           'STIXMathJax_Symbols',
           'STIXMathJax_Shapes',
           'STIXMathJax_Misc',
           'STIXMathJax_Variants',
           'STIXMathJax_Size1' ],
        FONTS:
         [ { '32': [Object],
             '33': [Object],
             '34': [Object],

...and so on

Example of a good this.sh value:

     this.sh: 686

I'm using mathjax version 2.5.1-mjnode, as part of mathjax-node, release 0.3.0

**Comment by corinnaSchultz** [comment] 2015-08-05 22:52
More info:

Here's an example of mathML which still produces an invalid svg (it shows a rectangle for the character, and an error in the javascript console: "invalid value for <text> attribute y='NaN'"). The special character here is the invisible multiplication.


     <math xmlns="http://www.w3.org/2010/Math/MathML"><semantics><mstyle scriptsizemultiplier="0.715"><mrow><mn>14</mn><mo>&#x2062;</mo><mtable groupalign='{right}' align='baseline 2' rowspacing='0.0ex'><mtr><mtd><mrow><maligngroup/><mo>&#x2062;</mo><mn>14</mn><mo>&#x2062;</mo><malignmark/></mrow></mtd></mtr><mtr><mtd><mrow><maligngroup/><mo>&#x2062;</mo><menclose notation='longdiv'><mrow><mn>14</mn><mo>&#x2062;</mo><malignmark/></mrow></menclose></mrow></mtd></mtr></mtable></mrow></mstyle><annotation encoding="text/plain">Palette 002 - All Characters</annotation></semantics></math>

**Comment by pkra** [comment] 2015-08-06 09:29
Thanks for the report. 

I'm afraid I cannot reproduce this with MathJax so it sounds like a MathJax-node specific problem. 

However, I'm also not able to reproduce this on MathJax-node's `develop` branch. Could you try that branch out and let us know how it goes? If the problem persists, we should move this to the mathjax-node tracker.

**Comment by dpvc** [comment] 2015-08-06 14:46
If you remove the `<mo>&#x2062;</mo>`, the `<maligngroup/>` and `<malignmark/>` elements, do you still get the problem?  I am somewhat confused about the invisible multiplication, which are semantically meaningless in this expression, though it should not cause any problems.  The `<maligngroup/>` and `<malignmark/>` are not actually implemented in MathJax, so they haven't been heavily tested.  It could be one of those that is problematic.

But like Peter, I am not able to reproduce the problem in MathJax directly, or in MathJax-node with the current develop branch.

If you could reduce the test case to the minimum that causes the problem for you, that would be great.

**Comment by dpvc** [comment] 2015-08-06 17:24
If the problem is due to the actual unicode characters, it might that there is an encoding issue(since there are several ways to encode unicode characters).  Can you say something more about how you are passing your MathML to MathJax (i.e., are you using `bin/mml2svg`, or your own code; and if your own code, how are you reading the original MathML)?

**Comment by corinnaSchultz** [comment] 2015-08-06 22:05
The mathML in my "more info" comment, works correctly now if I remove the two tags you mentioned. Thanks for pointing that out.

The situation in my first comment is still present. I don't know the difference between passing characters directly vs. passing hex entity values. And I don't know why we saw different behavior depending on which server was running the code, since it was the same code and the same browser in both scenarios. 

At least now we have a workaround, and we know to disallow certain characters in the mathML we generate.

As a point of information, this mathML originally came from Design Science's Mathflow Java app, which has a bunch of predefined templates. They use several invisible unicode characters, including the invisible times, a couple of different spacing characters.

If I ever do figure out a root cause, and it seems to be a mathjax bug, I'll report back here.

**Comment by pkra** [comment] 2015-08-07 07:33
@corinnaSchultz thanks for the additional information. Have you been able to check your examples with the develop branch of mathjax-node? 

Closing this for now; happy to re-open at a later point.

**Comment by dpvc** [comment] 2015-08-09 19:01
OK, I thought about this some more, and I think I know what's going on.  In your "More info" example, the `<maligngroup/>` tag is the one that is causing problems.  The reason is because HTML doesn't have self-closing tags, and so 

```
<mrow>
  <maligngroup/>
  <mo>&#x2062;</mo>
  <mn>14</mn>
  <mo>&#x2062;</mo>
  <malignmark/>
</mrow>
```

is being parsed as

```
<mrow>
  <maligngroup>
    <mo>&#x2062;</mo>
    <mn>14</mn>
    <mo>&#x2062;</mo>
    <malignmark></malignmark>
  </maligngroup>
</mrow>
```

where the `<maligngroup>` ends up containing all the rest of the nodes in the `<mrow>`.  MathJax expects the `<maligngroup>` to have no children, and the presence of those children is causing the problem.  (The SVG output's base rendering is the one for token elements, and that is overridden by the more complicated elements to do what they are supposed to.  But the `maligngroup` and `malignmark` elements didn't expect to do any rendering, and so didn't override that.  This is a bug and should be fixed.

Also, The MathML input jax has some heuristics to try to detect the incorrect nesting caused by self-closing tags that don't self-close in HTML.  This is used to make things like `<mspace width="1em" />` work, but `maligngroup` and `malignmark` were left out of that logic (I did mention these node types were not well established in MathJax).  So that should be fixed as well.  Either fix would resolve your immediate problem.

I still don't see what could be going wrong in your first example, however.  Are you sure that this is the exact MathML that causes the problem?  I see that there are `<mtext></mtext>` elements, and if they were coded `<mtext/>` instead, that would cause the same type or problem.  I note that your second (working) example doesn't include the empty mtext nodes.  Other than that, I can't see anything that would cause the error.

**Comment by dpvc** [comment] 2015-08-11 12:38
=> Merged

**Closed** 2015-08-11 12:38 UTC
Labels: Accepted, Merged, Test Needed

**Comment by corinnaSchultz** [comment] 2015-08-12 17:00
Thank you so much for pointing out the self-closing mtext nodes. That is definitely part of the problems I'm seeing with some of this wonky mathML. I have a little bit more information, but this may be a separate issue:

Here's mathML that produces invalid svg (it has a <text> tag with y=NaN and containing a character that is rendered as a rectangle)

    <math xmlns="http://www.w3.org/2010/Math/MathML">
    <mrow>
        <mrow>
            <mi>P</mi>
            <mo>⁢</mo>
            <mrow>
                <mo>(</mo>
                <mrow>
                    <mi>A</mi>
                    <mo>⁢</mo>
                    <mtext> </mtext>
                    <mtext> </mtext>
                    <mtext>and</mtext>
                    <mtext></mtext>
                    <mtext></mtext>
                    <mtext></mtext>
                    <mtext></mtext>
                    <mo>⁢</mo>
                    <mtext> </mtext>
                    <mtext> </mtext>
                    <mi>B</mi>
                </mrow>
                <mo>)</mo>
            </mrow>
        </mrow>
        <mo>=</mo>
        <mn>0.10</mn>
     </mrow>
    </math>


(The non-empty mtext tags contain the unicode "thin space" character. The mo character is the invisible times.)

If I change the self-closing mtext tags into proper html syntax empty tags, mathjax still renders this mathml with the bad text element (and y=NaN). If I put a space inside the mtext tags so they are no longer empty, the svg come back fine (no text element, no y=NaN error). If I delete the empty mtext tags, I also get a good svg.

So, perhaps, mathjax doesn't know how to handle the empty mtext tags. It's not just the nesting produced by the self-closing tag syntax, but the fact of having the empty tags?

I have not yet checked this out on the develop branch. I've been scrambling to make a release deadline.

**Comment by pkra** [comment] 2015-08-12 20:35
I am not able to reproduce this on MathJax-node master or develop branch, nor on core MathJax. This does not seem to be MathJax related issue. 

I would strongly suggest to check the other parts of your tool chain. In particular, I would look into @dpvc's suggestion about encoding problems in Unicode.

**Comment by corinnaSchultz** [comment] 2015-08-12 21:16
ok, thanks for looking into this for me. It helps to narrow down the root cause.

**Comment by dpvc** [comment] 2015-08-17 15:19
=> in testsuite

MathMLToDisplay/issue1233.html
