### ISSUE TITLE
On mathjax.org home page, Standard Deviation formula has glitches in Safari 14.0

### ISSUE THREAD

**Issue by jlokier** [mathjax/MathJax#2553] opened 2020-10-11 00:17 UTC
### Issue Summary

On the mathjax.org home page, the Standard Deviation formula under "View Samples" has glitches in Safari 14.0.

### Steps to Reproduce:

Visit https://www.mathjax.org/.  Scroll down and click on "View Samples".  Scroll down and look at the Standard Deviation formula.  Images are attached here.

1. The top half of the limit-N is clipped away (i.e. missing). When selecting it with the mouse, the expected box size for N is highlighted but the top half of the glyph stays missing. Images 1-3 show this; images 4-6 (after page reload) do not.

Two parts of the square root sign, in the larger vertical bar of the tick on the left, come and go.

2. The middle part is present when the page is loaded (image 1), but disappears when selecting the whole formula with a mouse (image 2). It stays disappeared after the selection is cleared (shown in image 3).

3. The upper part (top of the vertical bar where it forms a corner with horizontal bar) is missing after some page reloads (image 4), but present after some page loads albeit with a bump (image 1).

All the other formulae look fine (although selection is ugly because the highlighted regions don't make much sense, but that's not what this bug report is about).

### Technical details:

* MathJax Version: Unknown, but on current front page of https://www.mathjax.org/ as of 2020-10-10 23:54:45 UTC.
* Client OS: Mac OS X 10.15.7
* Browser: Safari 14.0

### Supporting information:

Image 1: After visiting the front page https://www.mathjax.org/ then going to "View Samples".
![Image 1](https://user-images.githubusercontent.com/19521990/95667434-f9752480-0b5d-11eb-9433-2ae804673b75.png)

Image 2: After selecting the title and formula.
![Image 2](https://user-images.githubusercontent.com/19521990/95667437-009c3280-0b5e-11eb-935b-31e83dce8144.png)

Image 3: After clearing the selection.
![Image 3](https://user-images.githubusercontent.com/19521990/95667438-042fb980-0b5e-11eb-8cce-ca9a4ffe7704.png)

Image 4: After reloading the page using the browser's reload key, ⌘R.
![Image 4](https://user-images.githubusercontent.com/19521990/95667439-098d0400-0b5e-11eb-8dc8-75bc1483f4e3.png)

Image 5: After selecting the title and formula.
![Image 5](https://user-images.githubusercontent.com/19521990/95667441-0c87f480-0b5e-11eb-9f44-a74ab4e513b7.png)

Image 6: After clearing the selection.
![Image 6](https://user-images.githubusercontent.com/19521990/95667442-0db92180-0b5e-11eb-8ccd-2154fe810cda.png)

There are no relevant browser console errors.

**Comment by dpvc** [comment] 2020-10-11 19:13
Thank you for your report. This is a duplicate of #2435 and is being investigated as part of the font work we are currently doing.

**Comment by dpvc** [comment] 2021-02-01 16:30
Closing as a duplicate.

**Closed by dpvc** 2021-02-01 16:30 UTC
Labels: Duplicate, v3
