### ISSUE TITLE
Consistency in rendering Mathematics between Mathjax2.75 and Latest version

### ISSUE THREAD

**Issue by jp405405** [mathjax/MathJax#2308] opened 2020-01-25 20:56 UTC
See the same code  snippet using MathJax Latest Version and MathJax2.75. It is working in MathJax2.75 where as not working in latest version (Browser Used: Firefox 72.0.2).

However, if I put a space between `<br>` and `$2$`, it will work in latest version also. I believe it is an issue and hence raising it here. thanks.

**Code in MathJax Latest Version**
>     <html>
>     <head>
> 
>     	<script>
>     	MathJax = {
>     	  tex: {
>     		inlineMath: [['$', '$']]
>     	  }  
>     	};
>     	</script>
>     	<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script"></script>
> 
>     </head>
> 
>     <body>
>     	$2$	<br>$2$  
>     </body>
> 
>     </html>

**Code in MathJax 2.75**

    <html>
    <head>

    	<script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax:{inlineMath: [['$','$']]}
      });    
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML"></script>

    </head>

    <body>
    	$2$	<br>$2$  
    </body>

    </html>

**Comment by dpvc** [comment] 2020-01-25 21:20
This is a duplicate of issue #2202, which has a fix merged into `develop` that will be part of the next release.

**Closed** 2020-02-24 22:04 UTC
Labels: Duplicate, v3
