### ISSUE TITLE
new line before and after $$  ... $$ equations

### ISSUE THREAD

**Issue by Alanthink** [mathjax/MathJax#2225] opened 2019-10-25 01:37 UTC
It seems to me that to make Mathjax $$ ... $$ equations work, there have to be new lines before and after $$...$$ equations. 

Is there any plan to remove this requirement in the future?

BTW, I was using Jekyll to build a static website. And equations are written in markdown file.

**Comment by dpvc** [comment] 2019-10-25 10:49
This is a duplicate of #2202.  There is a pull request that resolves this, and it will be included in the next release.

**Closed** 2019-10-25 10:49 UTC
Labels: Duplicate
