### ISSUE TITLE
an hour ago mathjax from the cdn started showing "multiple rendering" bug

### ISSUE THREAD

**Issue by Krastanov** [mathjax/MathJax#1068] opened 2015-02-25 17:28 UTC
To the right of each equation now there is a small copy of the same equation:
![screenshot from 2015-02-25 12 26 46](https://cloud.githubusercontent.com/assets/705248/6376099/be6823e2-bce9-11e4-95b6-2769ba71f0fe.png)

**Comment by Krastanov** [comment] 2015-02-25 17:31
`2.4-latest` does not have that issue

**Comment by Joe312341** [comment] 2015-02-25 17:31
I am having the same problem. Using cdn and this only happens on IOS Safari. Not on chrome / firefox / safari on Windows

**Comment by Krastanov** [comment] 2015-02-25 17:35
In my case it is on Linux Firefox 31.2.0 (Iceweasel)

**Comment by dpvc** [comment] 2015-02-25 17:38
We pushed an update to the CDN and there seems to be a problem with the upload.  Can you try changing from `mathjax/latest/MathJax.js` to `mathjax/2.5-latest/MathJax.js`, or `mathjax/2.5-latest/unpacked/MathJax.js` and see if that works better?  (You may need to clear the cache and restart the browser.)

**Comment by DanielKeeble** [comment] 2015-02-25 17:45
I'm seeing this as well.

mathjax/2.5-latest/MathJax.js and mathjax/2.5-latest/unpacked/MathJax.js do NOT have the same issue.

**Comment by Joe312341** [comment] 2015-02-25 17:46
yes unpacked version worked for me too on IOS Safari. 2.5-latest did not work on IOS Safari.

**Comment by dpvc** [comment] 2015-02-25 17:47
Thanks for the additional information, @DanielKeeble.  Do you use a consumed configuration file (e.g., TeX-AMS-MML_HTMLorMML), or do you provide your own configuration (that sets the jax and extensions arrays by hand)?

**Comment by dpvc** [comment] 2015-02-25 17:48
@Joe312341, thanks for the additional information.  It should not be browser dependent, as it is based on the files being served from the various CDN edge nodes.  We're looking into it.

**Comment by DanielKeeble** [comment] 2015-02-25 17:51
@dpvc funny you should ask. I am using a using my own inline config, however I still had `?config=TeX-AMS-MML_HTMLorMML` appended to the end of the scripts src tag, but removing this seems to fix this issue. Unfortunately my knowledge isn't that great regarding this package, so does that sound like a plausible fix to you or is it just chance?

**Comment by rulnick** [comment] 2015-02-25 17:57
Additional info: Seeing this bug with latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML,Safe on Chrome (Chrome OS) and Firefox (Mac OS).  Not seeing it when 'latest' replaced by '2.5-latest'.

**Comment by dpvc** [comment] 2015-02-25 18:02
The problem is that some new files didn't get uploaded properly to the CDN during the recent update, and when MathJax started requesting the new files, it got the old ones instead.  We use a cache-breaking string on the URLs to avoid this, but since the old files were served on the URLs for the new string, the CDN edge nodes now have the old version in their caches for those new URLs, even though we have updated the files to the new versions.

The changes I suggested were to try to get your URLs that hadn't been used on those servers yet, s those of you who are getting through on those are getting the new files, since they aren't in the CDN edge node caches for the node you are using.  The reason I asked about the inline configuration is that it is the combined configuration files that were affected by the upload problem, and they are the ones causing the difficulty.

The fix is not really to change your configuration (I only asked you to do that temporarily to see if we could get you working while we try to fix the CDN problem).  It is not just chance that it worked, but is not something you need to leave permanently in place once we get things back in order on the CDN.

**Comment by dpvc** [comment] 2015-02-25 18:51
We think we have the issue resolved on the CDN.  I am now seeing the correct version of the files from all branches.  Can you verify that that is also the case for you?  You may need to clear the cache on your browser.  Thanks.

**Comment by pkra** [comment] 2015-02-25 20:59
Just another roll call: is anyone still experiencing this issue?

And again, sorry for the inconvience this has caused!

**Comment by rulnick** [comment] 2015-02-25 22:04
Tested just now. Yes, dpvc, it is resolved for me.

**Comment by dpvc** [comment] 2015-02-25 22:29
@rulnick, thanks for the confirmation, and (as Peter says), apologies for the problem it caused you.

**Comment by rulnick** [comment] 2015-02-25 22:35
@dpvc thank you to everyone involved for this outstanding resource.

**Comment by hubgit** [comment] 2015-02-25 23:29
I seem to be currently experiencing this in Chrome, using [2.5-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML,Safe](https://cdn.mathjax.org/mathjax/2.5-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML,Safe).

**Comment by dpvc** [comment] 2015-02-25 23:40
@hubgit, I was going to suggest that that might have been the problem. Glad you were able to clear the cache and get things working.

**Comment by pkra** [comment] 2015-02-26 07:36
=> closing

**Closed by pkra** 2015-02-26 07:36 UTC
Labels: Fixed
