### ISSUE TITLE
Newlines (\\) not working for TeX to SVG

### ISSUE THREAD

**Issue by maxkrieger** [mathjax/MathJax#2418] opened 2020-04-22 04:11 UTC
### Issue Summary

The `\\` syntax doesn't seem to work for TeX to SVG.

### Steps to Reproduce:

1. Use https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html
2. Input `f(u_1 + u_2) = \\ f(u_1) + f(u_2)`
3. Observe no linebreak present, whereas there was one in MathJax 2.x

### Technical details:

* MathJax Version: 3.0.5

**Comment by dpvc** [comment] 2020-04-22 16:41
This is a duplicate of #2312.  See that issue for more details and some potential work-arounds.

**Comment by dpvc** [comment] 2021-02-01 17:32
Closing as a duplicate.

**Closed by dpvc** 2021-02-01 17:32 UTC
Labels: Duplicate, v3
