### ISSUE TITLE
[CommonHTML] Safari extraneous space in mover 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1709] opened 2017-03-01 09:08 UTC
[Reported via the user group](https://groups.google.com/forum/#!topic/mathjax-users/J9-jy6_tVmM).

Using the CommonHTML output, Safari 9 and 10 add extra space to the right of an `mover`; HTML-CSS and SVG seem ok. This might be a browser bug.

Example.
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow class="MJX-TeXAtom-ORD">
    <mover>
      <mi>u</mi>
      <mo stretchy="false">&#x2192;<!-- → --></mo>
    </mover>
  </mrow>
  <mo>+</mo>
  <mrow class="MJX-TeXAtom-ORD">
    <mover>
      <mi>v</mi>
      <mo stretchy="false">&#x2192;<!-- → --></mo>
    </mover>
  </mrow>
</math>
```

**Comment by dpvc** [comment] 2017-03-02 15:40
The vector arrow is one of the combining characters, so it is zero-width.  The combining characters have been a perennial headache, as the browsers handle them differently, and there is often problems when they are used without a preceding character (as is the case for MathJax, which positions them by hand).  It looks like Safari has made a change that affects this (they are incorrectly handing the zero width, and it is getting a non-zero width).  It looks like explicitly setting `width:0` on the parent element will do the trick.

**Comment by pkra** [comment] 2017-03-02 16:24
>  It looks like Safari has made a change that affects this (they are incorrectly handing the zero width, and it is getting a non-zero width)

I'll try to make file a bug upstream.

**Comment by dpvc** [comment] 2017-06-01 23:32
Well, I suspect that Safari's behavior is by design, and will not be considered a bug by Apple.  The combining characters like the vector accent (U+20D7) are implemented by making the character be zero-width and overlapping on the left, so that when it follows a character, it extends over that character.  Most browsers also may add a vertical shift to accommodate tall letters (the accent is usually positions in the font to cover a lower-case letter like "x").  Some browsers will also try to center the accent over the preceding character (e.g., Chrome).

Since these characters are intended to combine with the previous character, the expected behavior for when there *is* no preceding character is not clear.Some browsers (e.g., IE) would not show the character at all, for example, but until Safari 10, most other browsers simply showed the character to the left of the starting position (as though there actually *were* something to overlap.  As of Safari 10, however, when there is no preceding character, the combining character is instead treated like a *non*-combining character, and so it extends to the right of the starting point and takes up non-zero space.

MathJax positions accents "by hand", so it puts the accent in a positioned element by itself.  That means that Safari now operates completely differently from everybody else (having the accent extend to the right rather than to the left), which is what is causing the result described in this issue.  

The natural solution would be to use a space as a preceding character (MathJax has done this for IE in the past) so that Safari will place the accent in the same place as the other browsers.  Unfortunately, Safari and Firefox consider this to be a "tall" character, and move the accent up, while Chrome leaves it where it is, so now there is a vertical difference rather than a horizontal one between the browsers.  Furthermore, since Chrome centers accents, and the space is not the same width as the vector arrow, Chrome now has a horizontal difference as well.  It turns out that the arrow is the size of two spaces, so that can be used to alleviate the horizontal spacing problem, but I was not able to come up with a mechanism to get the vertical spacing to be consistent (and believe me, I tried).

So at this point, I don't see how to get combining characters to work for accents consistently across all browsers.  The best answer would be to not use combining character at all, since they are unreliable (and always have been).  But this would require changes to the fonts.  We can do that for version 3, but for now, the best solution I could come up with is to use a new font with a non-combining version of the needed glyph.  For the MathJax TeX fonts (the only ones supported by the CommonHTML output), there is only one combining character that is actually used, so we really only have to work out a mechanism for that one, so a simple font with only one character would suffice.

I made such a font and converted it to a CSS font, so that it can be included within a page directly.  Here is an example of a patch that can be used for now until new fonts are available in version 3.

```
<!DOCTYPE html>
<html>
<head>
<title>MathJax Safari vector placement</title>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  CommonHTML: {
    styles: {
      "@font-face /* vec */ ": {
        "font-family": "MJX-VEC",
        src: [
          "url(data:application/x-font-woff;charset=utf-8;base64,",
          "d09GRgABAAAAAARMAA0AAAAABiQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAAEMAAAABwA",
          "AAAccRGLqUdERUYAAAQMAAAAJAAAACgANAAmT1MvMgAAAaAAAABJAAAAYFc5gfFjbWFwAAACAAAA",
          "AEYAAAFKQxjlbWdhc3AAAAQEAAAACAAAAAj//wADZ2x5ZgAAAlQAAACUAAAAlIQU9HBoZWFkAAAB",
          "MAAAADAAAAA2C748e2hoZWEAAAFgAAAAHgAAACQFXQDqaG10eAAAAewAAAAUAAAAFAYvAE9sb2Nh",
          "AAACSAAAAAwAAAAMACgAcm1heHAAAAGAAAAAHQAAACAASQAmbmFtZQAAAugAAADxAAAB5uwlD0hw",
          "b3N0AAAD3AAAACgAAAA34M9aEXjaY2BkYGAA4uOfgq7G89t8ZeBmfgEUYbga+icNTssClVxnOgXk",
          "cjAwgUQBdqEMW3jaY2BkYGBu+feBgYHxCwMQMF5nYGRABawAcaQESgAAeNpjYGRgYGBlUGZgYgAB",
          "EMnIABJzAPMZAAZZAHAAAAB42mNgYSxn/MLAysDA1MW0h4GBoQdCMz5gMGRkAooysDEzwAAjECvA",
          "OAFprikMBxgUFCcxt/z7wMDA3MIoAFUDAwoMjACD8Qv5AAAAAfQAMgAAAAABTQAAAPoAAAH0AB14",
          "2mNgYGBmgGAZBkYGEHAB8hjBfBYGDSDNBqQZGZgYFBQn/f8P5IPp/4/vFUHVAwEjGwOcw8gEJJgY",
          "UAEjxIrhDACLGwmnAAAAAAAUABQAFAAUAEoAAgAyAAABwgIVAAMABwAAMxEhESUhESEyAZD+ogEs",
          "/tQCFf3rMgGxAAEAHQIEAdcCygAiAAABNDYzMhcWFxYXFhUUBgcGBw4DIyImNTQ3IycmNTQ3ISYB",
          "eQsJBwUFBQofCwYLKyACBwMGBAcNL6urDQ0BZxgCtggMBQQPJRQHCwkGBhYpAgkCAgsJEygBCQoH",
          "DSYAeNqVjrGKwkAURe/EGBBUrG12CishMrFQcDuLsAi26YMOmsIMxAh+hN8i+CF+gd+y4B3zttjC",
          "woHhncu7774HoI8rFP5eIKzQw5dwgAjfwi2McBEO6bkLtzHAr3CEnhrTqcKOpDasMCQ1HKCLWLiF",
          "HyyFQ3puwm1oPIQjDFXfR62Ro8YeK9YzMlhsqB0qtvJ6v8rPmd3Uzkv2tihwwoHCbosTa0pryYH0",
          "NbKjRWPB/z626Se8dsY/hSHPGeTKOnXVzuqF/reYOoln8dQk80+u9b0KR97rD9Rc4xdNXtVQI7PV",
          "sXClNiaZGGP0B+FPMN1KMAAAAHjaY2BiAIP/zQxGDNgAKxAzMjAxMDMycSUWFeWXF2WmZ5QAAGh5",
          "BhgAAAAB//8AAnjaY2BkYGDgA2IJBgUgycTAyMDMwAIkWcA8BgZGCAYACgIAWwAAAAEAAAAAxmW3",
          "ygAAAADVVeemAAAAANVV7Dg=) format('woff')"
        ].join('')
      },
      ".MJX-VEC": {
        "font-family": "MJX-VEC"
      }
    }
  }
});
MathJax.Hub.Register.StartupHook("CommonHTML Jax Ready", function () {
  var MML = MathJax.ElementJax.mml;
  var fixCombiningChar = MML.mo.prototype.CHTMLfixCombiningChar;
  MML.mo.Augment({
    CHTMLfixCombiningChar: function (node) {
      if (node.textContent === '\u20D7') {
        //
        //  Safari makes combining characters into non-combining ones when
        //  they don't have anything to combine with; replace \vec arrow
        //  with a non-combining one so all browsers get the same thing
        //
        node = node.firstChild;
        node.firstChild.nodeValue = "\u2192";
        node.className = "mjx-char MJX-VEC";
        node.style.marginLeft = "-.5em";
        node.style.paddingTop = ".45em";
      } else {
        fixCombiningChar.call(this,node);
      }
    }
  });
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML"></script>
</head>
<body>

<div style="margin-top:2em; font-size: 300%">
xxx\(\vec x x\)xxx
<span style="font-family: MJX-VEC">&#x2192;</span>
</div>

</body>
</html>
```

**Comment by pkra** [comment] 2017-06-02 07:24
> Well, I suspect that Safari's behavior is by design, and will not be considered a bug by Apple.

They are often open if the behavior is different from (all) other browsers. (At the very least, it would be something to bring up with the CSS WG)

I made [a very minimal example](https://codepen.io/pkra/pen/yXBRxW) but screenshots across browsers were not very informative,  [cbt_2357888_2471928.zip](https://github.com/mathjax/MathJax/files/1046932/cbt_2357888_2471928.zip)

If we can create a better minimal example, we might be able to make a case.

**Comment by dpvc** [comment] 2017-06-02 11:32
I think the example should load a font known to have the vector arrow.  That would resolve the Windows missing character issues, for example, but more importantly, it would make sure you are getting a font that uses the zero-width character approach for the accents.  It turns out that that is not the only way to do it (the MathJax fonts do that because that's how the STIX fonts did it, and we followed that model), but other fonts, like Arial Unicode and Cambria Math use normal glyphs, and apparently the browsers use the Unicode positions (part of a combining character block) to decide that they should be combined even though they have non-zero width.

I'd also suggest using all four possible combinations of characters with surrounding spans (no spans, span around first, span around second, span around both) just to see the differences, if any.

So using

```
@font-face {
  font-family: VEC;
  src: url(https://cdn.mathjax.org/mathjax/latest/fonts/HTML-CSS/TeX/otf/MathJax_Main-Regular.otf) format("opentype")
}
```

for the CSS and

```
<div style="font-family:VEC">
u&#x20D7;
<span>u</span>&#x20D7;
u<span>&#x20D7;</span>
<span>u</span><span>&#x20D7;</span>
</div>
```

for the HTML might be a better test, and should show up the difference between Safari and the others.

I suspect that we can use the full-width characters in the version 3 fonts and so avoid the issue all together.

**Comment by pkra** [comment] 2017-06-02 13:30
Thanks, Davide.

I've updated the example and generated new screenshots. Much more interesting now and shows that Safari 9 had only one of them wrong but Safari 10 has two of them wrong. (To round things off, IE10 has an issue with all of them and Chrome has a minor issues with the first, only on Mac.)

[cbt_2358181_2472234.zip](https://github.com/mathjax/MathJax/files/1047779/cbt_2358181_2472234.zip)

**Comment by pkra** [comment] 2017-06-02 13:55
Filed at https://bugs.webkit.org/show_bug.cgi?id=172855.

I noticed that WebKitGTK+ 2.16.3 has no such issue so perhaps this is easy for them to fix if they care enough.

**Comment by dpvc** [comment] 2017-06-02 14:45
Thanks, Peter, that is more interesting, and more consistent with my experience as well.  It looks like IE10 is not getting the arrows from the MathJax font (they are not shaped properly), so it might be getting them from somewhere else that doesn't use zero-width characters.  I'm not sure the IE10 result is valid for that reason.  

I'm not sure what is going on with the Chrome issue for the first example.  I do know that it repositions the accent based on the height of the preceding character, but it may be that it only does that if there is no intervening span, so the first one is its repositioned version, while the others are just using the glyph in its unmodified position.  For example, switching all the u's to X's shows that only the first arrow is in the proper position.

Safari also repositions the first arrow for larger letters, but just uses a little less space above the letter so that it matches the un-positioned versions better, while Firefox doesn't reposition the accent for taller letters.  I didn't try it in IE or Edge.  So I guess Chrome's result is "correct", but that the spacing is perhaps a bit larger than necessary.

**Comment by pkra** [comment] 2017-06-02 19:47
It was marked as a duplicate of https://bugs.webkit.org/show_bug.cgi?id=6148 (which was filed in 2005). 

Truly, Safari is the new IE.

**Comment by dpvc** [comment] 2017-06-02 19:52
I agree that they have mis-marked this as a duplicate, as well as Safari being the new IE.  Sigh.

**Comment by dpvc** [comment] 2017-07-07 15:45
The `issue1709` includes a work-around for this issue.

**Comment by dpvc** [comment] 2017-07-10 01:24
==> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/mover/issue1737.html

(this tests both 1737 and 1709)

**Comment by dpvc** [comment] 2017-07-11 11:15
==> Merged

**Closed** 2017-07-11 19:11 UTC
Labels: Accepted, Browser Bug, Merged, Test Available

**Comment by khaledhosny** [comment] 2018-02-03 14:34
This is closed issue, but here are a few suggestions that might help in the future to stop browsers from automatically positioning combining marks:
1. Include a `GDEF` table in the font and set the glyph class for the combining marks to base glyph instead of mark (without such table text layout engines will typically use the Unicode character properties to determine glyph classes).
2. Include a `GPOS` table even if empty, which some layout engine use to decide whether to automatically position mark glyphs or rely on the font to do so.
3. A more radical way is to use PUA characters for the marks which layout engine will typically leave alone and not do any automatic positioning, but using PUA has its known disadvantages.

**Comment by dpvc** [comment] 2018-02-05 14:53
Thanks for the information.  We will be rebuilding the fonts for MathJax version 3, and will keep these ideas in mind for the process.
