### ISSUE TITLE
mathjax 3.0.0 mathml2chtml error

### ISSUE THREAD

**Issue by yiptsangkin** [mathjax/MathJax#2370] opened 2020-03-16 07:33 UTC
when i use MathJax.mathml2chtml('`<math xmlns="http://www.w3.org/1998/Math/MathML"><mfenced open="{" close=""><mtable columnalign="left"><mtr><mtd><mn>2</mn><mi>x</mi><mo>+</mo><mi>y</mi><mo>=</mo><mo>&#9675;</mo></mtd></mtr><mtr><mtd><mn>2</mn><mi>x</mi><mo>-</mo><mi>y</mi><mo>=</mo><mn>12</mn></mtd></mtr></mtable></mfenced></math>`')

it throw out these errors

tex-mml-chtml.js:1 Uncaught TypeError: Cannot read property 'parentNode' of null
    at l.parent (tex-mml-chtml.js:1)
    at f.measureTextNode (tex-mml-chtml.js:1)
    at f.d.measureTextNodeWithCache (tex-mml-chtml.js:1)
    at f.d.measureText (tex-mml-chtml.js:1)
    at u.e.computeBBox (tex-mml-chtml.js:1)
    at u.g.getBBox (tex-mml-chtml.js:1)
    at c.g.computeBBox (tex-mml-chtml.js:1)
    at c.e.computeBBox (tex-mml-chtml.js:1)
    at c.g.getBBox (tex-mml-chtml.js:1)
    at m.g.computeBBox (tex-mml-chtml.js:1)

but i use https://cdn.rawgit.com/mathjax/MathJax/2.7.1/test/sample-dynamic-2.html
it works ok, is this bug for version 3.0.0?

**Comment by yiptsangkin** [comment] 2020-03-16 07:39
i see the release show it fix in 3.0.1, but the same function throw another error 'Error: Unknown node type "body"'

**Comment by dpvc** [comment] 2020-03-16 14:26
This is a duplicate of #2330, and there is a work-around listed there.  It is fixed in the next release.

**Comment by dpvc** [comment] 2020-03-16 14:28
PS, the original error you cite *is* fixed.  This is a new one.

**Comment by yiptsangkin** [comment] 2020-03-16 16:09
> PS, the original error you cite _is_ fixed. This is a new one.

thx a lot! i use this to solve the problem temporary.
`MathJax = {
    mml: {
        forceReparse: true
    }
}`

**Closed** 2020-08-25 18:06 UTC
Labels: Duplicate, v3

**Comment by doox911** [comment] 2021-11-08 11:16
I have the same problem with NuxJs:

Nuxt config:

```
    script: [
      {
        src: 'https://polyfill.io/v3/polyfill.min.js?features=es6',
      },
      {
        id: 'MathJax-script',
        src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
        body: true,
        async: true,
      },
    ],
```

**Comment by ss-zf-520** [comment] 2023-05-12 08:14
![image](https://github.com/mathjax/MathJax/assets/47528311/b428f82c-8533-45b8-a645-dbc109cff692)
How did you handle it?

**Comment by dpvc** [comment] 2023-05-12 11:32
@ss-zf-520, see #2330 for a work-around, as mentioned above in my [comment](https://github.com/mathjax/MathJax/issues/2370#issuecomment-599565595).

**Comment by BinaryQuantumSoul** [comment] 2023-07-01 11:09
@dpvc I still have this issue as today using script `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js`
I have the following error:
```
tex-chtml.js:1 Uncaught TypeError: Cannot set property Package of #<Object> which has only a getter
    at s (tex-chtml.js:1:13801)
    at s (tex-chtml.js:1:13808)
    at s (tex-chtml.js:1:13808)
    at s (tex-chtml.js:1:13808)
    at e.combineWithMathJax (tex-chtml.js:1:14317)
    at tex-chtml.js:1:1144820
    at tex-chtml.js:1:1160983
    at tex-chtml.js:1:1160987
   ```
   
   I don't see how your workaroud would work since the only thing I do is adding the script to html

**Comment by dpvc** [comment] 2023-07-01 18:20
@BinaryQuantumSoul, can you give the configuration that you re using?  It's true that this is not the same issue as the original post.  The issue is related to combining configurations, but I would need to see the configuration you are using before I could say more.  If you don't have an explicit configuration, can you post a link to the page where this is occurring?

**Comment by BinaryQuantumSoul** [comment] 2023-07-01 21:15
> @BinaryQuantumSoul, can you give the configuration that you re using?  It's true that this is not the same issue as the original post.  The issue is related to combining configurations, but I would need to see the configuration you are using before I could say more.  If you don't have an explicit configuration, can you post a link to the page where this is occurring?

I'm doing a betterDiscord plugin, so it's running on electron.
I load it with this code ```

module.exports = class Plugin {
  static mathJaxURL =
    "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js";

  loadMathJax() {
    const checkExisting = document.querySelector(
      'script[src="' + Plugin.mathJaxURL + '"]'
    );
    if (!checkExisting) {
      var mathJaxScript = document.createElement("script");
      mathJaxScript.src = Plugin.mathJaxURL;
      mathJaxScript.async = true;
      document.head.appendChild(mathJaxScript);
    }
  }

```

So it's basically just a <script> The error appears but it's still usable. However I tried bundling mathjax with the extension and using require/import for npm downloaded mathjax, and the same error occurs and now I can't ignore it since it's preventing the plugin to launch

**Comment by dpvc** [comment] 2023-07-02 12:32
@BinaryQuantumSoul, I am not able to reproduce the problem in a stand-alone file.  I haven't used discord or electron, only your class, so I'm not able to test the issue.  The following file works as expected for me:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Package error</title>
<script>
class Plugin {
  static mathJaxURL = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js";

  loadMathJax() {
    const checkExisting = document.querySelector('script[src="' + Plugin.mathJaxURL + '"]');
    if (!checkExisting) {
      var mathJaxScript = document.createElement("script");
      mathJaxScript.src = Plugin.mathJaxURL;
      mathJaxScript.async = true;
      document.head.appendChild(mathJaxScript);
    }
  }
}
</script>
</head>
<body>

$$x+1\over x-1$$

<script>
const plugin = new Plugin();
plugin.loadMathJax();
</script>

</body>
</html>
```

Can you provide a link to a test page where I can see better what is happening?

**Comment by BinaryQuantumSoul** [comment] 2023-08-05 13:05
Sorry for late reply,

I was able to remove the error, but I don't know how, using this:
```js
const MATHJAX_SCRIPT_CLASS = "MathJaxDiscord";
const MATHJAX_CONFIG = `MathJax = {
    tex: {
      inlineMath: [['mthjxinline', 'mthjxinlineend']],
      displayMath: [['mthjxblock', 'mthjxblockend']]
    }
  };`;

module.exports = class Plugin {
  loadMathJax() {
    const scriptElements = document.getElementsByClassName(MATHJAX_SCRIPT_CLASS);
    if (!scriptElements || scriptElements.length === 0) {
      const mathJaxConfig = document.createElement("script");
      mathJaxConfig.innerHTML = MATHJAX_CONFIG;
      mathJaxConfig.defer = true;
      mathJaxConfig.classList.add(MATHJAX_SCRIPT_CLASS);
      document.head.appendChild(mathJaxConfig);

      const mathJaxScript = document.createElement("script");
      mathJaxScript.src = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js";
      mathJaxScript.defer = true;
      mathJaxScript.classList.add(MATHJAX_SCRIPT_CLASS);
      document.head.appendChild(mathJaxScript);
    }
  }
}
```

However I can't settle on this solution since I need to bundle MathJax inside a single plugin file. And the error is then coming back. I'm [creating new issue](https://github.com/mathjax/MathJax/issues/3079).

**Comment by dpvc** [comment] 2023-08-10 00:06
@BinaryQuantumSoul, I have responded in the new issue, #3079.
