### ISSUE TITLE
[CommonHTML] [Firefox] Anomaly with spacing before and after \text

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1718] opened 2017-03-12 14:31 UTC
The issue can be seen in https://cdi2tp.math.tecnico.ulisboa.pt/texto/10 with Firefox 52 on Linux Mint. This may be very browser, version, OS,..., specific problem. Absent from Firefox 51 on Windows or Firefox 52 on Android.

![imagem](https://cloud.githubusercontent.com/assets/1136663/23832523/b577c0d6-072d-11e7-95b5-f8796585510c.png)

Spacing after the phrase "Existe um caminho unindo" in a displayed formula has disappeared although you can see it on mouseover.

**Comment by pkra** [comment] 2017-03-13 08:14
Thanks for the report.

I see this on FF 51 on Windows 10 actually (and Linux) but not on macOS.

I also only see this for the CommonHTML output.

**Comment by pkra** [comment] 2017-03-13 08:15
For the record, I don't see it with FF's dev channel on Win10, so it might be a browser bug with an upcoming fix.

**Comment by dpvc** [comment] 2017-03-29 17:02
The issue is not restricted to Firefox.  Here's what's going on:  because you are using `mtextFontInherit:true`, MathJax must measure the size of the text so that it knows how much space it takes up.  It gets the size in pixels, and must convert that to em's (which is what it uses internally).  This is done using the em-size of the font surrounding the math, but this value is determined empirically and so is only an approximation.  For a very wide item (like a long string of text), the inaccuracy of the em-size has a noticeable effect on the size that MathJax determines, and so the computed size is somewhat far off from the actual size.  The CommonHTML output forces the size of the items it measures to be the computed size (so that if it is off, that doesn't have ripple effects to the sizes of things that surround it).  So what you are seeing here is CommonHTML trying to force the long line of text to fit the size it thinks it is rather than the size it actually is.

One possible solution might be to have CommonHTML not set the width for items over a certain size, where the inaccuracy in the em-size measurements are magnified to such an extent that it becomes problematic, as in this case.  Or a second measurement could be taken after the size is set to see how far off it is (though that would cause an additional reflow performance hit).

**Comment by dpvc** [comment] 2017-07-07 12:38
The `issue1718` branch of my fork of MathJax works around this.

**Comment by dpvc** [comment] 2017-07-10 11:56
==> Merged

**Comment by dpvc** [comment] 2017-07-15 00:53
==> In testsuite

MathMLToDisplay/Presentation/TokenElements/mtext/issue1718.html

**Closed** 2017-07-15 00:54 UTC
Labels: Accepted, Merged, Test Available
