### ISSUE TITLE
Less than sign adjacent to letter in version 3

### ISSUE THREAD

**Issue by Alex-Jordan** [mathjax/MathJax#2669] opened 2021-04-11 01:56 UTC
### Issue Summary

At least in Firefox, math content with version 3 like `1<x` is broken. The browser interprets `<x` as opening an HTML element. This is a behavior change from version 2, but I am unsure if it should be considered a bug, or if it is just not supported to use `<` when you could use `\lt` instead.

### Steps to Reproduce:

1. Visit https://www.mathjax.org/#demo in Firefox.
2. Change `When $a \ne 0$,` to `When $1<x$`.

In the output, you will see `When $1` and nothing more. In other settings (not this live rendering) the DOM inspector suggests the browser has interpreted `<x` as an HTML tag opening.

### Technical details:

* MathJax Version: 3
* Client OS: Mac OS X 10.14.6
* Browser: Firefox 87

Using `1< x` or `1\lt x`, the math renders as expected.

**Comment by dpvc** [comment] 2021-04-11 12:49
This is expected behavior, because the math in the page is part of an HTML page, and so HTML special characters will be interpreted by the browser long before MathJax runs.  So the browser with treat `<x` as the beginning of a tag when it parses the DOM.  MathJax can't do anything about that, as the DOM has already been parsed by the time it runs.

See the [documentation](https://docs.mathjax.org/en/latest/input/tex/html.html) for more details.

Math inserted programmatically into the page (as is being done by WeBWorK) should escape the HTML special characters (`<`, `&`, and `>`) into their respective entities (`&lt;`, `&amp;`, `&gt;`) before inserting the math into the page, as you would have to do for any other use of those characters in the text of the page.

**Comment by dpvc** [comment] 2021-04-11 12:56
Duplicate of #457.

**Comment by Alex-Jordan** [comment] 2021-04-11 15:27
OK, that seemed like it might be the case. My testing indicates that in WeBWorK 2.15, which uses MathJax 2, that `\(1<x\)` comes out as rendered math that one might expect. If the behavior change is not due to MathJax 2 -> 3, there must be something about WW 2.15 -> 2.16 that is responsible.

**Comment by dpvc** [comment] 2021-04-12 11:46
> If the behavior change is not due to MathJax 2 -> 3, there must be something about WW 2.15 -> 2.16 that is responsible.

Right.  It is the fact that when using v2, WeBWorK inserted the math inside `<script type="text/math">` tags, and `<script>` content is CDATA automatically, so doesn't need to he HTML escaped.  The change to v3 went to raw `\(...\)` in the text, and so the math is now regular text on the page, so HTML special characters need to be escaped.  In particular, `<` needs to be represented as `&lt;` and `&` as `&amp;`.

**Closed** 2021-07-06 21:46 UTC
Labels: Duplicate, Expected Behavior
