### ISSUE TITLE
On Chrome Canary a vertical line is being shown to the right of \frac 1 2

### ISSUE THREAD

**Issue by BugsNash** [mathjax/MathJax#1306] opened 2015-11-23 03:18 UTC
On Chrome Canary a vertical line is being shown to the right of `\frac 1 2`

E.g. http://jsfiddle.net/L276to7d/1/

For the span element to the right of the fraction, it seems like MathJax generates border-left style code differently for different browsers.

Chrome:

`<span style="border-left-width: 0.003em; border-left-style: solid; display: inline-block; overflow: hidden; width: 0px; height: 1.566em; vertical-align: -0.497em;"></span>`

Firefox:

`<span style="border-left: 0em solid; display: inline-block; overflow: hidden; width: 0px; height: 1.74em; vertical-align: -0.545em;"></span>`

As of Chrome 48.0.2553.0, this 0.003em left border is rounded up to 1px (consistent with other browsers) and displays a vertical line to the right of the fraction. See bug https://code.google.com/p/chromium/issues/detail?id=552421

**Comment by pkra** [comment] 2015-11-23 09:51
This is a duplicate of https://github.com/mathjax/MathJax/issues/1300.

**Closed** 2015-11-23 09:52 UTC
Labels: Duplicate
