### ISSUE TITLE
linebreaks option in mathjax-src

### ISSUE THREAD

**Issue by ShaMan123** [mathjax/MathJax#2447] opened 2020-05-29 05:53 UTC
### Issue Summary

Using `mathjax-src`. It's terribly difficult to find documentation regarding config. I've stumbled upon the option `linebreaks` and tried to implement it with no success.
Is there a way? I saw that `mathjax-node` supports it but I can't use it (using react-native).

https://github.com/mathjax/MathJax-demos-node/issues/15

### Steps to Reproduce:
Run [this](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg) and try to configure linebreaks.

### Technical details:

* MathJax Version: mathjax-full@3
* Using in react-native

### Supporting information:
I can't find proper documentation.

**Comment by dpvc** [comment] 2020-05-29 14:27
Line breaking has not yet been ported to MathJax v3.

> I can't find proper documentation.

See the [line breaking](http://docs.mathjax.org/en/latest/output/linebreaks.html) link in the "MathJax Output" section of the [MathJax Documentation](http://docs.mathjax.org/en/latest/).

> It's terribly difficult to find documentation regarding config

Try the [Configuration Options](http://docs.mathjax.org/en/latest/index.html#configuration-options) topic on the main documentation page.

**Comment by dpvc** [comment] 2020-05-29 14:28
I'm marking this a duplicate of #2312.

**Comment by dpvc** [comment] 2021-02-01 17:20
Closing as a duplicate.

**Closed by dpvc** 2021-02-01 17:20 UTC
Labels: Duplicate, v3
