### ISSUE TITLE
Characters with diacritical marks inside \\text{}

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2401] opened 2020-04-10 14:08 UTC
### Issue Summary

Characters with diacritical marks inside \\text{} appear in a font (size?) different from ascii characters. There is a marked difference in Linux. For Windows size is about the same but one can tell it is a different font.

### Steps to Reproduce:

Typeset
\\[f(x)=\begin{cases}\\frac{xy}{\\sqrt{x^2+y^2}},& \\text{ se } (x,y)\\neq (0,0),\\\\ 0, & \\text{ caso contrário. éíóúñ}\end{cases}\\]

### Technical details:

* MathJax Version: 3.0.5
* Client OS: Linux Mint 19, Windows 10.
* Browser: Firefox 75.0 (64-bit) on Linux Mint 19, Firefox 74 on Windows 10.

### Supporting information:

 * See the first exemple in https://cdi2tp.math.tecnico.ulisboa.pt/test

![Captura de ecrã de 2020-04-10 15-03-53](https://user-images.githubusercontent.com/1136663/78996578-c9ac7c00-7b3c-11ea-9b79-a3e104522beb.png)

 * MathJax configuration: https://cdi2tp.math.tecnico.ulisboa.pt/scripts/mathjax-config.js
   Script tag that loads MathJax itself: https://cdi2tp.math.tecnico.ulisboa.pt/mathjax3/es5/tex-mml-chtml.js

**Comment by dpvc** [comment] 2020-04-10 16:08
The issue is actually with `mtextInheritFont`, which is broken in v3, and hasn't been fixed yet (it is going to require a change to the configuration, and that will be made in v3.1).  Technically, this is a duplicate of your #2189 for that reason.  

As a fix for now, you could add

```
mjx-utext {
  font-family: MJXZERO, Noto Sans, sans-serif
}
```

to your CSS.

The reason that the characters are different sizes is that some are being taken from the MathJax TeX font set, and some from system fonts (when they aren't in the TeX font), and the two don't have the same ex-heights, so they don't match well.  MathJax normally adjusted the scaling of its fonts to match the system fonts, but it thinks that all the characters are coming from the surrounding font, which they are not due to a setting on the mathjax container element that can not be removed without damaging the layout.

**Closed** 2021-02-01 17:35 UTC
Labels: Accepted, Duplicate
