### ISSUE TITLE
MathJax.Hub.Queue fails when called from GWT function

### ISSUE THREAD

**Issue by kevinushey** [mathjax/MathJax#1584] opened 2016-08-16 22:47 UTC
I'm running into trouble using MathJax within a GWT project. I have a GWT function using the native JSNI interface e.g.

```
    private static final native void mathjaxTypeset(String text, Element el) /*-{
      var MathJax = $wnd.MathJax;
      var f = function(x) { alert(x); };
      MathJax.Hub.Queue([f, 15]);
    }-*/;
```

Unfortunately, this fails for the reasons outlined by https://github.com/mathjax/MathJax/issues/508 -- we get a MathJax error of the form

```
<...> Can't make callback from given data
```

This ultimately stems from MathJax's use of `args instanceof Array` -- within the context of GWT, this check fails.

![screen shot 2016-08-16 at 3 46 01 pm](https://cloud.githubusercontent.com/assets/1976582/17718419/9ea732c8-63c8-11e6-8887-6ba110463385.png)

You'll notice that `instanceof Array` returns `false`, despite other checks reporting that this is indeed an array. Could this condition be relaxed to use a helper function e.g.

```
function isArray(object) {
    return Object.prototype.toString.call(object) === "[object Array]";
}
```

Or even `Array.isArray()` would suffice here.

Thanks!
Kevin

**Comment by dpvc** [comment] 2016-08-21 15:47
Thanks for your report, and proposed fix.  You are certainly correct that `instanceof` can be problematic, and certainly is in your case.  We ran into some similar issues in mathjax-node.

As you point out in your PR, we can't use `Array.isArray()` due to lack of support in some browsers, and MathJax has a policy against modifying global prototypes to add missing functionality like this.  Your suggestion of using `toString()` would work, but because some of these calls are in core pieces of MathJax (e.g., the Callback class, which is used very heavily), I would want to investigate the performance impact; I doubt it is significant, but that needs to be verified.

Also, your PR is a little more aggressive than necessary, as some of the instances you changes are not going to be in places where mixed origins for the arrays will occur, so `instanceof` is fine in those cases.  I would also want to make a utility function for this rather than reproduce the same code over and over.  So I'm going to close your PR for now, but appreciate the work you have done to try to overcome the issue and your willingness to share your solution.

@pkra, do you want to include something for this in v2.7?

**Comment by kevinushey** [comment] 2016-08-21 16:50
Thanks for your thoughtful response @dpvc -- I definitely agree a more nuanced version of my proposed PR would be more appropriate. Thanks for taking the time to respond + review!

**Comment by dpvc** [comment] 2016-08-24 17:15
The `issue1584` branch of my fork of MathJax includes a fix for this.  It turns out that most of the `instanceof` calls did need to be changed after all (only a few could be pretty much guaranteed to not need to be changed).  I provided a service routine, `MathJax.Object.isArray()`, to handle it.

There is also a new `MathJax.Object.Array()` call that can be used to create an array using the Array object that MathJax is using, so even if one of the unchanged cases comes into play, you can use that to create the proper type of array.  I think that should cover all the bases.

I looked into the performance, and the difference seems negligible.

**Comment by dpvc** [comment] 2016-08-25 01:24
==> In testsuite

Configuration/issue1589.html

**Comment by dpvc** [comment] 2016-08-29 14:19
==> Merged.

**Closed** 2016-08-29 14:19 UTC
Labels: Accepted, Feature Request, Merged, Test Available

**Comment by kevinushey** [comment] 2016-08-29 16:40
Awesome, thanks!
