### ISSUE TITLE
subscript size differs IE vs FF

### ISSUE THREAD

**Issue by zino113** [mathjax/MathJax#1540] opened 2016-06-30 14:10 UTC
Hi all -

Attached you'll find an example of subscripts differing in size where they should not: the first {1} is larger than the second {2} (and afaic too large to begin with).

![mathjax_subscript_firefox](https://cloud.githubusercontent.com/assets/20226105/16490732/6f72e178-3eca-11e6-9f2d-fe8d0dc41b40.png)

The screenshot is from Firefox v48.0 beta 4 but this has been observed for some months at least.
In Internet explorer v9 the same example renders correct.

Am I right in guessing that this not a _MathJax version_ issue as I'm using this construct in the web page:

`<script type="text/javascript"`
 `src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">`
`</script>`

Could you tell me whether it makes sense to report this here, or do you suggest to rather report somewhere else..?

Best regards
-Z

**Comment by pkra** [comment] 2016-06-30 15:08
Thanks for the report. This is the right place for it. We'll take a look.

**Comment by pkra** [comment] 2016-06-30 18:18
I'm unable to reproduce this on FF47 (linux).

Can you try clearing the browser cache to make sure it's not due to a corrupted resource?

**Comment by zino113** [comment] 2016-07-01 19:12
Hi Peter -

This afternoon I was at a workstation running W7 Pro 64-bit and standard FF v47.0.1.
From what I found out  today, this problem definitely has to do with the **zoom** functionality [Ctrl]_[MouseWheel] of the browser:

On different zoom levels, I get regular digit (1) too small, okay or too large (compared to other digits, try e.g. prime 1103); sometimes this is accompanied by simultaneous changes in subscript digit (1) size as well (sometimes a size change in the same direction, at other times in the opposite).

Early this morning, I also got some zoom levels where the digit zero (0) suddenly looked like capital letter (O); this evening I have not been able to reproduce that ...

Another thing I observed is different spacing of indices (subscripts) whether you look at ASCIIMath (wider) or TeX (narrower).

Btw, clearing browser cache didn't make any difference.

**Comment by pkra** [comment] 2016-07-04 10:31
@zino113 I'm afraid I can't see any issues on Windows 7 either. If you could post a few screenshots (ideally as SVG to avoid artifacts from compression and with an indication regarding font-size and zoom level), that could help us at least see the issue.

**Comment by dpvc** [comment] 2016-07-05 14:13
I can reproduce it in Windows 7 with the current version of Firefox, but it appears to be a problem with the font renderer in Windows 7 (or perhaps in Firefox).  The Windows font rendering has always been lower quality than other OSes, especially at small sizes.  When you see things that change dramatically when zooming, that usually means there is a rounding issue in the renderer, and that appears to be the case here.  Even when the 1 and the 2 are in the same `<span>` so that the CSS for them is identical, they are rendered at different heights on the demo page.  That suggests that a slight difference in height of the paths for the two glyphs translates to a pixel difference in the output.

Here is a sample HTML page that tests the MathJax font in different sizes:

```
<!DOCTYPE html>
<html>
<head>
<title>Test of MathJax_Main in different sizes</title>
<style>
@font-face {
  font-family: MJX;
  src: url("http://cdn.mathjax.org/mathjax/latest/fonts/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff") format("woff");
}
.MJX {font-family: MJX}
</style>
</head>
<body>

<div class="MJX" style="font-size:50%">0123456789</div>
<div class="MJX" style="font-size:55%">0123456789</div>
<div class="MJX" style="font-size:60%">0123456789</div>
<div class="MJX" style="font-size:65%">0123456789</div>
<div class="MJX" style="font-size:70%">0123456789</div>
<div class="MJX" style="font-size:75%">0123456789</div>
<div class="MJX" style="font-size:80%">0123456789</div>
<div class="MJX" style="font-size:85%">0123456789</div>
<div class="MJX" style="font-size:90%">0123456789</div>
<div class="MJX" style="font-size:95%">0123456789</div>
<div class="MJX" style="font-size:100%">0123456789</div>
<div class="MJX" style="font-size:105%">0123456789</div>
<div class="MJX" style="font-size:110%">0123456789</div>
<div class="MJX" style="font-size:115%">0123456789</div>
<div class="MJX" style="font-size:120%">0123456789</div>
<div class="MJX" style="font-size:125%">0123456789</div>
<div class="MJX" style="font-size:130%">0123456789</div>
<div class="MJX" style="font-size:135%">0123456789</div>
</body>
</html>
```

The output for this in Firefox on Windows 7 is:

<img width="123" alt="ff-win7" src="https://cloud.githubusercontent.com/assets/432782/16587151/35e3f390-4297-11e6-9393-4abd2d8fe50c.png">

and for comparison, in IE11 on Windows 7 is:

<img width="120" alt="ie11-win7" src="https://cloud.githubusercontent.com/assets/432782/16587165/435ba73e-4297-11e6-995a-504d5fda1317.png">

The output for this in Firefox on Mac OS X is:

<img width="121" alt="ff-osx" src="https://cloud.githubusercontent.com/assets/432782/16587134/21f5ebf4-4297-11e6-81c3-101baf44c107.png">

The Firefox output in Windows 7 is by far the worst, and it appears they are using a different renderer than IE11 (Windows 7 has several choices), and its results are inferior.  There are many anomalies (in the 0's, 2's, 3's, 6's, etc.) in nearly all sizes.  Note also that the sizes don't scale up smoothly, but seem to be clamped to whole pixel sizes somewhere along the line.  So the results are pretty poor.  Note that the 1 seems large in the smaller sizes.

Contrast that to IE11's output, which is much smoother, but still shows some issues (heights of 1, 4, 5, and 7) in the smaller sizes.  Note that the 1 seems a little short in the smaller sizes.

Finally, the Firefox output on Mac OS X is smooth and accurate throughout all the sizes.

In conclusion, Firefox output in Windows 7 is poor compared to other browsers and other OSes.  While the anomalies may be due to slight differences in the heights of the paths for the various glyphs (they were produced automatically from the TeX fonts by tracing paths around the bitmapped versions, so some differences undoubtedly do exist), it si not clear that manually adjusting the paths would help.  For example, the heights of the 1 are too high in Firefox on Windows 7, while they are too short in IE11, so fixing the output for Firefox would degrade the output for IE11.

I'm marking this a browser bug, and I'm afraid that I don't think there is much that we can do about it.  I admit that I am not a font expert, and I don't know all the ins and outs of Windows, so if anyone has information that would allow for an improvement, here, I'd be happy to hear it.

**Comment by zino113** [comment] 2016-07-05 17:05
@pkra 
Thanks for that demonstration (I'm not HTML-savvy enough to produce such a test page in short time).
Looking at the output examples, that's exactly what I tried to describe in words.
Yesterday I had the chance to compare results on a W8 (v8.0 that is) machine, those were not as grave as on W7 or Vista. (I vaguely remember that it looked alright in Iceweasel on a Debian machine.) So on the whole I tend to agree with you that this isn't your problem ...

Some sidestep:
When you write
> The Firefox output in Windows 7 is by far the worst, and it appears they are using a different renderer than IE11 (Windows 7 has several choices), and its results are inferior.<
do you mean that I (as a user) have a choice, or are you talking of use of the API..?

Thanks
-Z

**Comment by dpvc** [comment] 2016-07-05 17:10
> do you mean that I (as a user) have a choice, or are you talking of use of the API..?

I mean that the Firefox programmers had a choice.  There are several fond rendering technologies available in Windows.  For example, see this (fairly old) article about [font rendering](https://www.smashingmagazine.com/2012/04/a-closer-look-at-font-rendering/).  There are probably newer ones, but this is the first one I could lay my hands on.

PS, this is dlvc, not pkra.

**Comment by zino113** [comment] 2016-07-05 17:24
@dpvc 
Davide, I'm aware of that :) Must have happened (means: switched back) while I was updating my comment (fiddling with layout of the quotatation). I'm relatively uneasy at forums as well :)
-Z

**Comment by zino113** [comment] 2016-07-05 18:04
@dpvc 
Thanks for the link -- has made an interesting read; I'm interested in fonts but having used them rather intuitively most of the time I wasn't aware of those subtleties ...
-Z

**Comment by zino113** [comment] 2016-07-05 18:35
@dpvc 
Thanks for the link -- has made an interesting read; I'm interested in fonts but having used them rather intuitively most of the time I wasn't aware of those subtleties ...
-Z

**Comment by pkra** [comment] 2016-07-13 14:55
Closing this since we can't do anything reasonable about this.

**Closed by pkra** 2016-07-13 14:55 UTC
Labels: Accepted, Browser Bug
