### ISSUE TITLE
MJ4: cdot has inconsistent spacing

### ISSUE THREAD

**Issue by AlexEdgcomb** [mathjax/MathJax#3059] opened 2023-06-06 15:30 UTC
### Issue Summary

In 4.0.0-alpha.1, `\cdot` has less surrounding space when the first operand is math and second operand is text, than any other permutation.

### Steps to Reproduce:

1. Go to https://codepen.io/alexedgcomb/pen/vYQYGvE

Observed: Second typesetting has less spacing around cdot than other typesettings
<img width="47" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/d055a21c-3ae3-4981-91db-0059bd69fe4e">

Expected: Each typesetting to have the same spacing around cdot, like in MJ3:
https://codepen.io/alexedgcomb/pen/dyQyMQx
<img width="36" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/d8b0d6bc-f5a5-4edf-ae7f-cb812cecef8b">

### Technical details:

* MathJax Version: 4.0.0-alpha.1
* Client OS: MacOS 13.2.1
* Browser: Firefox 113, Chrome 113, Safari 16.3

I am NOT using a MathJax configuration and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax-full@4.0.0-alpha.1/es5/tex-mml-svg.min.js"></script>
```

### Supporting information:

MJ2 also has equal spacing around cdot:
https://codepen.io/alexedgcomb/pen/XWyWdyP
<img width="36" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/1582a1be-eba0-4144-a521-ee45379ec2f7">

**Comment by dpvc** [comment] 2023-06-06 18:08
This is actually a duplicate of #3055, which is due to the semantic enrichment that is on by default in v4.  It seems to be mishandling `<mtext>` elements that are produced by `\text{}`, and is putting an `<mrow>` around the `a\cdot`, making the `\cdot` a postfix operator rather than an infix one, as though it were `{a\cdot}\text{b}`.

**Comment by dpvc** [comment] 2023-06-06 18:10
PS, it is not specific to `\cdot`, as any info operator followed by `\text{}` will likely do the same thing.

**Comment by AlexEdgcomb** [comment] 2023-06-06 18:14
@dpvc , got it. Thanks for explaining!

**Closed** 2023-06-06 18:16 UTC
Labels: Duplicate, v4
