### ISSUE TITLE
Preview HTML renderer doesn't honor "displayAlign" setting

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#1848] opened 2017-09-29 08:11 UTC
The Preview HTML renderer doesn't seem to honor the "displayAlign" setting (and probably the "displayIndent" setting neither). That's a problem if you set it to anything but "center" because then the rendered LaTeX will jump from the center to the left/right when being typeset with the high-quality renderer.

**Comment by pkra** [comment] 2017-09-29 08:58
That's expected as it has not been implemented; the PreviewHTML output is not feature complete.

To work around this, set the `text-align` for the `MJXp-display` class.

**Comment by dpvc** [comment] 2020-05-12 17:19
Duplicate of #1713.

**Comment by dpvc** [comment] 2022-03-11 14:02
MathJax v3 no longer has a PreviewHTML renderer.

**Closed by dpvc** 2022-03-11 14:02 UTC
Labels: Duplicate
