### ISSUE TITLE
Line breaks doesn't work for long text

### ISSUE THREAD

**Issue by suryateja619** [mathjax/MathJax#1818] opened 2017-08-08 16:39 UTC
Hi,
I have a use case where we have a long text being used with double quotes inside the ``(backticks) which will eventually overflow the text outside of the container. It works fine if I don't use the double quotes.

Ex: `(a + b) "Some long text in here"`

I'm using **AM_HTMLorMML** config. 

Here are my settings for having line breaks.

`MathJax.Hub.Config({
      "HTML-CSS": { linebreaks: { automatic: true, width: "container" } }
    });`

Any thoughts?

**Comment by pkra** [comment] 2017-08-08 20:01
This is a duplicate of https://github.com/mathjax/MathJax/issues/1648. The asciimath input will generate a single `mtext` element with a long string -- and we don't support line-breaks within such token elements yet.

**Comment by suryateja619** [comment] 2017-08-08 20:04
@pkra Do you have any plans for supporting it in the future?

**Closed** 2017-08-08 20:04 UTC
Labels: Duplicate

**Comment by pkra** [comment] 2017-08-09 15:29
Yes, #1648 is the "future release" milestone (which indicates intent to implement).
