### ISSUE TITLE
Math is repeated in <select> (new in 2.6.1 compared to 2.4)

### ISSUE THREAD

**Issue by dqnykamp** [mathjax/MathJax#1400] opened 2016-02-26 20:50 UTC
I recently upgraded from MathJax 2.4 to 2.6.1.  I have discovered a bug in 2.6.1 that wasn't present in 2.4.   Inside an option of a select, MathJax renders correctly when showing the drop down list, but the math is repeated once the option is selected.  It worked fine with MathJax 2.4.  Here are temporary files that illustrate the bug.

MathJax 2.6.1 version:  [http://mathinsight.org/static/test/select_mathjax_new.html](http://mathinsight.org/static/test/select_mathjax_new.html)
MathJax 2.4 version: [http://mathinsight.org/static/test/select_mathjax_old.html](http://mathinsight.org/static/test/select_mathjax_old.html)

Also, as you'll notice if you select the last option, subscripts are not rendered correctly in selected options for either version of MathJax.  This never bothered me enough to report it earlier, but since I'm making this report, I'll mention it here.

**Comment by dpvc** [comment] 2016-02-27 20:44
The `<option>` tag can only contain plain text, not HTML tags (see the [HTML standard](https://html.spec.whatwg.org/multipage/forms.html#the-option-element) for it, which lists the content model as text).  Since MathJax output always involves HTML tags, not just text, MathJax output is invalid within `<option>` tags, and hence within `<select>` tags.  So you should not use MathJax within pop-up menus.

The reason you are seeing double equations is because in v2.6, we added an AssistiveMML extension that adds a hidden MathML copy of the expression to be used by screen readers for this with visual impairments.  When used inside `<option>`, the HTML tags (together with the CSS that hides the MathML from the visual presentation) are ignored, and the text content of all the tags (include the "hidden" MathML) are used as the content of the `<option>`.  So you see two copies, one for the original MathJax output, and one for the AssistiveMML output.

This is the expected behavior of the HTML in this case, so I'm marking it as such.

**Closed** 2016-02-29 13:14 UTC
Labels: Expected Behavior
