### ISSUE TITLE
Equation is cutting on the safari browsers

### ISSUE THREAD

**Issue by uc-asv** [mathjax/MathJax#2592] opened 2020-12-24 10:48 UTC
### Issue Summary
The equation is cutting on the safari browser only. The issue can be produced by reducing the viewport or width of the browser.
How can I fix this issue?

Math ml code:
`<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <mi>A</mi>
    <mo>=</mo>
    <mrow>
      <mo>{</mo>
      <mrow>
        <mtable columnalign="right right center left" columnspacing="0.3em">
          <mtr>
            <mtd>
              <mrow>
                <mstyle displaystyle="true">
                  <munderover>
                    <mo>&#x2211;</mo>
                    <mrow>
                      <mi>i</mi>
                      <mo>=</mo>
                      <mn>0</mn>
                    </mrow>
                    <mrow>
                      <mi>n</mi>
                      <mo>&#x2212;</mo>
                      <mn>2</mn>
                    </mrow>
                  </munderover>
                  <mrow>
                    <msup>
                      <mn>2</mn>
                      <mi>i</mi>
                    </msup>
                    <msub>
                      <mi>a</mi>
                      <mi>i</mi>
                    </msub>
                  </mrow>
                </mstyle>
              </mrow>
            </mtd>
            <mtd>
              <mrow>
                <mspace width="1.5em"></mspace>
                <mtext>if</mtext>
                <mtext></mtext>
                <msub>
                  <mi>a</mi>
                  <mrow>
                    <mi>n</mi>
                    <mo>&#x2212;</mo>
                    <mn>1</mn>
                  </mrow>
                </msub>
              </mrow>
            </mtd>
            <mtd>
              <mo>=</mo>
            </mtd>
            <mtd>
              <mn>0</mn>
            </mtd>
          </mtr>
          <mtr>
            <mtd>
              <mrow>
                <mo>&#x2212;</mo>
                <mstyle displaystyle="true">
                  <munderover>
                    <mo>&#x2211;</mo>
                    <mrow>
                      <mi>i</mi>
                      <mo>=</mo>
                      <mn>0</mn>
                    </mrow>
                    <mrow>
                      <mi>n</mi>
                      <mo>&#x2212;</mo>
                      <mn>2</mn>
                    </mrow>
                  </munderover>
                  <mrow>
                    <msup>
                      <mn>2</mn>
                      <mi>i</mi>
                    </msup>
                    <msub>
                      <mi>a</mi>
                      <mi>i</mi>
                    </msub>
                  </mrow>
                </mstyle>
              </mrow>
            </mtd>
            <mtd>
              <mrow>
                <mtext>if</mtext>
                <mtext></mtext>
                <msub>
                  <mi>a</mi>
                  <mrow>
                    <mi>n</mi>
                    <mo>&#x2212;</mo>
                    <mn>1</mn>
                  </mrow>
                </msub>
              </mrow>
            </mtd>
            <mtd>
              <mo>=</mo>
            </mtd>
            <mtd>
              <mn>1</mn>
            </mtd>
          </mtr>
        </mtable>
      </mrow>
    </mrow>
  </mrow>
</math>`

Screenshot: 

https://ucertify.tinytake.com/tt/NDk1MjQ0OV8xNTU5ODA3MQ
https://ucertify.tinytake.com/tt/NDk1MjQ0OV8xNTU5ODA3MQ

### Technical details:

* MathJax Version: https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js
* Client OS: Mac OS
* Browser: Safari 12.0.1 (14606.2.104.1.1)

**Comment by dpvc** [comment] 2020-12-26 17:34
Thank you for your report. This is a duplicate of #2435 (and several others) and is being investigated as part of the font work we are currently doing.

**Comment by uc-asv** [comment] 2020-12-28 04:01
So for now this can't be fixed right?

**Comment by dpvc** [comment] 2020-12-28 12:05
In the CHTML output, that is correct.  The SVG output works in Safari (but there are reports of some issues with scaled versions of minus and plus in Chrome in SVG).

**Comment by dpvc** [comment] 2021-02-01 16:18
Closing as a duplicate.

**Closed by dpvc** 2021-02-01 16:18 UTC
Labels: Duplicate, v3
