### ISSUE TITLE
[CommonHTML] Poor over script position above italic letters

### ISSUE THREAD

**Issue by samdooley** [mathjax/MathJax#1735] opened 2017-04-14 21:32 UTC
### Issue Summary

Over script characters that are positioned above italic characters appear too far to the right, as if the italic correction is not handled properly.

### Steps to Reproduce

1.  Load the following HTML example page.

```
<script type="text/javascript"
   src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=MML_CHTML">
</script>

<math xmlns="http://www.w3.org/1998/Math/MathML" mathsize="36pt">
  <mover>
    <mrow>
      <mi>X</mi>
      <mo>&#x2063;</mo>
      <mi>J</mi>
    </mrow>
    <mo>&#x23dc;</mo>
  </mover>
  <mo>=</mo>
  <mover>
    <mrow>
      <mtext mathvariant="italic">X</mtext>
      <mo>&#x2063;</mo>
      <mtext mathvariant="italic">J</mtext>
    </mrow>
    <mo>&#x23dc;</mo>
  </mover>
</math>
```

2.  Observe the horizontal position of the over script character in relation to the italic base letters.

This is a bug because the extent of the over script character should match the extent of the base letters, after accounting for the italic slant of the characters.  The over script extends too far to the right, especially for the case on the left that uses mi elements.

### Technical details

* MathJax Version: 2.7.0 release
* Client OS: Windows
* Browser: Chrome

![mover-italic](https://cloud.githubusercontent.com/assets/4752336/25056581/13ec0560-2127-11e7-941c-c5efa136fee1.png)

**Comment by pkra** [comment] 2017-04-16 13:28
Thanks for the report. I can reproduce this with the CommonHTML output on Chrome and Firefox.

**Comment by dpvc** [comment] 2017-04-16 18:03
I believe the problem is [this line](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/CommonHTML/jax.js#L1418), which bubbles the accent skew up from lower nodes to higher nodes.  The skew value is only supposed to be used if base is a single character, but this propagates the skew value for all cases.  I think

```
            if (cbox.skew && this.data.length === 1) bbox.skew = cbox.skew;
```

would do the trick.

**Comment by samdooley** [comment] 2017-04-17 16:39
Thanks for the patch.  I was able to test it with a local 2.7.0 and it is better, but I believe the line above needs the same treatment.  So I think:

            if (cbox.ic && this.data.length === 1) {bbox.ic = cbox.ic} else {delete bbox.ic}
            if (cbox.skew && this.data.length === 1) bbox.skew = cbox.skew;

does the trick, both for arc(XJ) and arc(XY).

**Comment by dpvc** [comment] 2017-07-07 12:38
The `issue1735` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment] 2017-07-10 17:19
==> Merged.

**Comment by dpvc** [comment] 2017-07-15 01:05
==> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/mover/issue1735.html

**Closed** 2017-07-15 01:05 UTC
Labels: Accepted, Merged, Test Available
