### ISSUE TITLE
`<mspace linebreak="newline" />` not working.

### ISSUE THREAD

**Issue by henok-tesfaye** [mathjax/MathJax#2495] opened 2020-08-10 07:33 UTC
### Issue Summary

`<mspace linebreak="newline" />` not working tried it in [Mathjax demo page](https://www.mathjax.org/#demo).
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
    <mi>H</mi>
    <mi>o</mi>
    <mi>r</mi>
    <mi>i</mi>
    <mi>z</mi>
    <mi>o</mi>
    <mi>n</mi>
    <mi>t</mi>
    <mi>a</mi>
    <mi>l</mi>
    <mo></mo>
    <mi>a</mi>
    <mi>s</mi>
    <mi>y</mi>
    <mi>m</mi>
    <mi>p</mi>
    <mi>t</mi>
    <mi>o</mi>
    <mi>t</mi>
    <mi>e</mi>
    <mfenced>
        <mi>s</mi>
    </mfenced>
    <mo>=</mo>
    <mrow>
        <mrow>
            <mfenced close="}" open="{">
                <mrow>
                    <mi>y</mi>
                    <mo>=</mo>
                    <mn>0</mn>
                    <mo>.</mo>
                    <mn>750</mn>
                </mrow>
            </mfenced>
        </mrow>
    </mrow>
    <mspace linebreak="newline"/>
    <mi>V</mi>
    <mi>e</mi>
    <mi>r</mi>
    <mi>t</mi>
    <mi>i</mi>
    <mi>c</mi>
    <mi>a</mi>
    <mi>l</mi>
    <mo></mo>
    <mi>a</mi>
    <mi>s</mi>
    <mi>y</mi>
    <mi>m</mi>
    <mi>p</mi>
    <mi>t</mi>
    <mi>o</mi>
    <mi>t</mi>
    <mi>e</mi>
    <mfenced>
        <mi>s</mi>
    </mfenced>
    <mo>=</mo>
    <mrow>
        <mrow>
            <mfenced close="}" open="{">
                <mrow>
                    <mi>x</mi>
                    <mo>=</mo>
                    <mo>-</mo>
                    <mn>3</mn>
                    <mo>.</mo>
                    <mn>000</mn>
                    <mo>,</mo>
                    <mi>x</mi>
                    <mo>=</mo>
                    <mn>1</mn>
                    <mo>.</mo>
                    <mn>250</mn>
                </mrow>
            </mfenced>
        </mrow>
    </mrow>
</math>
```

### Steps to Reproduce:

1. Open https://www.mathjax.org/#demo 
2. Go to live demo section
3. Copy paste the above snippet

Expected Behavior: Vertical Asymptote text should be displayed in a new line

### Technical details:

* MathJax Version: 2.3 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Mac OS X 10.14.6
* Browser: Chrome 84.0.4147.105 (Official Build) (64-bit)

**Comment by dpvc** [comment] 2020-08-10 13:03
Line breaking is not yet implemented in v3 (some v2 features are still being ported).

This is a duplicate of #2312 (and  #2382, #2418, and #2491).

**Comment by chrispitude** [comment] 2020-10-08 20:44
How's this feature coming along (for MathML rendering)?

**Comment by dpvc** [comment] 2020-10-11 19:14
@chrispitude, It is scheduled for second-quarter next year.

**Comment by chrispitude** [comment] 2020-10-11 23:49
Thanks @dpvc!

**Comment by dpvc** [comment] 2021-02-01 16:59
Closing as a duplicate.

**Closed by dpvc** 2021-02-01 16:59 UTC
Labels: Duplicate, v3
