### ISSUE TITLE
Rendering problem in Safari

### ISSUE THREAD

**Issue by AndreyAkinshin** [mathjax/MathJax#2459] opened 2020-06-22 12:57 UTC
### Issue Summary

I have a problem with math expression rendering in Safari on macOS: 
![image](https://user-images.githubusercontent.com/2259237/85289801-a6893b80-b4a0-11ea-86fe-df7b5e5efc47.png)

If I use other browsers or operating systems, everything is OK.

### Steps to Reproduce:

Open https://aakinshin.net/posts/harrell-davis-double-mad-outlier-detector/ in Safari on macOS

### Technical details:

* MathJax Import:
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```
* Client OS: Mac OS X 10.15.5
* Browser: Version 13.1.1 (15609.2.9.1.2)

**Comment by dpvc** [comment] 2020-06-22 13:02
Thank you for your report.  This is a duplicate of #2435 and is being investigated as part of the font update this summer.

**Comment by auduchinok** [comment] 2020-07-23 18:16
It seems to be fixed in Safari 14 beta.
<img width="1436" alt="Screenshot 2020-07-23 at 21 15 55" src="https://user-images.githubusercontent.com/3923587/88322671-b6a76b80-cd29-11ea-8de7-6f3924238432.png">

**Comment by dpvc** [comment] 2021-02-01 17:07
Closing as a duplicate.

**Closed by dpvc** 2021-02-01 17:07 UTC
Labels: Duplicate
