### ISSUE TITLE
Bug: Missing space after '=' when using '^'

### ISSUE THREAD

**Issue by SeanFlemingMathsPathway** [mathjax/MathJax#2206] opened 2019-09-22 04:11 UTC
### Issue Summary
For the majority of equations, MathJax inserts a "space" between the '=' sign and the content that sits either side of it.
However, when you use a number that uses indices (^) on the first number after the '=', then no space is present.

### Steps to Reproduce

1. Go to the [MathJax demo](https://www.mathjax.org/#demo) site
2. Paste the following equation in:
```
\(\begin{align}(3^3)^2&amp;=(3^3)\times(3^3)\\&amp;= 3^{3+3}\\&amp;=3\end{align}\)
```
3. Click the "Render HTML" button.

You will notice that the second line of the equation looks out of alignment with the line above and below.

This is also reproducible with a much simpler example of:
```
\(3=3^2\)
```

### Technical details

* MathJax Version: (3.0) master - latest commit: [a043a3f83d3e88b2bfd74a2c562c575b0f210b23](https://github.com/mathjax/MathJax/commit/a043a3f83d3e88b2bfd74a2c562c575b0f210b23)
* Client OS: Windows 10 64 bit
* Browsers: 
  * Chrome (Version 76.0.3809.132 (Official Build) (64-bit))
  * Firefox (70.0b7 (64-bit))

**Comment by dpvc** [comment] 2019-09-22 09:26
Thanks for the report.  This is a duplicate of #2187, which is fixed by PR mathjax/MathJax-src#344.

**Comment by SeanFlemingMathsPathway** [comment] 2019-09-22 11:16
Thanks for the response, apologies for not detecting the duplicate.

**Comment by dpvc** [comment] 2019-09-22 11:17
No problem.  It was not titled in a way that you would recognize it (I changed the title to make it more apparent).

**Closed** 2019-09-22 14:01 UTC
Labels: Duplicate
