### ISSUE TITLE
Mathjax renders multiple instances of equations

### ISSUE THREAD

**Issue by moorepants** [mathjax/MathJax#1070] opened 2015-02-27 01:18 UTC
For example I'm viewing:
http://docs.scipy.org/doc/scipy/reference/tutorial/fftpack.html#fast-fourier-transforms
with Firefox 35.0.1 on Ubuntu 14.04 and I see:
![selection_056](https://cloud.githubusercontent.com/assets/276007/6405683/537a6638-bddb-11e4-8dbb-8ef6e411e712.png)

The same result is in Chromium too.

My entire dissertation also renders this way: http://moorepants.github.io/dissertation/

This seemed to only have changed in last week or so.

**Comment by pkra** [comment] 2015-02-27 08:43
This looks like a duplicate of https://github.com/mathjax/MathJax/issues/1068. 

Please clear your browser cache.

**Closed** 2015-03-03 21:26 UTC
Labels: Duplicate
