### ISSUE TITLE
Multiple Subscripts produce render error

### ISSUE THREAD

**Issue by korny** [mathjax/MathJax#1207] opened 2015-07-03 10:57 UTC
I think that `$H_2_0$` is a valid LaTeX expression, and should render the same as `$H_{20}$`.

MathJax however does not render this correctly:
<img width="455" alt="screenshot_01" src="https://cloud.githubusercontent.com/assets/1037292/8498062/cd714bfe-2182-11e5-8237-a2020acd7f7c.png">

As far as I know, this used to work with MathJax 2.4.

**Comment by dpvc** [comment] 2015-07-03 11:22
>  I think that `$H_2_0$` is a valid LaTeX expression.

It turns out that it is not.  This produces an error message about ambiguous subscripts, and that is the same error that MathJax produces.  You need to disambiguate it as either `$H_{2_0}$` or `${H_2}_0$`.  This is a duplicate of issue #1054; please see that issue for further details.

**Closed** 2015-07-03 11:23 UTC
Labels: Expected Behavior

**Comment by korny** [comment] 2015-07-03 11:37
I see. Thanks for the quick reply!
