### ISSUE TITLE
Upgrading from 3.1.2 to 3.1.4 causes style breakage

### ISSUE THREAD

**Issue by artagnon** [mathjax/MathJax#2699] opened 2021-05-31 15:54 UTC
I'm using `mathjax-full` to do server-side rendering of HTML with the TeX-CHTML driver. When I upgraded from 3.1.2 to 3.1.4, I got quite a large diff on all my pages, and the style seems to be broken now. I don't have any custom styles for MathJaX that I'm either imposing or injecting, so I'm not sure what the problem is. Here's the diff of one of my pages; in particular, notice the "font-size: 26520%":

```diff
diff --git a/math.html b/math.html
index 4230e31..42eab5c 100644
--- a/math.html
+++ b/math.html
@@ -189,11 +189,6 @@ mjx-msub {
   text-align: left;
 }

-mjx-TeXAtom {
-  display: inline-block;
-  text-align: left;
-}
-
 mjx-c {
   display: inline-block;
 }
@@ -416,19 +411,11 @@ mjx-c.mjx-c1D49E.TEX-SC::before {
   content: "C";
 }

-[noIC] mjx-c.mjx-c1D49E.TEX-SC:last-child::before {
-  padding-right: 0.666em;
-}
-
 mjx-c.mjx-c1D4A2.TEX-SC::before {
   padding: 0.717em 0.738em 0.037em 0;
   content: "G";
 }

-[noIC] mjx-c.mjx-c1D4A2.TEX-SC:last-child::before {
-  padding-right: 0.61em;
-}
-
 mjx-c.mjx-c1D54B.TEX-A::before {
   padding: 0.683em 0.667em 0 0;
   content: "T";
@@ -446,7 +433,7 @@ mjx-c.mjx-c1D6AB.TEX-B::before {
           Mathematical notes
         </h1>
         <div id="metadata">
-          <span id="timestamp"><time class="begin" datetime="2018-09-23">Sun, 23 Sep 2018 07:00:00 +0530</time><span class="to"><img src="/dist/icon.arrow.svg"></span><time class="end" datetime="2021-05-29">Sat, 29 May 2021 20:00:00 +0200</time></span><br><span id="locations">Paris</span>
+          <span id="timestamp"><time class="begin" datetime="2018-09-23">Sun, 23 Sep 2018 07:00:00 +0530</time><span class="to"><img src="/dist/icon.arrow.svg"></span><time class="end" datetime="2021-05-31">Mon, 31 May 2021 17:00:00 +0200</time></span><br><span id="locations">Paris</span>
         </div>
       </header>
       <article>
@@ -482,16 +469,16 @@ mjx-c.mjx-c1D6AB.TEX-B::before {
             <a href="/math/inf/mapping-spaces">Mapping spaces in higher category theory</a>
           </li>
           <li>
-            <a href="/math/inf/thomason-modelcat">The Thomason model structure on <mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-TeXAtom texclass="ORD"><mjx-mi class="mjx-ds mjx-b"><mjx-c class="mjx-c2102 TEX-A"></mjx-c></mjx-mi><mjx-mi class="mjx-ds mjx-b"><mjx-utext style="font-size: 88.4%; padding: 0.848em 0 0.226em 0" variant="double-struck">𝕒</mjx-utext></mjx-mi><mjx-mi class="mjx-ds mjx-b"><mjx-utext style="font-size: 88.4%; padding: 0.848em 0 0.226em 0" variant="double-struck">𝕥</mjx-utext></mjx-mi></mjx-TeXAtom></mjx-math></mjx-container></a>
+            <a href="/math/inf/thomason-modelcat">The Thomason model structure on <mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-mi class="mjx-ds mjx-b"><mjx-c class="mjx-c2102 TEX-A"></mjx-c><mjx-utext style="font-size: 200%; padding: 0.375em 0 0.1em 0" variant="double-struck">𝕒</mjx-utext><mjx-utext style="font-size: 200%; padding: 0.375em 0 0.1em 0" variant="double-struck">𝕥</mjx-utext></mjx-mi></mjx-math></mjx-container></a>
           </li>
           <li>
-            <a href="/math/inf/cg-comprehensive">A comprehensive study of <mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-TeXAtom texclass="ORD"><mjx-mi class="mjx-sc mjx-i"><mjx-c class="mjx-c1D49E TEX-SC"></mjx-c></mjx-mi><mjx-mi class="mjx-sc mjx-i"><mjx-c class="mjx-c1D4A2 TEX-SC"></mjx-c></mjx-mi></mjx-TeXAtom></mjx-math></mjx-container></a>
+            <a href="/math/inf/cg-comprehensive">A comprehensive study of <mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-mi class="mjx-sc mjx-i"><mjx-c class="mjx-c1D49E TEX-SC"></mjx-c><mjx-c class="mjx-c1D4A2 TEX-SC"></mjx-c></mjx-mi></mjx-math></mjx-container></a>
           </li>
           <li>
-            <a href="/math/inf/joins">Joins in <mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-TeXAtom texclass="ORD"><mjx-mi class="mjx-ds mjx-b"><mjx-c class="mjx-c2102 TEX-A"></mjx-c></mjx-mi><mjx-mi class="mjx-ds mjx-b"><mjx-utext style="font-size: 88.4%; padding: 0.848em 0 0.226em 0" variant="double-struck">𝕒</mjx-utext></mjx-mi><mjx-mi class="mjx-ds mjx-b"><mjx-utext style="font-size: 88.4%; padding: 0.848em 0 0.226em 0" variant="double-struck">𝕥</mjx-utext></mjx-mi></mjx-TeXAtom></mjx-math></mjx-container>, <mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-TeXAtom texclass="ORD"><mjx-mi class="mjx-ds mjx-b"><mjx-c class="mjx-c1D54B TEX-A"></mjx-c></mjx-mi><mjx-mi class="mjx-ds mjx-b"><mjx-utext style="font-size: 88.4%; padding: 0.848em 0 0.226em 0" variant="double-struck">𝕠</mjx-utext></mjx-mi><mjx-mi class="mjx-ds mjx-b"><mjx-utext style="font-size: 88.4%; padding: 0.848em 0 0.226em 0" variant="double-struck">𝕡</mjx-utext></mjx-mi></mjx-TeXAtom></mjx-math></mjx-container>, and Set<mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-msub><mjx-mi class="mjx-n" noIC="true"></mjx-mi><mjx-script style="vertical-align: -0.15em"><mjx-mi class="mjx-b" size="s"><mjx-c class="mjx-c1D6AB TEX-B"></mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-math></mjx-container></a>
+            <a href="/math/inf/joins">Joins in <mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-mi class="mjx-ds mjx-b"><mjx-c class="mjx-c2102 TEX-A"></mjx-c><mjx-utext style="font-size: 200%; padding: 0.375em 0 0.1em 0" variant="double-struck">𝕒</mjx-utext><mjx-utext style="font-size: 200%; padding: 0.375em 0 0.1em 0" variant="double-struck">𝕥</mjx-utext></mjx-mi></mjx-math></mjx-container>, <mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-mi class="mjx-ds mjx-b"><mjx-c class="mjx-c1D54B TEX-A"></mjx-c><mjx-utext style="font-size: 200%; padding: 0.375em 0 0.1em 0" variant="double-struck">𝕠</mjx-utext><mjx-utext style="font-size: 200%; padding: 0.375em 0 0.1em 0" variant="double-struck">𝕡</mjx-utext></mjx-mi></mjx-math></mjx-container>, and Set<mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-msub><mjx-mi class="mjx-n"></mjx-mi><mjx-script style="vertical-align: -184.756em"><mjx-mi class="mjx-b" style="font-size: 26520%"><mjx-c class="mjx-c1D6AB TEX-B"></mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-math></mjx-container></a>
           </li>
           <li>
-            <a href="/math/inf/cg-properties">Properties of <mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-TeXAtom texclass="ORD"><mjx-mi class="mjx-sc mjx-i"><mjx-c class="mjx-c1D49E TEX-SC"></mjx-c></mjx-mi><mjx-mi class="mjx-sc mjx-i"><mjx-c class="mjx-c1D4A2 TEX-SC"></mjx-c></mjx-mi></mjx-TeXAtom></mjx-math></mjx-container></a>
+            <a href="/math/inf/cg-properties">Properties of <mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-mi class="mjx-sc mjx-i"><mjx-c class="mjx-c1D49E TEX-SC"></mjx-c><mjx-c class="mjx-c1D4A2 TEX-SC"></mjx-c></mjx-mi></mjx-math></mjx-container></a>
           </li>
           <li>
             <a href="/math/inf/enrichment-cat">Enrichment in category theory</a>
@@ -500,7 +487,7 @@ mjx-c.mjx-c1D6AB.TEX-B::before {
             <a href="/math/inf/monoidal-cat">Monoidal categories</a>
           </li>
           <li>
-            <a href="/math/inf/model-sset">The model structure on Set<mjx-container class="MathJax" jax="CHTML" style="font-size: 113.1%"><mjx-math class=" MJX-TEX"><mjx-msub><mjx-mi class="mjx-n" noIC="true"></mjx-mi><mjx-script style="vertical-align: -0.15em"><mjx-mi class="mjx-b" size="s"><mjx-c class="mjx-c1D6AB TEX-B"></mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-math></mjx-container></a>
+            <a href="/math/inf/model-sset">The model structure on Set<mjx-container class="MathJax" jax="CHTML" style="font-size: 50%"><mjx-math class=" MJX-TEX"><mjx-msub><mjx-mi class="mjx-n"></mjx-mi><mjx-script style="vertical-align: -184.756em"><mjx-mi class="mjx-b" style="font-size: 26520%"><mjx-c class="mjx-c1D6AB TEX-B"></mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-math></mjx-container></a>
           </li>
           <li>
             <a href="/math/inf/outline">An outline for studying higher category theory</a>
```

**Comment by dpvc** [comment] 2021-06-01 12:46
This is a duplicate of #2694.  It will be resolved in the next release, but there is a work-around listed in that issue that you can use in the meantime.

**Closed** 2021-07-06 21:29 UTC
Labels: Duplicate, Fixed, v3, v3.2
