### ISSUE TITLE
Vertical lines at the end of a formula

### ISSUE THREAD

**Issue by cljkoopman** [mathjax/MathJax#1402] opened 2016-02-29 16:30 UTC
Hi,

I use in Moodle 2.9 and 3.0 http://cdn.mathjax.org/mathjax/2.5-latest/MathJax.js

I get this (just the last months), vertical lines at the end of formulas etc.:

![image](https://cloud.githubusercontent.com/assets/17550898/13400858/07e50628-df0a-11e5-9a89-d52f04302b39.png)

**Comment by pkra** [comment] 2016-02-29 16:31
Duplicate of https://github.com/mathjax/MathJax/issues/1300. This was fixed in 2.6.0.

**Closed by pkra** 2016-02-29 16:31 UTC
Labels: Duplicate
