### ISSUE TITLE
find n-th root, 'n' is hidden.

### ISSUE THREAD

**Issue by weihaopeng** [mathjax/MathJax#2735] opened 2021-07-05 10:29 UTC
### Issue Summary

When I want to show find cubic root or n-th root, I find the number ( or the `mo` n) is hidden. Like this: 

![image](https://user-images.githubusercontent.com/33681454/124457331-4371fa80-ddbe-11eb-95e0-a9a0d376b9bc.png)

Then, when I try more mathml, I found when I use some n-th root mathml as adjacent sibling, the `n` in first mathml will be hidden, others will show.

![image](https://user-images.githubusercontent.com/33681454/124457941-f8a4b280-ddbe-11eb-9cbc-e98a8ce0beca.png)

### Technical details:

* MathJax Version: 3.1.4, 3.2.0
* Client OS: Windows10
* Browser: Chrome 91.0.4472.114

### Supporting information:

 * Example MathML: `<math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><msup><mn>6</mn><mn>3</mn></msup><mn>4</mn></mroot></math>`
 * Example link: https://jsbin.com/xemewowujo/1/edit?html,output

**Comment by weihaopeng** [comment] 2021-07-05 10:43
It will hidden if the mathml is the first element of a new line(block).

![image](https://user-images.githubusercontent.com/33681454/124459580-db70e380-ddc0-11eb-9cc5-23c8eb6831b2.png)

**Comment by weihaopeng** [comment] 2021-07-05 10:54
Add custom style: `m-root { width: 1px}` will fix this, but I don't know if this will bring other render bug...

**Comment by dpvc** [comment] 2021-07-05 10:55
Yes, I was looking at it and came to the same conclusion.  It also only occurs at some zoom levels, so if you zoom in or out, it sometimes appears again.

This seems to be a bug in Chrome, related to the fact that the root is placed in a box with width 0 (Chrome seems to clip those out when they appear at the beginning of a line).

A work-around for now is to add the CSS

``` css
mix-root {
  min-width: .05px;
}
```

**Comment by dpvc** [comment] 2021-07-05 10:56
Looks like you've been thinking along the same lines.  Setting the `min-width` for `mjx-root`  is better, since the width can be larger than 0 in some cases (i.e., if the root is wide, say "1000").

**Comment by weihaopeng** [comment] 2021-07-06 01:37
Yes, `min-width` is better. It's true that chrome has this problem, but firebox doesn't. I'll try to find the reason. It's so confusing.

**Comment by dpvc** [comment] 2022-01-18 14:39
I'm no longer able to reproduce this, so I suspect it has been fixed in current versions of Chrome.

**Closed** 2022-08-05 23:10 UTC
Labels: Accepted, Browser Bug, v3, Code Example
